import { EmojiInformation } from "../types/emojiInformation";

export const ACTIVITY: EmojiInformation = {
  "⚽": {
    name: "soccer-ball",
    category: "activity",
    unicode: "_26bd",
    htmlEntity: "&#x26BD",
  },
  "🏀": {
    name: "basketball",
    category: "activity",
    unicode: "_1f3c0",
    htmlEntity: "&#x1F3C0",
  },
  "🏈": {
    name: "american-football",
    category: "activity",
    unicode: "_1f3c8",
    htmlEntity: "&#x1F3C8",
  },
  "⚾": {
    name: "baseball",
    category: "activity",
    unicode: "_26be",
    htmlEntity: "&#x26BE",
  },
  "🥎": {
    name: "softball",
    category: "activity",
    unicode: "_1f94e",
    htmlEntity: "&#x1F94E",
  },
  "🎾": {
    name: "tennis",
    category: "activity",
    unicode: "_1f3be",
    htmlEntity: "&#x1F3BE",
  },
  "🏐": {
    name: "volleyball",
    category: "activity",
    unicode: "_1f3d0",
    htmlEntity: "&#x1F3D0",
  },
  "🏉": {
    name: "rugby-football",
    category: "activity",
    unicode: "_1f3c9",
    htmlEntity: "&#x1F3C9",
  },
  "🥏": {
    name: "flying-disc",
    category: "activity",
    unicode: "_1f94f",
    htmlEntity: "&#x1F94F",
  },
  "🪃": {
    name: "boomerang",
    category: "activity",
    unicode: "_1fa83",
    htmlEntity: "&#x1FA83",
  },
  "🎱": {
    name: "pool-8-ball",
    category: "activity",
    unicode: "_1f3b1",
    htmlEntity: "&#x1F3B1",
  },
  "🪀": {
    name: "yo-yo",
    category: "activity",
    unicode: "_1fa80",
    htmlEntity: "&#x1FA80",
  },
  "🏓": {
    name: "ping-pong",
    category: "activity",
    unicode: "_1f3d3",
    htmlEntity: "&#x1F3D3",
  },
  "🏸": {
    name: "badminton",
    category: "activity",
    unicode: "_1f3f8",
    htmlEntity: "&#x1F3F8",
  },
  "🏒": {
    name: "ice-hockey",
    category: "activity",
    unicode: "_1f3d2",
    htmlEntity: "&#x1F3D2",
  },
  "🏑": {
    name: "field-hockey",
    category: "activity",
    unicode: "_1f3d1",
    htmlEntity: "&#x1F3D1",
  },
  "🥍": {
    name: "lacrosse",
    category: "activity",
    unicode: "_1f94d",
    htmlEntity: "&#x1F94D",
  },
  "🏏": {
    name: "cricket-game",
    category: "activity",
    unicode: "_1f3cf",
    htmlEntity: "&#x1F3CF",
  },
  "🥅": {
    name: "goal-net",
    category: "activity",
    unicode: "_1f945",
    htmlEntity: "&#x1F945",
  },
  "⛳": {
    name: "flag-in-hole",
    category: "activity",
    unicode: "_26f3",
    htmlEntity: "&#x26F3",
  },
  "🪁": {
    name: "kite",
    category: "activity",
    unicode: "_1fa81",
    htmlEntity: "&#x1FA81",
  },
  "🏹": {
    name: "bow-and-arrow",
    category: "activity",
    unicode: "_1f3f9",
    htmlEntity: "&#x1F3F9",
  },
  "🎣": {
    name: "fishing-pole",
    category: "activity",
    unicode: "_1f3a3",
    htmlEntity: "&#x1F3A3",
  },
  "🤿": {
    name: "diving-mask",
    category: "activity",
    unicode: "_1f93f",
    htmlEntity: "&#x1F93F",
  },
  "🥊": {
    name: "boxing-glove",
    category: "activity",
    unicode: "_1f94a",
    htmlEntity: "&#x1F94A",
  },
  "🥋": {
    name: "martial-arts-uniform",
    category: "activity",
    unicode: "_1f94b",
    htmlEntity: "&#x1F94B",
  },
  "🎽": {
    name: "running-shirt",
    category: "activity",
    unicode: "_1f3bd",
    htmlEntity: "&#x1F3BD",
  },
  "🛹": {
    name: "skateboard",
    category: "activity",
    unicode: "_1f6f9",
    htmlEntity: "&#x1F6F9",
  },
  "🛼": {
    name: "roller-skate",
    category: "activity",
    unicode: "_1f6fc",
    htmlEntity: "&#x1F6FC",
  },
  "🛷": {
    name: "sled",
    category: "activity",
    unicode: "_1f6f7",
    htmlEntity: "&#x1F6F7",
  },
  "⛸": {
    name: "ice-skate",
    category: "activity",
    unicode: "_26f8",
    htmlEntity: "&#x26F8",
  },
  "🥌": {
    name: "curling-stone",
    category: "activity",
    unicode: "_1f94c",
    htmlEntity: "&#x1F94C",
  },
  "🎿": {
    name: "skis",
    category: "activity",
    unicode: "_1f3bf",
    htmlEntity: "&#x1F3BF",
  },
  "⛷": {
    name: "skier",
    category: "activity",
    unicode: "_26f7",
    htmlEntity: "&#x26F7",
  },
  "🏂": {
    name: "snowboarder",
    category: "activity",
    unicode: "_1f3c2",
    htmlEntity: "&#x1F3C2",
  },
  "🏂🏻": {
    name: "snowboarder-light-skin-tone",
    category: "diversity",
    unicode: "_1f3c2-1f3fb",
    htmlEntity: "&#x1F3C2;&#x1F3FB",
  },
  "🏂🏼": {
    name: "snowboarder-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f3c2-1f3fc",
    htmlEntity: "&#x1F3C2;&#x1F3FC",
  },
  "🏂🏽": {
    name: "snowboarder-medium-skin-tone",
    category: "diversity",
    unicode: "_1f3c2-1f3fd",
    htmlEntity: "&#x1F3C2;&#x1F3FD",
  },
  "🏂🏾": {
    name: "snowboarder-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f3c2-1f3fe",
    htmlEntity: "&#x1F3C2;&#x1F3FE",
  },
  "🏂🏿": {
    name: "snowboarder-dark-skin-tone",
    category: "diversity",
    unicode: "_1f3c2-1f3ff",
    htmlEntity: "&#x1F3C2;&#x1F3FF",
  },
  "🪂": {
    name: "parachute",
    category: "activity",
    unicode: "_1fa82",
    htmlEntity: "&#x1FA82",
  },
  "🏋": {
    name: "person-lifting-weights",
    category: "activity",
    unicode: "_1f3cb",
    htmlEntity: "&#x1F3CB",
  },
  "🏋🏻": {
    name: "person-lifting-weights-light-skin-tone",
    category: "diversity",
    unicode: "_1f3cb-1f3fb",
    htmlEntity: "&#x1F3CB;&#x1F3FB",
  },
  "🏋🏼": {
    name: "person-lifting-weights-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f3cb-1f3fc",
    htmlEntity: "&#x1F3CB;&#x1F3FC",
  },
  "🏋🏽": {
    name: "person-lifting-weights-medium-skin-tone",
    category: "diversity",
    unicode: "_1f3cb-1f3fd",
    htmlEntity: "&#x1F3CB;&#x1F3FD",
  },
  "🏋🏾": {
    name: "person-lifting-weights-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f3cb-1f3fe",
    htmlEntity: "&#x1F3CB;&#x1F3FE",
  },
  "🏋🏿": {
    name: "person-lifting-weights-dark-skin-tone",
    category: "diversity",
    unicode: "_1f3cb-1f3ff",
    htmlEntity: "&#x1F3CB;&#x1F3FF",
  },
  "🏋♀": {
    name: "woman-lifting-weights",
    category: "activity",
    unicode: "_1f3cb-2640",
    htmlEntity: "&#x1F3CB;&#x2640",
  },
  "🏋🏻♀": {
    name: "woman-lifting-weights-light-skin-tone",
    category: "diversity",
    unicode: "_1f3cb-1f3fb-2640",
    htmlEntity: "&#x1F3CB;&#x1F3FB;&#x2640",
  },
  "🏋🏼♀": {
    name: "woman-lifting-weights-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f3cb-1f3fc-2640",
    htmlEntity: "&#x1F3CB;&#x1F3FC;&#x2640",
  },
  "🏋🏽♀": {
    name: "woman-lifting-weights-medium-skin-tone",
    category: "diversity",
    unicode: "_1f3cb-1f3fd-2640",
    htmlEntity: "&#x1F3CB;&#x1F3FD;&#x2640",
  },
  "🏋🏾♀": {
    name: "woman-lifting-weights-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f3cb-1f3fe-2640",
    htmlEntity: "&#x1F3CB;&#x1F3FE;&#x2640",
  },
  "🏋🏿♀": {
    name: "woman-lifting-weights-dark-skin-tone",
    category: "diversity",
    unicode: "_1f3cb-1f3ff-2640",
    htmlEntity: "&#x1F3CB;&#x1F3FF;&#x2640",
  },
  "🏋♂": {
    name: "man-lifting-weights",
    category: "activity",
    unicode: "_1f3cb-2642",
    htmlEntity: "&#x1F3CB;&#x2642",
  },
  "🏋🏻♂": {
    name: "man-lifting-weights-light-skin-tone",
    category: "diversity",
    unicode: "_1f3cb-1f3fb-2642",
    htmlEntity: "&#x1F3CB;&#x1F3FB;&#x2642",
  },
  "🏋🏼♂": {
    name: "man-lifting-weights-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f3cb-1f3fc-2642",
    htmlEntity: "&#x1F3CB;&#x1F3FC;&#x2642",
  },
  "🏋🏽♂": {
    name: "man-lifting-weights-medium-skin-tone",
    category: "diversity",
    unicode: "_1f3cb-1f3fd-2642",
    htmlEntity: "&#x1F3CB;&#x1F3FD;&#x2642",
  },
  "🏋🏾♂": {
    name: "man-lifting-weights-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f3cb-1f3fe-2642",
    htmlEntity: "&#x1F3CB;&#x1F3FE;&#x2642",
  },
  "🏋🏿♂": {
    name: "man-lifting-weights-dark-skin-tone",
    category: "diversity",
    unicode: "_1f3cb-1f3ff-2642",
    htmlEntity: "&#x1F3CB;&#x1F3FF;&#x2642",
  },
  "🤼": {
    name: "people-wrestling",
    category: "activity",
    unicode: "_1f93c",
    htmlEntity: "&#x1F93C",
  },
  "🤼♀": {
    name: "women-wrestling",
    category: "activity",
    unicode: "_1f93c-2640",
    htmlEntity: "&#x1F93C;&#x2640",
  },
  "🤼♂": {
    name: "men-wrestling",
    category: "activity",
    unicode: "_1f93c-2642",
    htmlEntity: "&#x1F93C;&#x2642",
  },
  "🤸": {
    name: "person-cartwheeling",
    category: "activity",
    unicode: "_1f938",
    htmlEntity: "&#x1F938",
  },
  "🤸🏻": {
    name: "person-cartwheeling-light-skin-tone",
    category: "diversity",
    unicode: "_1f938-1f3fb",
    htmlEntity: "&#x1F938;&#x1F3FB",
  },
  "🤸🏼": {
    name: "person-cartwheeling-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f938-1f3fc",
    htmlEntity: "&#x1F938;&#x1F3FC",
  },
  "🤸🏽": {
    name: "person-cartwheeling-medium-skin-tone",
    category: "diversity",
    unicode: "_1f938-1f3fd",
    htmlEntity: "&#x1F938;&#x1F3FD",
  },
  "🤸🏾": {
    name: "person-cartwheeling-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f938-1f3fe",
    htmlEntity: "&#x1F938;&#x1F3FE",
  },
  "🤸🏿": {
    name: "person-cartwheeling-dark-skin-tone",
    category: "diversity",
    unicode: "_1f938-1f3ff",
    htmlEntity: "&#x1F938;&#x1F3FF",
  },
  "🤸♀": {
    name: "woman-cartwheeling",
    category: "activity",
    unicode: "_1f938-2640",
    htmlEntity: "&#x1F938;&#x2640",
  },
  "🤸🏻♀": {
    name: "woman-cartwheeling-light-skin-tone",
    category: "diversity",
    unicode: "_1f938-1f3fb-2640",
    htmlEntity: "&#x1F938;&#x1F3FB;&#x2640",
  },
  "🤸🏼♀": {
    name: "woman-cartwheeling-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f938-1f3fc-2640",
    htmlEntity: "&#x1F938;&#x1F3FC;&#x2640",
  },
  "🤸🏽♀": {
    name: "woman-cartwheeling-medium-skin-tone",
    category: "diversity",
    unicode: "_1f938-1f3fd-2640",
    htmlEntity: "&#x1F938;&#x1F3FD;&#x2640",
  },
  "🤸🏾♀": {
    name: "woman-cartwheeling-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f938-1f3fe-2640",
    htmlEntity: "&#x1F938;&#x1F3FE;&#x2640",
  },
  "🤸🏿♀": {
    name: "woman-cartwheeling-dark-skin-tone",
    category: "diversity",
    unicode: "_1f938-1f3ff-2640",
    htmlEntity: "&#x1F938;&#x1F3FF;&#x2640",
  },
  "🤸♂": {
    name: "man-cartwheeling",
    category: "activity",
    unicode: "_1f938-2642",
    htmlEntity: "&#x1F938;&#x2642",
  },
  "🤸🏻♂": {
    name: "man-cartwheeling-light-skin-tone",
    category: "diversity",
    unicode: "_1f938-1f3fb-2642",
    htmlEntity: "&#x1F938;&#x1F3FB;&#x2642",
  },
  "🤸🏼♂": {
    name: "man-cartwheeling-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f938-1f3fc-2642",
    htmlEntity: "&#x1F938;&#x1F3FC;&#x2642",
  },
  "🤸🏽♂": {
    name: "man-cartwheeling-medium-skin-tone",
    category: "diversity",
    unicode: "_1f938-1f3fd-2642",
    htmlEntity: "&#x1F938;&#x1F3FD;&#x2642",
  },
  "🤸🏾♂": {
    name: "man-cartwheeling-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f938-1f3fe-2642",
    htmlEntity: "&#x1F938;&#x1F3FE;&#x2642",
  },
  "🤸🏿♂": {
    name: "man-cartwheeling-dark-skin-tone",
    category: "diversity",
    unicode: "_1f938-1f3ff-2642",
    htmlEntity: "&#x1F938;&#x1F3FF;&#x2642",
  },
  "⛹": {
    name: "person-bouncing-ball",
    category: "activity",
    unicode: "_26f9",
    htmlEntity: "&#x26F9",
  },
  "⛹🏻": {
    name: "person-bouncing-ball-light-skin-tone",
    category: "diversity",
    unicode: "_26f9-1f3fb",
    htmlEntity: "&#x26F9;&#x1F3FB",
  },
  "⛹🏼": {
    name: "person-bouncing-ball-medium-light-skin-tone",
    category: "diversity",
    unicode: "_26f9-1f3fc",
    htmlEntity: "&#x26F9;&#x1F3FC",
  },
  "⛹🏽": {
    name: "person-bouncing-ball-medium-skin-tone",
    category: "diversity",
    unicode: "_26f9-1f3fd",
    htmlEntity: "&#x26F9;&#x1F3FD",
  },
  "⛹🏾": {
    name: "person-bouncing-ball-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_26f9-1f3fe",
    htmlEntity: "&#x26F9;&#x1F3FE",
  },
  "⛹🏿": {
    name: "person-bouncing-ball-dark-skin-tone",
    category: "diversity",
    unicode: "_26f9-1f3ff",
    htmlEntity: "&#x26F9;&#x1F3FF",
  },
  "⛹♀": {
    name: "woman-bouncing-ball",
    category: "activity",
    unicode: "_26f9-2640",
    htmlEntity: "&#x26F9;&#x2640",
  },
  "⛹🏻♀": {
    name: "woman-bouncing-ball-light-skin-tone",
    category: "diversity",
    unicode: "_26f9-1f3fb-2640",
    htmlEntity: "&#x26F9;&#x1F3FB;&#x2640",
  },
  "⛹🏼♀": {
    name: "woman-bouncing-ball-medium-light-skin-tone",
    category: "diversity",
    unicode: "_26f9-1f3fc-2640",
    htmlEntity: "&#x26F9;&#x1F3FC;&#x2640",
  },
  "⛹🏽♀": {
    name: "woman-bouncing-ball-medium-skin-tone",
    category: "diversity",
    unicode: "_26f9-1f3fd-2640",
    htmlEntity: "&#x26F9;&#x1F3FD;&#x2640",
  },
  "⛹🏾♀": {
    name: "woman-bouncing-ball-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_26f9-1f3fe-2640",
    htmlEntity: "&#x26F9;&#x1F3FE;&#x2640",
  },
  "⛹🏿♀": {
    name: "woman-bouncing-ball-dark-skin-tone",
    category: "diversity",
    unicode: "_26f9-1f3ff-2640",
    htmlEntity: "&#x26F9;&#x1F3FF;&#x2640",
  },
  "⛹♂": {
    name: "man-bouncing-ball",
    category: "activity",
    unicode: "_26f9-2642",
    htmlEntity: "&#x26F9;&#x2642",
  },
  "⛹🏻♂": {
    name: "man-bouncing-ball-light-skin-tone",
    category: "diversity",
    unicode: "_26f9-1f3fb-2642",
    htmlEntity: "&#x26F9;&#x1F3FB;&#x2642",
  },
  "⛹🏼♂": {
    name: "man-bouncing-ball-medium-light-skin-tone",
    category: "diversity",
    unicode: "_26f9-1f3fc-2642",
    htmlEntity: "&#x26F9;&#x1F3FC;&#x2642",
  },
  "⛹🏽♂": {
    name: "man-bouncing-ball-medium-skin-tone",
    category: "diversity",
    unicode: "_26f9-1f3fd-2642",
    htmlEntity: "&#x26F9;&#x1F3FD;&#x2642",
  },
  "⛹🏾♂": {
    name: "man-bouncing-ball-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_26f9-1f3fe-2642",
    htmlEntity: "&#x26F9;&#x1F3FE;&#x2642",
  },
  "⛹🏿♂": {
    name: "man-bouncing-ball-dark-skin-tone",
    category: "diversity",
    unicode: "_26f9-1f3ff-2642",
    htmlEntity: "&#x26F9;&#x1F3FF;&#x2642",
  },
  "🤺": {
    name: "person-fencing",
    category: "activity",
    unicode: "_1f93a",
    htmlEntity: "&#x1F93A",
  },
  "🤾": {
    name: "person-playing-handball",
    category: "activity",
    unicode: "_1f93e",
    htmlEntity: "&#x1F93E",
  },
  "🤾🏻": {
    name: "person-playing-handball-light-skin-tone",
    category: "diversity",
    unicode: "_1f93e-1f3fb",
    htmlEntity: "&#x1F93E;&#x1F3FB",
  },
  "🤾🏼": {
    name: "person-playing-handball-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f93e-1f3fc",
    htmlEntity: "&#x1F93E;&#x1F3FC",
  },
  "🤾🏽": {
    name: "person-playing-handball-medium-skin-tone",
    category: "diversity",
    unicode: "_1f93e-1f3fd",
    htmlEntity: "&#x1F93E;&#x1F3FD",
  },
  "🤾🏾": {
    name: "person-playing-handball-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f93e-1f3fe",
    htmlEntity: "&#x1F93E;&#x1F3FE",
  },
  "🤾🏿": {
    name: "person-playing-handball-dark-skin-tone",
    category: "diversity",
    unicode: "_1f93e-1f3ff",
    htmlEntity: "&#x1F93E;&#x1F3FF",
  },
  "🤾♀": {
    name: "woman-playing-handball",
    category: "activity",
    unicode: "_1f93e-2640",
    htmlEntity: "&#x1F93E;&#x2640",
  },
  "🤾🏻♀": {
    name: "woman-playing-handball-light-skin-tone",
    category: "diversity",
    unicode: "_1f93e-1f3fb-2640",
    htmlEntity: "&#x1F93E;&#x1F3FB;&#x2640",
  },
  "🤾🏼♀": {
    name: "woman-playing-handball-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f93e-1f3fc-2640",
    htmlEntity: "&#x1F93E;&#x1F3FC;&#x2640",
  },
  "🤾🏽♀": {
    name: "woman-playing-handball-medium-skin-tone",
    category: "diversity",
    unicode: "_1f93e-1f3fd-2640",
    htmlEntity: "&#x1F93E;&#x1F3FD;&#x2640",
  },
  "🤾🏾♀": {
    name: "woman-playing-handball-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f93e-1f3fe-2640",
    htmlEntity: "&#x1F93E;&#x1F3FE;&#x2640",
  },
  "🤾🏿♀": {
    name: "woman-playing-handball-dark-skin-tone",
    category: "diversity",
    unicode: "_1f93e-1f3ff-2640",
    htmlEntity: "&#x1F93E;&#x1F3FF;&#x2640",
  },
  "🤾♂": {
    name: "man-playing-handball",
    category: "activity",
    unicode: "_1f93e-2642",
    htmlEntity: "&#x1F93E;&#x2642",
  },
  "🤾🏻♂": {
    name: "man-playing-handball-light-skin-tone",
    category: "diversity",
    unicode: "_1f93e-1f3fb-2642",
    htmlEntity: "&#x1F93E;&#x1F3FB;&#x2642",
  },
  "🤾🏼♂": {
    name: "man-playing-handball-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f93e-1f3fc-2642",
    htmlEntity: "&#x1F93E;&#x1F3FC;&#x2642",
  },
  "🤾🏽♂": {
    name: "man-playing-handball-medium-skin-tone",
    category: "diversity",
    unicode: "_1f93e-1f3fd-2642",
    htmlEntity: "&#x1F93E;&#x1F3FD;&#x2642",
  },
  "🤾🏾♂": {
    name: "man-playing-handball-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f93e-1f3fe-2642",
    htmlEntity: "&#x1F93E;&#x1F3FE;&#x2642",
  },
  "🤾🏿♂": {
    name: "man-playing-handball-dark-skin-tone",
    category: "diversity",
    unicode: "_1f93e-1f3ff-2642",
    htmlEntity: "&#x1F93E;&#x1F3FF;&#x2642",
  },
  "🏌": {
    name: "person-golfing",
    category: "activity",
    unicode: "_1f3cc",
    htmlEntity: "&#x1F3CC",
  },
  "🏌🏻": {
    name: "person-golfing-light-skin-tone",
    category: "diversity",
    unicode: "_1f3cc-1f3fb",
    htmlEntity: "&#x1F3CC;&#x1F3FB",
  },
  "🏌🏼": {
    name: "person-golfing-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f3cc-1f3fc",
    htmlEntity: "&#x1F3CC;&#x1F3FC",
  },
  "🏌🏽": {
    name: "person-golfing-medium-skin-tone",
    category: "diversity",
    unicode: "_1f3cc-1f3fd",
    htmlEntity: "&#x1F3CC;&#x1F3FD",
  },
  "🏌🏾": {
    name: "person-golfing-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f3cc-1f3fe",
    htmlEntity: "&#x1F3CC;&#x1F3FE",
  },
  "🏌🏿": {
    name: "person-golfing-dark-skin-tone",
    category: "diversity",
    unicode: "_1f3cc-1f3ff",
    htmlEntity: "&#x1F3CC;&#x1F3FF",
  },
  "🏌♀": {
    name: "woman-golfing",
    category: "activity",
    unicode: "_1f3cc-2640",
    htmlEntity: "&#x1F3CC;&#x2640",
  },
  "🏌🏻♀": {
    name: "woman-golfing-light-skin-tone",
    category: "diversity",
    unicode: "_1f3cc-1f3fb-2640",
    htmlEntity: "&#x1F3CC;&#x1F3FB;&#x2640",
  },
  "🏌🏼♀": {
    name: "woman-golfing-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f3cc-1f3fc-2640",
    htmlEntity: "&#x1F3CC;&#x1F3FC;&#x2640",
  },
  "🏌🏽♀": {
    name: "woman-golfing-medium-skin-tone",
    category: "diversity",
    unicode: "_1f3cc-1f3fd-2640",
    htmlEntity: "&#x1F3CC;&#x1F3FD;&#x2640",
  },
  "🏌🏾♀": {
    name: "woman-golfing-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f3cc-1f3fe-2640",
    htmlEntity: "&#x1F3CC;&#x1F3FE;&#x2640",
  },
  "🏌🏿♀": {
    name: "woman-golfing-dark-skin-tone",
    category: "diversity",
    unicode: "_1f3cc-1f3ff-2640",
    htmlEntity: "&#x1F3CC;&#x1F3FF;&#x2640",
  },
  "🏌♂": {
    name: "man-golfing",
    category: "activity",
    unicode: "_1f3cc-2642",
    htmlEntity: "&#x1F3CC;&#x2642",
  },
  "🏌🏻♂": {
    name: "man-golfing-light-skin-tone",
    category: "diversity",
    unicode: "_1f3cc-1f3fb-2642",
    htmlEntity: "&#x1F3CC;&#x1F3FB;&#x2642",
  },
  "🏌🏼♂": {
    name: "man-golfing-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f3cc-1f3fc-2642",
    htmlEntity: "&#x1F3CC;&#x1F3FC;&#x2642",
  },
  "🏌🏽♂": {
    name: "man-golfing-medium-skin-tone",
    category: "diversity",
    unicode: "_1f3cc-1f3fd-2642",
    htmlEntity: "&#x1F3CC;&#x1F3FD;&#x2642",
  },
  "🏌🏾♂": {
    name: "man-golfing-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f3cc-1f3fe-2642",
    htmlEntity: "&#x1F3CC;&#x1F3FE;&#x2642",
  },
  "🏌🏿♂": {
    name: "man-golfing-dark-skin-tone",
    category: "diversity",
    unicode: "_1f3cc-1f3ff-2642",
    htmlEntity: "&#x1F3CC;&#x1F3FF;&#x2642",
  },
  "🏇": {
    name: "horse-racing",
    category: "activity",
    unicode: "_1f3c7",
    htmlEntity: "&#x1F3C7",
  },
  "🏇🏻": {
    name: "horse-racing-light-skin-tone",
    category: "diversity",
    unicode: "_1f3c7-1f3fb",
    htmlEntity: "&#x1F3C7;&#x1F3FB",
  },
  "🏇🏼": {
    name: "horse-racing-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f3c7-1f3fc",
    htmlEntity: "&#x1F3C7;&#x1F3FC",
  },
  "🏇🏽": {
    name: "horse-racing-medium-skin-tone",
    category: "diversity",
    unicode: "_1f3c7-1f3fd",
    htmlEntity: "&#x1F3C7;&#x1F3FD",
  },
  "🏇🏾": {
    name: "horse-racing-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f3c7-1f3fe",
    htmlEntity: "&#x1F3C7;&#x1F3FE",
  },
  "🏇🏿": {
    name: "horse-racing-dark-skin-tone",
    category: "diversity",
    unicode: "_1f3c7-1f3ff",
    htmlEntity: "&#x1F3C7;&#x1F3FF",
  },
  "🧘": {
    name: "person-in-lotus-position",
    category: "activity",
    unicode: "_1f9d8",
    htmlEntity: "&#x1F9D8",
  },
  "🧘🏻": {
    name: "person-in-lotus-position-light-skin-tone",
    category: "diversity",
    unicode: "_1f9d8-1f3fb",
    htmlEntity: "&#x1F9D8;&#x1F3FB",
  },
  "🧘🏼": {
    name: "person-in-lotus-position-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f9d8-1f3fc",
    htmlEntity: "&#x1F9D8;&#x1F3FC",
  },
  "🧘🏽": {
    name: "person-in-lotus-position-medium-skin-tone",
    category: "diversity",
    unicode: "_1f9d8-1f3fd",
    htmlEntity: "&#x1F9D8;&#x1F3FD",
  },
  "🧘🏾": {
    name: "person-in-lotus-position-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f9d8-1f3fe",
    htmlEntity: "&#x1F9D8;&#x1F3FE",
  },
  "🧘🏿": {
    name: "person-in-lotus-position-dark-skin-tone",
    category: "diversity",
    unicode: "_1f9d8-1f3ff",
    htmlEntity: "&#x1F9D8;&#x1F3FF",
  },
  "🧘♀": {
    name: "woman-in-lotus-position",
    category: "activity",
    unicode: "_1f9d8-2640",
    htmlEntity: "&#x1F9D8;&#x2640",
  },
  "🧘🏻♀": {
    name: "woman-in-lotus-position-light-skin-tone",
    category: "diversity",
    unicode: "_1f9d8-1f3fb-2640",
    htmlEntity: "&#x1F9D8;&#x1F3FB;&#x2640",
  },
  "🧘🏼♀": {
    name: "woman-in-lotus-position-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f9d8-1f3fc-2640",
    htmlEntity: "&#x1F9D8;&#x1F3FC;&#x2640",
  },
  "🧘🏽♀": {
    name: "woman-in-lotus-position-medium-skin-tone",
    category: "diversity",
    unicode: "_1f9d8-1f3fd-2640",
    htmlEntity: "&#x1F9D8;&#x1F3FD;&#x2640",
  },
  "🧘🏾♀": {
    name: "woman-in-lotus-position-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f9d8-1f3fe-2640",
    htmlEntity: "&#x1F9D8;&#x1F3FE;&#x2640",
  },
  "🧘🏿♀": {
    name: "woman-in-lotus-position-dark-skin-tone",
    category: "diversity",
    unicode: "_1f9d8-1f3ff-2640",
    htmlEntity: "&#x1F9D8;&#x1F3FF;&#x2640",
  },
  "🧘♂": {
    name: "man-in-lotus-position",
    category: "activity",
    unicode: "_1f9d8-2642",
    htmlEntity: "&#x1F9D8;&#x2642",
  },
  "🧘🏻♂": {
    name: "man-in-lotus-position-light-skin-tone",
    category: "diversity",
    unicode: "_1f9d8-1f3fb-2642",
    htmlEntity: "&#x1F9D8;&#x1F3FB;&#x2642",
  },
  "🧘🏼♂": {
    name: "man-in-lotus-position-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f9d8-1f3fc-2642",
    htmlEntity: "&#x1F9D8;&#x1F3FC;&#x2642",
  },
  "🧘🏽♂": {
    name: "man-in-lotus-position-medium-skin-tone",
    category: "diversity",
    unicode: "_1f9d8-1f3fd-2642",
    htmlEntity: "&#x1F9D8;&#x1F3FD;&#x2642",
  },
  "🧘🏾♂": {
    name: "man-in-lotus-position-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f9d8-1f3fe-2642",
    htmlEntity: "&#x1F9D8;&#x1F3FE;&#x2642",
  },
  "🧘🏿♂": {
    name: "man-in-lotus-position-dark-skin-tone",
    category: "diversity",
    unicode: "_1f9d8-1f3ff-2642",
    htmlEntity: "&#x1F9D8;&#x1F3FF;&#x2642",
  },
  "🏄": {
    name: "person-surfing",
    category: "activity",
    unicode: "_1f3c4",
    htmlEntity: "&#x1F3C4",
  },
  "🏄🏻": {
    name: "person-surfing-light-skin-tone",
    category: "diversity",
    unicode: "_1f3c4-1f3fb",
    htmlEntity: "&#x1F3C4;&#x1F3FB",
  },
  "🏄🏼": {
    name: "person-surfing-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f3c4-1f3fc",
    htmlEntity: "&#x1F3C4;&#x1F3FC",
  },
  "🏄🏽": {
    name: "person-surfing-medium-skin-tone",
    category: "diversity",
    unicode: "_1f3c4-1f3fd",
    htmlEntity: "&#x1F3C4;&#x1F3FD",
  },
  "🏄🏾": {
    name: "person-surfing-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f3c4-1f3fe",
    htmlEntity: "&#x1F3C4;&#x1F3FE",
  },
  "🏄🏿": {
    name: "person-surfing-dark-skin-tone",
    category: "diversity",
    unicode: "_1f3c4-1f3ff",
    htmlEntity: "&#x1F3C4;&#x1F3FF",
  },
  "🏄♀": {
    name: "woman-surfing",
    category: "activity",
    unicode: "_1f3c4-2640",
    htmlEntity: "&#x1F3C4;&#x2640",
  },
  "🏄🏻♀": {
    name: "woman-surfing-light-skin-tone",
    category: "diversity",
    unicode: "_1f3c4-1f3fb-2640",
    htmlEntity: "&#x1F3C4;&#x1F3FB;&#x2640",
  },
  "🏄🏼♀": {
    name: "woman-surfing-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f3c4-1f3fc-2640",
    htmlEntity: "&#x1F3C4;&#x1F3FC;&#x2640",
  },
  "🏄🏽♀": {
    name: "woman-surfing-medium-skin-tone",
    category: "diversity",
    unicode: "_1f3c4-1f3fd-2640",
    htmlEntity: "&#x1F3C4;&#x1F3FD;&#x2640",
  },
  "🏄🏾♀": {
    name: "woman-surfing-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f3c4-1f3fe-2640",
    htmlEntity: "&#x1F3C4;&#x1F3FE;&#x2640",
  },
  "🏄🏿♀": {
    name: "woman-surfing-dark-skin-tone",
    category: "diversity",
    unicode: "_1f3c4-1f3ff-2640",
    htmlEntity: "&#x1F3C4;&#x1F3FF;&#x2640",
  },
  "🏄♂": {
    name: "man-surfing",
    category: "activity",
    unicode: "_1f3c4-2642",
    htmlEntity: "&#x1F3C4;&#x2642",
  },
  "🏄🏻♂": {
    name: "man-surfing-light-skin-tone",
    category: "diversity",
    unicode: "_1f3c4-1f3fb-2642",
    htmlEntity: "&#x1F3C4;&#x1F3FB;&#x2642",
  },
  "🏄🏼♂": {
    name: "man-surfing-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f3c4-1f3fc-2642",
    htmlEntity: "&#x1F3C4;&#x1F3FC;&#x2642",
  },
  "🏄🏽♂": {
    name: "man-surfing-medium-skin-tone",
    category: "diversity",
    unicode: "_1f3c4-1f3fd-2642",
    htmlEntity: "&#x1F3C4;&#x1F3FD;&#x2642",
  },
  "🏄🏾♂": {
    name: "man-surfing-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f3c4-1f3fe-2642",
    htmlEntity: "&#x1F3C4;&#x1F3FE;&#x2642",
  },
  "🏄🏿♂": {
    name: "man-surfing-dark-skin-tone",
    category: "diversity",
    unicode: "_1f3c4-1f3ff-2642",
    htmlEntity: "&#x1F3C4;&#x1F3FF;&#x2642",
  },
  "🏊": {
    name: "person-swimming",
    category: "activity",
    unicode: "_1f3ca",
    htmlEntity: "&#x1F3CA",
  },
  "🏊🏻": {
    name: "person-swimming-light-skin-tone",
    category: "diversity",
    unicode: "_1f3ca-1f3fb",
    htmlEntity: "&#x1F3CA;&#x1F3FB",
  },
  "🏊🏼": {
    name: "person-swimming-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f3ca-1f3fc",
    htmlEntity: "&#x1F3CA;&#x1F3FC",
  },
  "🏊🏽": {
    name: "person-swimming-medium-skin-tone",
    category: "diversity",
    unicode: "_1f3ca-1f3fd",
    htmlEntity: "&#x1F3CA;&#x1F3FD",
  },
  "🏊🏾": {
    name: "person-swimming-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f3ca-1f3fe",
    htmlEntity: "&#x1F3CA;&#x1F3FE",
  },
  "🏊🏿": {
    name: "person-swimming-dark-skin-tone",
    category: "diversity",
    unicode: "_1f3ca-1f3ff",
    htmlEntity: "&#x1F3CA;&#x1F3FF",
  },
  "🏊♀": {
    name: "woman-swimming",
    category: "activity",
    unicode: "_1f3ca-2640",
    htmlEntity: "&#x1F3CA;&#x2640",
  },
  "🏊🏻♀": {
    name: "woman-swimming-light-skin-tone",
    category: "diversity",
    unicode: "_1f3ca-1f3fb-2640",
    htmlEntity: "&#x1F3CA;&#x1F3FB;&#x2640",
  },
  "🏊🏼♀": {
    name: "woman-swimming-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f3ca-1f3fc-2640",
    htmlEntity: "&#x1F3CA;&#x1F3FC;&#x2640",
  },
  "🏊🏽♀": {
    name: "woman-swimming-medium-skin-tone",
    category: "diversity",
    unicode: "_1f3ca-1f3fd-2640",
    htmlEntity: "&#x1F3CA;&#x1F3FD;&#x2640",
  },
  "🏊🏾♀": {
    name: "woman-swimming-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f3ca-1f3fe-2640",
    htmlEntity: "&#x1F3CA;&#x1F3FE;&#x2640",
  },
  "🏊🏿♀": {
    name: "woman-swimming-dark-skin-tone",
    category: "diversity",
    unicode: "_1f3ca-1f3ff-2640",
    htmlEntity: "&#x1F3CA;&#x1F3FF;&#x2640",
  },
  "🏊♂": {
    name: "man-swimming",
    category: "activity",
    unicode: "_1f3ca-2642",
    htmlEntity: "&#x1F3CA;&#x2642",
  },
  "🏊🏻♂": {
    name: "man-swimming-light-skin-tone",
    category: "diversity",
    unicode: "_1f3ca-1f3fb-2642",
    htmlEntity: "&#x1F3CA;&#x1F3FB;&#x2642",
  },
  "🏊🏼♂": {
    name: "man-swimming-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f3ca-1f3fc-2642",
    htmlEntity: "&#x1F3CA;&#x1F3FC;&#x2642",
  },
  "🏊🏽♂": {
    name: "man-swimming-medium-skin-tone",
    category: "diversity",
    unicode: "_1f3ca-1f3fd-2642",
    htmlEntity: "&#x1F3CA;&#x1F3FD;&#x2642",
  },
  "🏊🏾♂": {
    name: "man-swimming-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f3ca-1f3fe-2642",
    htmlEntity: "&#x1F3CA;&#x1F3FE;&#x2642",
  },
  "🏊🏿♂": {
    name: "man-swimming-dark-skin-tone",
    category: "diversity",
    unicode: "_1f3ca-1f3ff-2642",
    htmlEntity: "&#x1F3CA;&#x1F3FF;&#x2642",
  },
  "🤽": {
    name: "person-playing-water-polo",
    category: "activity",
    unicode: "_1f93d",
    htmlEntity: "&#x1F93D",
  },
  "🤽🏻": {
    name: "person-playing-water-polo-light-skin-tone",
    category: "diversity",
    unicode: "_1f93d-1f3fb",
    htmlEntity: "&#x1F93D;&#x1F3FB",
  },
  "🤽🏼": {
    name: "person-playing-water-polo-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f93d-1f3fc",
    htmlEntity: "&#x1F93D;&#x1F3FC",
  },
  "🤽🏽": {
    name: "person-playing-water-polo-medium-skin-tone",
    category: "diversity",
    unicode: "_1f93d-1f3fd",
    htmlEntity: "&#x1F93D;&#x1F3FD",
  },
  "🤽🏾": {
    name: "person-playing-water-polo-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f93d-1f3fe",
    htmlEntity: "&#x1F93D;&#x1F3FE",
  },
  "🤽🏿": {
    name: "person-playing-water-polo-dark-skin-tone",
    category: "diversity",
    unicode: "_1f93d-1f3ff",
    htmlEntity: "&#x1F93D;&#x1F3FF",
  },
  "🤽♀": {
    name: "woman-playing-water-polo",
    category: "activity",
    unicode: "_1f93d-2640",
    htmlEntity: "&#x1F93D;&#x2640",
  },
  "🤽🏻♀": {
    name: "woman-playing-water-polo-light-skin-tone",
    category: "diversity",
    unicode: "_1f93d-1f3fb-2640",
    htmlEntity: "&#x1F93D;&#x1F3FB;&#x2640",
  },
  "🤽🏼♀": {
    name: "woman-playing-water-polo-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f93d-1f3fc-2640",
    htmlEntity: "&#x1F93D;&#x1F3FC;&#x2640",
  },
  "🤽🏽♀": {
    name: "woman-playing-water-polo-medium-skin-tone",
    category: "diversity",
    unicode: "_1f93d-1f3fd-2640",
    htmlEntity: "&#x1F93D;&#x1F3FD;&#x2640",
  },
  "🤽🏾♀": {
    name: "woman-playing-water-polo-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f93d-1f3fe-2640",
    htmlEntity: "&#x1F93D;&#x1F3FE;&#x2640",
  },
  "🤽🏿♀": {
    name: "woman-playing-water-polo-dark-skin-tone",
    category: "diversity",
    unicode: "_1f93d-1f3ff-2640",
    htmlEntity: "&#x1F93D;&#x1F3FF;&#x2640",
  },
  "🤽♂": {
    name: "man-playing-water-polo",
    category: "activity",
    unicode: "_1f93d-2642",
    htmlEntity: "&#x1F93D;&#x2642",
  },
  "🤽🏻♂": {
    name: "man-playing-water-polo-light-skin-tone",
    category: "diversity",
    unicode: "_1f93d-1f3fb-2642",
    htmlEntity: "&#x1F93D;&#x1F3FB;&#x2642",
  },
  "🤽🏼♂": {
    name: "man-playing-water-polo-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f93d-1f3fc-2642",
    htmlEntity: "&#x1F93D;&#x1F3FC;&#x2642",
  },
  "🤽🏽♂": {
    name: "man-playing-water-polo-medium-skin-tone",
    category: "diversity",
    unicode: "_1f93d-1f3fd-2642",
    htmlEntity: "&#x1F93D;&#x1F3FD;&#x2642",
  },
  "🤽🏾♂": {
    name: "man-playing-water-polo-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f93d-1f3fe-2642",
    htmlEntity: "&#x1F93D;&#x1F3FE;&#x2642",
  },
  "🤽🏿♂": {
    name: "man-playing-water-polo-dark-skin-tone",
    category: "diversity",
    unicode: "_1f93d-1f3ff-2642",
    htmlEntity: "&#x1F93D;&#x1F3FF;&#x2642",
  },
  "🚣": {
    name: "person-rowing-boat",
    category: "activity",
    unicode: "_1f6a3",
    htmlEntity: "&#x1F6A3",
  },
  "🚣🏻": {
    name: "person-rowing-boat-light-skin-tone",
    category: "diversity",
    unicode: "_1f6a3-1f3fb",
    htmlEntity: "&#x1F6A3;&#x1F3FB",
  },
  "🚣🏼": {
    name: "person-rowing-boat-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f6a3-1f3fc",
    htmlEntity: "&#x1F6A3;&#x1F3FC",
  },
  "🚣🏽": {
    name: "person-rowing-boat-medium-skin-tone",
    category: "diversity",
    unicode: "_1f6a3-1f3fd",
    htmlEntity: "&#x1F6A3;&#x1F3FD",
  },
  "🚣🏾": {
    name: "person-rowing-boat-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f6a3-1f3fe",
    htmlEntity: "&#x1F6A3;&#x1F3FE",
  },
  "🚣🏿": {
    name: "person-rowing-boat-dark-skin-tone",
    category: "diversity",
    unicode: "_1f6a3-1f3ff",
    htmlEntity: "&#x1F6A3;&#x1F3FF",
  },
  "🚣♀": {
    name: "woman-rowing-boat",
    category: "activity",
    unicode: "_1f6a3-2640",
    htmlEntity: "&#x1F6A3;&#x2640",
  },
  "🚣🏻♀": {
    name: "woman-rowing-boat-light-skin-tone",
    category: "diversity",
    unicode: "_1f6a3-1f3fb-2640",
    htmlEntity: "&#x1F6A3;&#x1F3FB;&#x2640",
  },
  "🚣🏼♀": {
    name: "woman-rowing-boat-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f6a3-1f3fc-2640",
    htmlEntity: "&#x1F6A3;&#x1F3FC;&#x2640",
  },
  "🚣🏽♀": {
    name: "woman-rowing-boat-medium-skin-tone",
    category: "diversity",
    unicode: "_1f6a3-1f3fd-2640",
    htmlEntity: "&#x1F6A3;&#x1F3FD;&#x2640",
  },
  "🚣🏾♀": {
    name: "woman-rowing-boat-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f6a3-1f3fe-2640",
    htmlEntity: "&#x1F6A3;&#x1F3FE;&#x2640",
  },
  "🚣🏿♀": {
    name: "woman-rowing-boat-dark-skin-tone",
    category: "diversity",
    unicode: "_1f6a3-1f3ff-2640",
    htmlEntity: "&#x1F6A3;&#x1F3FF;&#x2640",
  },
  "🚣♂": {
    name: "man-rowing-boat",
    category: "activity",
    unicode: "_1f6a3-2642",
    htmlEntity: "&#x1F6A3;&#x2642",
  },
  "🚣🏻♂": {
    name: "man-rowing-boat-light-skin-tone",
    category: "diversity",
    unicode: "_1f6a3-1f3fb-2642",
    htmlEntity: "&#x1F6A3;&#x1F3FB;&#x2642",
  },
  "🚣🏼♂": {
    name: "man-rowing-boat-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f6a3-1f3fc-2642",
    htmlEntity: "&#x1F6A3;&#x1F3FC;&#x2642",
  },
  "🚣🏽♂": {
    name: "man-rowing-boat-medium-skin-tone",
    category: "diversity",
    unicode: "_1f6a3-1f3fd-2642",
    htmlEntity: "&#x1F6A3;&#x1F3FD;&#x2642",
  },
  "🚣🏾♂": {
    name: "man-rowing-boat-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f6a3-1f3fe-2642",
    htmlEntity: "&#x1F6A3;&#x1F3FE;&#x2642",
  },
  "🚣🏿♂": {
    name: "man-rowing-boat-dark-skin-tone",
    category: "diversity",
    unicode: "_1f6a3-1f3ff-2642",
    htmlEntity: "&#x1F6A3;&#x1F3FF;&#x2642",
  },
  "🧗": {
    name: "person-climbing",
    category: "activity",
    unicode: "_1f9d7",
    htmlEntity: "&#x1F9D7",
  },
  "🧗🏻": {
    name: "person-climbing-light-skin-tone",
    category: "diversity",
    unicode: "_1f9d7-1f3fb",
    htmlEntity: "&#x1F9D7;&#x1F3FB",
  },
  "🧗🏼": {
    name: "person-climbing-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f9d7-1f3fc",
    htmlEntity: "&#x1F9D7;&#x1F3FC",
  },
  "🧗🏽": {
    name: "person-climbing-medium-skin-tone",
    category: "diversity",
    unicode: "_1f9d7-1f3fd",
    htmlEntity: "&#x1F9D7;&#x1F3FD",
  },
  "🧗🏾": {
    name: "person-climbing-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f9d7-1f3fe",
    htmlEntity: "&#x1F9D7;&#x1F3FE",
  },
  "🧗🏿": {
    name: "person-climbing-dark-skin-tone",
    category: "diversity",
    unicode: "_1f9d7-1f3ff",
    htmlEntity: "&#x1F9D7;&#x1F3FF",
  },
  "🧗♀": {
    name: "woman-climbing",
    category: "activity",
    unicode: "_1f9d7-2640",
    htmlEntity: "&#x1F9D7;&#x2640",
  },
  "🧗🏻♀": {
    name: "woman-climbing-light-skin-tone",
    category: "diversity",
    unicode: "_1f9d7-1f3fb-2640",
    htmlEntity: "&#x1F9D7;&#x1F3FB;&#x2640",
  },
  "🧗🏼♀": {
    name: "woman-climbing-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f9d7-1f3fc-2640",
    htmlEntity: "&#x1F9D7;&#x1F3FC;&#x2640",
  },
  "🧗🏽♀": {
    name: "woman-climbing-medium-skin-tone",
    category: "diversity",
    unicode: "_1f9d7-1f3fd-2640",
    htmlEntity: "&#x1F9D7;&#x1F3FD;&#x2640",
  },
  "🧗🏾♀": {
    name: "woman-climbing-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f9d7-1f3fe-2640",
    htmlEntity: "&#x1F9D7;&#x1F3FE;&#x2640",
  },
  "🧗🏿♀": {
    name: "woman-climbing-dark-skin-tone",
    category: "diversity",
    unicode: "_1f9d7-1f3ff-2640",
    htmlEntity: "&#x1F9D7;&#x1F3FF;&#x2640",
  },
  "🧗♂": {
    name: "man-climbing",
    category: "activity",
    unicode: "_1f9d7-2642",
    htmlEntity: "&#x1F9D7;&#x2642",
  },
  "🧗🏻♂": {
    name: "man-climbing-light-skin-tone",
    category: "diversity",
    unicode: "_1f9d7-1f3fb-2642",
    htmlEntity: "&#x1F9D7;&#x1F3FB;&#x2642",
  },
  "🧗🏼♂": {
    name: "man-climbing-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f9d7-1f3fc-2642",
    htmlEntity: "&#x1F9D7;&#x1F3FC;&#x2642",
  },
  "🧗🏽♂": {
    name: "man-climbing-medium-skin-tone",
    category: "diversity",
    unicode: "_1f9d7-1f3fd-2642",
    htmlEntity: "&#x1F9D7;&#x1F3FD;&#x2642",
  },
  "🧗🏾♂": {
    name: "man-climbing-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f9d7-1f3fe-2642",
    htmlEntity: "&#x1F9D7;&#x1F3FE;&#x2642",
  },
  "🧗🏿♂": {
    name: "man-climbing-dark-skin-tone",
    category: "diversity",
    unicode: "_1f9d7-1f3ff-2642",
    htmlEntity: "&#x1F9D7;&#x1F3FF;&#x2642",
  },
  "🚵": {
    name: "person-mountain-biking",
    category: "activity",
    unicode: "_1f6b5",
    htmlEntity: "&#x1F6B5",
  },
  "🚵🏻": {
    name: "person-mountain-biking-light-skin-tone",
    category: "diversity",
    unicode: "_1f6b5-1f3fb",
    htmlEntity: "&#x1F6B5;&#x1F3FB",
  },
  "🚵🏼": {
    name: "person-mountain-biking-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f6b5-1f3fc",
    htmlEntity: "&#x1F6B5;&#x1F3FC",
  },
  "🚵🏽": {
    name: "person-mountain-biking-medium-skin-tone",
    category: "diversity",
    unicode: "_1f6b5-1f3fd",
    htmlEntity: "&#x1F6B5;&#x1F3FD",
  },
  "🚵🏾": {
    name: "person-mountain-biking-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f6b5-1f3fe",
    htmlEntity: "&#x1F6B5;&#x1F3FE",
  },
  "🚵🏿": {
    name: "person-mountain-biking-dark-skin-tone",
    category: "diversity",
    unicode: "_1f6b5-1f3ff",
    htmlEntity: "&#x1F6B5;&#x1F3FF",
  },
  "🚵♀": {
    name: "woman-mountain-biking",
    category: "activity",
    unicode: "_1f6b5-2640",
    htmlEntity: "&#x1F6B5;&#x2640",
  },
  "🚵🏻♀": {
    name: "woman-mountain-biking-light-skin-tone",
    category: "diversity",
    unicode: "_1f6b5-1f3fb-2640",
    htmlEntity: "&#x1F6B5;&#x1F3FB;&#x2640",
  },
  "🚵🏼♀": {
    name: "woman-mountain-biking-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f6b5-1f3fc-2640",
    htmlEntity: "&#x1F6B5;&#x1F3FC;&#x2640",
  },
  "🚵🏽♀": {
    name: "woman-mountain-biking-medium-skin-tone",
    category: "diversity",
    unicode: "_1f6b5-1f3fd-2640",
    htmlEntity: "&#x1F6B5;&#x1F3FD;&#x2640",
  },
  "🚵🏾♀": {
    name: "woman-mountain-biking-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f6b5-1f3fe-2640",
    htmlEntity: "&#x1F6B5;&#x1F3FE;&#x2640",
  },
  "🚵🏿♀": {
    name: "woman-mountain-biking-dark-skin-tone",
    category: "diversity",
    unicode: "_1f6b5-1f3ff-2640",
    htmlEntity: "&#x1F6B5;&#x1F3FF;&#x2640",
  },
  "🚵♂": {
    name: "man-mountain-biking",
    category: "activity",
    unicode: "_1f6b5-2642",
    htmlEntity: "&#x1F6B5;&#x2642",
  },
  "🚵🏻♂": {
    name: "man-mountain-biking-light-skin-tone",
    category: "diversity",
    unicode: "_1f6b5-1f3fb-2642",
    htmlEntity: "&#x1F6B5;&#x1F3FB;&#x2642",
  },
  "🚵🏼♂": {
    name: "man-mountain-biking-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f6b5-1f3fc-2642",
    htmlEntity: "&#x1F6B5;&#x1F3FC;&#x2642",
  },
  "🚵🏽♂": {
    name: "man-mountain-biking-medium-skin-tone",
    category: "diversity",
    unicode: "_1f6b5-1f3fd-2642",
    htmlEntity: "&#x1F6B5;&#x1F3FD;&#x2642",
  },
  "🚵🏾♂": {
    name: "man-mountain-biking-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f6b5-1f3fe-2642",
    htmlEntity: "&#x1F6B5;&#x1F3FE;&#x2642",
  },
  "🚵🏿♂": {
    name: "man-mountain-biking-dark-skin-tone",
    category: "diversity",
    unicode: "_1f6b5-1f3ff-2642",
    htmlEntity: "&#x1F6B5;&#x1F3FF;&#x2642",
  },
  "🚴": {
    name: "person-biking",
    category: "activity",
    unicode: "_1f6b4",
    htmlEntity: "&#x1F6B4",
  },
  "🚴🏻": {
    name: "person-biking-light-skin-tone",
    category: "diversity",
    unicode: "_1f6b4-1f3fb",
    htmlEntity: "&#x1F6B4;&#x1F3FB",
  },
  "🚴🏼": {
    name: "person-biking-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f6b4-1f3fc",
    htmlEntity: "&#x1F6B4;&#x1F3FC",
  },
  "🚴🏽": {
    name: "person-biking-medium-skin-tone",
    category: "diversity",
    unicode: "_1f6b4-1f3fd",
    htmlEntity: "&#x1F6B4;&#x1F3FD",
  },
  "🚴🏾": {
    name: "person-biking-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f6b4-1f3fe",
    htmlEntity: "&#x1F6B4;&#x1F3FE",
  },
  "🚴🏿": {
    name: "person-biking-dark-skin-tone",
    category: "diversity",
    unicode: "_1f6b4-1f3ff",
    htmlEntity: "&#x1F6B4;&#x1F3FF",
  },
  "🚴♀": {
    name: "woman-biking",
    category: "activity",
    unicode: "_1f6b4-2640",
    htmlEntity: "&#x1F6B4;&#x2640",
  },
  "🚴🏻♀": {
    name: "woman-biking-light-skin-tone",
    category: "diversity",
    unicode: "_1f6b4-1f3fb-2640",
    htmlEntity: "&#x1F6B4;&#x1F3FB;&#x2640",
  },
  "🚴🏼♀": {
    name: "woman-biking-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f6b4-1f3fc-2640",
    htmlEntity: "&#x1F6B4;&#x1F3FC;&#x2640",
  },
  "🚴🏽♀": {
    name: "woman-biking-medium-skin-tone",
    category: "diversity",
    unicode: "_1f6b4-1f3fd-2640",
    htmlEntity: "&#x1F6B4;&#x1F3FD;&#x2640",
  },
  "🚴🏾♀": {
    name: "woman-biking-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f6b4-1f3fe-2640",
    htmlEntity: "&#x1F6B4;&#x1F3FE;&#x2640",
  },
  "🚴🏿♀": {
    name: "woman-biking-dark-skin-tone",
    category: "diversity",
    unicode: "_1f6b4-1f3ff-2640",
    htmlEntity: "&#x1F6B4;&#x1F3FF;&#x2640",
  },
  "🚴♂": {
    name: "man-biking",
    category: "activity",
    unicode: "_1f6b4-2642",
    htmlEntity: "&#x1F6B4;&#x2642",
  },
  "🚴🏻♂": {
    name: "man-biking-light-skin-tone",
    category: "diversity",
    unicode: "_1f6b4-1f3fb-2642",
    htmlEntity: "&#x1F6B4;&#x1F3FB;&#x2642",
  },
  "🚴🏼♂": {
    name: "man-biking-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f6b4-1f3fc-2642",
    htmlEntity: "&#x1F6B4;&#x1F3FC;&#x2642",
  },
  "🚴🏽♂": {
    name: "man-biking-medium-skin-tone",
    category: "diversity",
    unicode: "_1f6b4-1f3fd-2642",
    htmlEntity: "&#x1F6B4;&#x1F3FD;&#x2642",
  },
  "🚴🏾♂": {
    name: "man-biking-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f6b4-1f3fe-2642",
    htmlEntity: "&#x1F6B4;&#x1F3FE;&#x2642",
  },
  "🚴🏿♂": {
    name: "man-biking-dark-skin-tone",
    category: "diversity",
    unicode: "_1f6b4-1f3ff-2642",
    htmlEntity: "&#x1F6B4;&#x1F3FF;&#x2642",
  },
  "🏆": {
    name: "trophy",
    category: "activity",
    unicode: "_1f3c6",
    htmlEntity: "&#x1F3C6",
  },
  "🥇": {
    name: "1st-place-medal",
    category: "activity",
    unicode: "_1f947",
    htmlEntity: "&#x1F947",
  },
  "🥈": {
    name: "2nd-place-medal",
    category: "activity",
    unicode: "_1f948",
    htmlEntity: "&#x1F948",
  },
  "🥉": {
    name: "3rd-place-medal",
    category: "activity",
    unicode: "_1f949",
    htmlEntity: "&#x1F949",
  },
  "🏅": {
    name: "sports-medal",
    category: "activity",
    unicode: "_1f3c5",
    htmlEntity: "&#x1F3C5",
  },
  "🎖": {
    name: "military-medal",
    category: "activity",
    unicode: "_1f396",
    htmlEntity: "&#x1F396",
  },
  "🏵": {
    name: "rosette",
    category: "activity",
    unicode: "_1f3f5",
    htmlEntity: "&#x1F3F5",
  },
  "🎗": {
    name: "reminder-ribbon",
    category: "activity",
    unicode: "_1f397",
    htmlEntity: "&#x1F397",
  },
  "🎫": {
    name: "ticket",
    category: "activity",
    unicode: "_1f3ab",
    htmlEntity: "&#x1F3AB",
  },
  "🎟": {
    name: "admission-tickets",
    category: "activity",
    unicode: "_1f39f",
    htmlEntity: "&#x1F39F",
  },
  "🎪": {
    name: "circus-tent",
    category: "activity",
    unicode: "_1f3aa",
    htmlEntity: "&#x1F3AA",
  },
  "🤹": {
    name: "person-juggling",
    category: "activity",
    unicode: "_1f939",
    htmlEntity: "&#x1F939",
  },
  "🤹🏻": {
    name: "person-juggling-light-skin-tone",
    category: "diversity",
    unicode: "_1f939-1f3fb",
    htmlEntity: "&#x1F939;&#x1F3FB",
  },
  "🤹🏼": {
    name: "person-juggling-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f939-1f3fc",
    htmlEntity: "&#x1F939;&#x1F3FC",
  },
  "🤹🏽": {
    name: "person-juggling-medium-skin-tone",
    category: "diversity",
    unicode: "_1f939-1f3fd",
    htmlEntity: "&#x1F939;&#x1F3FD",
  },
  "🤹🏾": {
    name: "person-juggling-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f939-1f3fe",
    htmlEntity: "&#x1F939;&#x1F3FE",
  },
  "🤹🏿": {
    name: "person-juggling-dark-skin-tone",
    category: "diversity",
    unicode: "_1f939-1f3ff",
    htmlEntity: "&#x1F939;&#x1F3FF",
  },
  "🤹♀": {
    name: "woman-juggling",
    category: "activity",
    unicode: "_1f939-2640",
    htmlEntity: "&#x1F939;&#x2640",
  },
  "🤹🏻♀": {
    name: "woman-juggling-light-skin-tone",
    category: "diversity",
    unicode: "_1f939-1f3fb-2640",
    htmlEntity: "&#x1F939;&#x1F3FB;&#x2640",
  },
  "🤹🏼♀": {
    name: "woman-juggling-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f939-1f3fc-2640",
    htmlEntity: "&#x1F939;&#x1F3FC;&#x2640",
  },
  "🤹🏽♀": {
    name: "woman-juggling-medium-skin-tone",
    category: "diversity",
    unicode: "_1f939-1f3fd-2640",
    htmlEntity: "&#x1F939;&#x1F3FD;&#x2640",
  },
  "🤹🏾♀": {
    name: "woman-juggling-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f939-1f3fe-2640",
    htmlEntity: "&#x1F939;&#x1F3FE;&#x2640",
  },
  "🤹🏿♀": {
    name: "woman-juggling-dark-skin-tone",
    category: "diversity",
    unicode: "_1f939-1f3ff-2640",
    htmlEntity: "&#x1F939;&#x1F3FF;&#x2640",
  },
  "🤹♂": {
    name: "man-juggling",
    category: "activity",
    unicode: "_1f939-2642",
    htmlEntity: "&#x1F939;&#x2642",
  },
  "🤹🏻♂": {
    name: "man-juggling-light-skin-tone",
    category: "diversity",
    unicode: "_1f939-1f3fb-2642",
    htmlEntity: "&#x1F939;&#x1F3FB;&#x2642",
  },
  "🤹🏼♂": {
    name: "man-juggling-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f939-1f3fc-2642",
    htmlEntity: "&#x1F939;&#x1F3FC;&#x2642",
  },
  "🤹🏽♂": {
    name: "man-juggling-medium-skin-tone",
    category: "diversity",
    unicode: "_1f939-1f3fd-2642",
    htmlEntity: "&#x1F939;&#x1F3FD;&#x2642",
  },
  "🤹🏾♂": {
    name: "man-juggling-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f939-1f3fe-2642",
    htmlEntity: "&#x1F939;&#x1F3FE;&#x2642",
  },
  "🤹🏿♂": {
    name: "man-juggling-dark-skin-tone",
    category: "diversity",
    unicode: "_1f939-1f3ff-2642",
    htmlEntity: "&#x1F939;&#x1F3FF;&#x2642",
  },
  "🎭": {
    name: "performing-arts",
    category: "activity",
    unicode: "_1f3ad",
    htmlEntity: "&#x1F3AD",
  },
  "🩰": {
    name: "ballet-shoes",
    category: "activity",
    unicode: "_1fa70",
    htmlEntity: "&#x1FA70",
  },
  "🎨": {
    name: "artist-palette",
    category: "activity",
    unicode: "_1f3a8",
    htmlEntity: "&#x1F3A8",
  },
  "🎬": {
    name: "clapper-board",
    category: "activity",
    unicode: "_1f3ac",
    htmlEntity: "&#x1F3AC",
  },
  "🎤": {
    name: "microphone",
    category: "activity",
    unicode: "_1f3a4",
    htmlEntity: "&#x1F3A4",
  },
  "🎧": {
    name: "headphone",
    category: "activity",
    unicode: "_1f3a7",
    htmlEntity: "&#x1F3A7",
  },
  "🎼": {
    name: "musical-score",
    category: "activity",
    unicode: "_1f3bc",
    htmlEntity: "&#x1F3BC",
  },
  "🎹": {
    name: "musical-keyboard",
    category: "activity",
    unicode: "_1f3b9",
    htmlEntity: "&#x1F3B9",
  },
  "🥁": {
    name: "drum",
    category: "activity",
    unicode: "_1f941",
    htmlEntity: "&#x1F941",
  },
  "🪘": {
    name: "long-drum",
    category: "activity",
    unicode: "_1fa98",
    htmlEntity: "&#x1FA98",
  },
  "🎷": {
    name: "saxophone",
    category: "activity",
    unicode: "_1f3b7",
    htmlEntity: "&#x1F3B7",
  },
  "🎺": {
    name: "trumpet",
    category: "activity",
    unicode: "_1f3ba",
    htmlEntity: "&#x1F3BA",
  },
  "🎸": {
    name: "guitar",
    category: "activity",
    unicode: "_1f3b8",
    htmlEntity: "&#x1F3B8",
  },
  "🪕": {
    name: "banjo",
    category: "activity",
    unicode: "_1fa95",
    htmlEntity: "&#x1FA95",
  },
  "🎻": {
    name: "violin",
    category: "activity",
    unicode: "_1f3bb",
    htmlEntity: "&#x1F3BB",
  },
  "🪗": {
    name: "accordion",
    category: "activity",
    unicode: "_1fa97",
    htmlEntity: "&#x1FA97",
  },
  "🎲": {
    name: "game-die",
    category: "activity",
    unicode: "_1f3b2",
    htmlEntity: "&#x1F3B2",
  },
  "♟": {
    name: "chess-pawn",
    category: "activity",
    unicode: "_265f",
    htmlEntity: "&#x265F",
  },
  "🎯": {
    name: "direct-hit",
    category: "activity",
    unicode: "_1f3af",
    htmlEntity: "&#x1F3AF",
  },
  "🎳": {
    name: "bowling",
    category: "activity",
    unicode: "_1f3b3",
    htmlEntity: "&#x1F3B3",
  },
  "🎮": {
    name: "video-game",
    category: "activity",
    unicode: "_1f3ae",
    htmlEntity: "&#x1F3AE",
  },
  "🎰": {
    name: "slot-machine",
    category: "activity",
    unicode: "_1f3b0",
    htmlEntity: "&#x1F3B0",
  },
  "🧩": {
    name: "puzzle-piece",
    category: "activity",
    unicode: "_1f9e9",
    htmlEntity: "&#x1F9E9",
  },
};
