import { EmojiInformation } from "../types/emojiInformation";

export const ANIMALS_AND_NATURE: EmojiInformation = {
  "🐶": {
    name: "dog-face",
    category: "nature",
    unicode: "_1f436",
    htmlEntity: "&#x1F436",
  },
  "🐱": {
    name: "cat-face",
    category: "nature",
    unicode: "_1f431",
    htmlEntity: "&#x1F431",
  },
  "🐭": {
    name: "mouse-face",
    category: "nature",
    unicode: "_1f42d",
    htmlEntity: "&#x1F42D",
  },
  "🐹": {
    name: "hamster",
    category: "nature",
    unicode: "_1f439",
    htmlEntity: "&#x1F439",
  },
  "🐰": {
    name: "rabbit-face",
    category: "nature",
    unicode: "_1f430",
    htmlEntity: "&#x1F430",
  },
  "🦊": {
    name: "fox",
    category: "nature",
    unicode: "_1f98a",
    htmlEntity: "&#x1F98A",
  },
  "🐻": {
    name: "bear",
    category: "nature",
    unicode: "_1f43b",
    htmlEntity: "&#x1F43B",
  },
  "🐼": {
    name: "panda",
    category: "nature",
    unicode: "_1f43c",
    htmlEntity: "&#x1F43C",
  },
  "🐻❄": {
    name: "polar-bear",
    category: "nature",
    unicode: "_1f43b-2744",
    htmlEntity: "&#x1F43B;&#x2744",
  },
  "🐨": {
    name: "koala",
    category: "nature",
    unicode: "_1f428",
    htmlEntity: "&#x1F428",
  },
  "🐯": {
    name: "tiger-face",
    category: "nature",
    unicode: "_1f42f",
    htmlEntity: "&#x1F42F",
  },
  "🦁": {
    name: "lion",
    category: "nature",
    unicode: "_1f981",
    htmlEntity: "&#x1F981",
  },
  "🐮": {
    name: "cow-face",
    category: "nature",
    unicode: "_1f42e",
    htmlEntity: "&#x1F42E",
  },
  "🐷": {
    name: "pig-face",
    category: "nature",
    unicode: "_1f437",
    htmlEntity: "&#x1F437",
  },
  "🐽": {
    name: "pig-nose",
    category: "nature",
    unicode: "_1f43d",
    htmlEntity: "&#x1F43D",
  },
  "🐸": {
    name: "frog",
    category: "nature",
    unicode: "_1f438",
    htmlEntity: "&#x1F438",
  },
  "🐵": {
    name: "monkey-face",
    category: "nature",
    unicode: "_1f435",
    htmlEntity: "&#x1F435",
  },
  "🙈": {
    name: "see-no-evil-monkey",
    category: "nature",
    unicode: "_1f648",
    htmlEntity: "&#x1F648",
  },
  "🙉": {
    name: "hear-no-evil-monkey",
    category: "nature",
    unicode: "_1f649",
    htmlEntity: "&#x1F649",
  },
  "🙊": {
    name: "speak-no-evil-monkey",
    category: "nature",
    unicode: "_1f64a",
    htmlEntity: "&#x1F64A",
  },
  "🐒": {
    name: "monkey",
    category: "nature",
    unicode: "_1f412",
    htmlEntity: "&#x1F412",
  },
  "🐔": {
    name: "chicken",
    category: "nature",
    unicode: "_1f414",
    htmlEntity: "&#x1F414",
  },
  "🐧": {
    name: "penguin",
    category: "nature",
    unicode: "_1f427",
    htmlEntity: "&#x1F427",
  },
  "🐦": {
    name: "bird",
    category: "nature",
    unicode: "_1f426",
    htmlEntity: "&#x1F426",
  },
  "🐤": {
    name: "baby-chick",
    category: "nature",
    unicode: "_1f424",
    htmlEntity: "&#x1F424",
  },
  "🐣": {
    name: "hatching-chick",
    category: "nature",
    unicode: "_1f423",
    htmlEntity: "&#x1F423",
  },
  "🐥": {
    name: "front-facing-baby-chick",
    category: "nature",
    unicode: "_1f425",
    htmlEntity: "&#x1F425",
  },
  "🦆": {
    name: "duck",
    category: "nature",
    unicode: "_1f986",
    htmlEntity: "&#x1F986",
  },
  "🦤": {
    name: "dodo",
    category: "nature",
    unicode: "_1f9a4",
    htmlEntity: "&#x1F9A4",
  },
  "🦅": {
    name: "eagle",
    category: "nature",
    unicode: "_1f985",
    htmlEntity: "&#x1F985",
  },
  "🦉": {
    name: "owl",
    category: "nature",
    unicode: "_1f989",
    htmlEntity: "&#x1F989",
  },
  "🦇": {
    name: "bat",
    category: "nature",
    unicode: "_1f987",
    htmlEntity: "&#x1F987",
  },
  "🐺": {
    name: "wolf",
    category: "nature",
    unicode: "_1f43a",
    htmlEntity: "&#x1F43A",
  },
  "🐗": {
    name: "boar",
    category: "nature",
    unicode: "_1f417",
    htmlEntity: "&#x1F417",
  },
  "🐴": {
    name: "horse-face",
    category: "nature",
    unicode: "_1f434",
    htmlEntity: "&#x1F434",
  },
  "🦄": {
    name: "unicorn",
    category: "nature",
    unicode: "_1f984",
    htmlEntity: "&#x1F984",
  },
  "🐝": {
    name: "honeybee",
    category: "nature",
    unicode: "_1f41d",
    htmlEntity: "&#x1F41D",
  },
  "🐛": {
    name: "bug",
    category: "nature",
    unicode: "_1f41b",
    htmlEntity: "&#x1F41B",
  },
  "🦋": {
    name: "butterfly",
    category: "nature",
    unicode: "_1f98b",
    htmlEntity: "&#x1F98B",
  },
  "🐌": {
    name: "snail",
    category: "nature",
    unicode: "_1f40c",
    htmlEntity: "&#x1F40C",
  },
  "🪱": {
    name: "worm",
    category: "nature",
    unicode: "_1fab1",
    htmlEntity: "&#x1FAB1",
  },
  "🐞": {
    name: "lady-beetle",
    category: "nature",
    unicode: "_1f41e",
    htmlEntity: "&#x1F41E",
  },
  "🐜": {
    name: "ant",
    category: "nature",
    unicode: "_1f41c",
    htmlEntity: "&#x1F41C",
  },
  "🪰": {
    name: "fly",
    category: "nature",
    unicode: "_1fab0",
    htmlEntity: "&#x1FAB0",
  },
  "🦟": {
    name: "mosquito",
    category: "nature",
    unicode: "_1f99f",
    htmlEntity: "&#x1F99F",
  },
  "🪳": {
    name: "cockroach",
    category: "nature",
    unicode: "_1fab3",
    htmlEntity: "&#x1FAB3",
  },
  "🪲": {
    name: "beetle",
    category: "nature",
    unicode: "_1fab2",
    htmlEntity: "&#x1FAB2",
  },
  "🦗": {
    name: "cricket",
    category: "nature",
    unicode: "_1f997",
    htmlEntity: "&#x1F997",
  },
  "🕷": {
    name: "spider",
    category: "nature",
    unicode: "_1f577",
    htmlEntity: "&#x1F577",
  },
  "🕸": {
    name: "spider-web",
    category: "nature",
    unicode: "_1f578",
    htmlEntity: "&#x1F578",
  },
  "🦂": {
    name: "scorpion",
    category: "nature",
    unicode: "_1f982",
    htmlEntity: "&#x1F982",
  },
  "🐢": {
    name: "turtle",
    category: "nature",
    unicode: "_1f422",
    htmlEntity: "&#x1F422",
  },
  "🐍": {
    name: "snake",
    category: "nature",
    unicode: "_1f40d",
    htmlEntity: "&#x1F40D",
  },
  "🦎": {
    name: "lizard",
    category: "nature",
    unicode: "_1f98e",
    htmlEntity: "&#x1F98E",
  },
  "🦖": {
    name: "t-rex",
    category: "nature",
    unicode: "_1f996",
    htmlEntity: "&#x1F996",
  },
  "🦕": {
    name: "sauropod",
    category: "nature",
    unicode: "_1f995",
    htmlEntity: "&#x1F995",
  },
  "🐙": {
    name: "octopus",
    category: "nature",
    unicode: "_1f419",
    htmlEntity: "&#x1F419",
  },
  "🦑": {
    name: "squid",
    category: "nature",
    unicode: "_1f991",
    htmlEntity: "&#x1F991",
  },
  "🦐": {
    name: "shrimp",
    category: "nature",
    unicode: "_1f990",
    htmlEntity: "&#x1F990",
  },
  "🦞": {
    name: "lobster",
    category: "nature",
    unicode: "_1f99e",
    htmlEntity: "&#x1F99E",
  },
  "🦀": {
    name: "crab",
    category: "nature",
    unicode: "_1f980",
    htmlEntity: "&#x1F980",
  },
  "🐡": {
    name: "blowfish",
    category: "nature",
    unicode: "_1f421",
    htmlEntity: "&#x1F421",
  },
  "🐠": {
    name: "tropical-fish",
    category: "nature",
    unicode: "_1f420",
    htmlEntity: "&#x1F420",
  },
  "🐟": {
    name: "fish",
    category: "nature",
    unicode: "_1f41f",
    htmlEntity: "&#x1F41F",
  },
  "🦭": {
    name: "seal",
    category: "nature",
    unicode: "_1f9ad",
    htmlEntity: "&#x1F9AD",
  },
  "🐬": {
    name: "dolphin",
    category: "nature",
    unicode: "_1f42c",
    htmlEntity: "&#x1F42C",
  },
  "🐳": {
    name: "spouting-whale",
    category: "nature",
    unicode: "_1f433",
    htmlEntity: "&#x1F433",
  },
  "🐋": {
    name: "whale",
    category: "nature",
    unicode: "_1f40b",
    htmlEntity: "&#x1F40B",
  },
  "🦈": {
    name: "shark",
    category: "nature",
    unicode: "_1f988",
    htmlEntity: "&#x1F988",
  },
  "🐊": {
    name: "crocodile",
    category: "nature",
    unicode: "_1f40a",
    htmlEntity: "&#x1F40A",
  },
  "🐅": {
    name: "tiger",
    category: "nature",
    unicode: "_1f405",
    htmlEntity: "&#x1F405",
  },
  "🐆": {
    name: "leopard",
    category: "nature",
    unicode: "_1f406",
    htmlEntity: "&#x1F406",
  },
  "🦓": {
    name: "zebra",
    category: "nature",
    unicode: "_1f993",
    htmlEntity: "&#x1F993",
  },
  "🦍": {
    name: "gorilla",
    category: "nature",
    unicode: "_1f98d",
    htmlEntity: "&#x1F98D",
  },
  "🦧": {
    name: "orangutan",
    category: "nature",
    unicode: "_1f9a7",
    htmlEntity: "&#x1F9A7",
  },
  "🐘": {
    name: "elephant",
    category: "nature",
    unicode: "_1f418",
    htmlEntity: "&#x1F418",
  },
  "🦣": {
    name: "mammoth",
    category: "nature",
    unicode: "_1f9a3",
    htmlEntity: "&#x1F9A3",
  },
  "🦬": {
    name: "bison",
    category: "nature",
    unicode: "_1f9ac",
    htmlEntity: "&#x1F9AC",
  },
  "🦛": {
    name: "hippopotamus",
    category: "nature",
    unicode: "_1f99b",
    htmlEntity: "&#x1F99B",
  },
  "🦏": {
    name: "rhinoceros",
    category: "nature",
    unicode: "_1f98f",
    htmlEntity: "&#x1F98F",
  },
  "🐪": {
    name: "camel",
    category: "nature",
    unicode: "_1f42a",
    htmlEntity: "&#x1F42A",
  },
  "🐫": {
    name: "two-hump-camel",
    category: "nature",
    unicode: "_1f42b",
    htmlEntity: "&#x1F42B",
  },
  "🦒": {
    name: "giraffe",
    category: "nature",
    unicode: "_1f992",
    htmlEntity: "&#x1F992",
  },
  "🦘": {
    name: "kangaroo",
    category: "nature",
    unicode: "_1f998",
    htmlEntity: "&#x1F998",
  },
  "🐃": {
    name: "water-buffalo",
    category: "nature",
    unicode: "_1f403",
    htmlEntity: "&#x1F403",
  },
  "🐂": {
    name: "ox",
    category: "nature",
    unicode: "_1f402",
    htmlEntity: "&#x1F402",
  },
  "🐄": {
    name: "cow",
    category: "nature",
    unicode: "_1f404",
    htmlEntity: "&#x1F404",
  },
  "🐎": {
    name: "horse",
    category: "nature",
    unicode: "_1f40e",
    htmlEntity: "&#x1F40E",
  },
  "🐖": {
    name: "pig",
    category: "nature",
    unicode: "_1f416",
    htmlEntity: "&#x1F416",
  },
  "🐏": {
    name: "ram",
    category: "nature",
    unicode: "_1f40f",
    htmlEntity: "&#x1F40F",
  },
  "🐑": {
    name: "ewe",
    category: "nature",
    unicode: "_1f411",
    htmlEntity: "&#x1F411",
  },
  "🦙": {
    name: "llama",
    category: "nature",
    unicode: "_1f999",
    htmlEntity: "&#x1F999",
  },
  "🐐": {
    name: "goat",
    category: "nature",
    unicode: "_1f410",
    htmlEntity: "&#x1F410",
  },
  "🦌": {
    name: "deer",
    category: "nature",
    unicode: "_1f98c",
    htmlEntity: "&#x1F98C",
  },
  "🐕": {
    name: "dog",
    category: "nature",
    unicode: "_1f415",
    htmlEntity: "&#x1F415",
  },
  "🐩": {
    name: "poodle",
    category: "nature",
    unicode: "_1f429",
    htmlEntity: "&#x1F429",
  },
  "🦮": {
    name: "guide-dog",
    category: "nature",
    unicode: "_1f9ae",
    htmlEntity: "&#x1F9AE",
  },
  "🐕🦺": {
    name: "service-dog",
    category: "nature",
    unicode: "_1f415-1f9ba",
    htmlEntity: "&#x1F415;&#x1F9BA",
  },
  "🐈": {
    name: "cat",
    category: "nature",
    unicode: "_1f408",
    htmlEntity: "&#x1F408",
  },
  "🐈⬛": {
    name: "black-cat",
    category: "nature",
    unicode: "_1f408-2b1b",
    htmlEntity: "&#x1F408;&#x2B1B",
  },
  "🐓": {
    name: "rooster",
    category: "nature",
    unicode: "_1f413",
    htmlEntity: "&#x1F413",
  },
  "🦃": {
    name: "turkey",
    category: "nature",
    unicode: "_1f983",
    htmlEntity: "&#x1F983",
  },
  "🦚": {
    name: "peacock",
    category: "nature",
    unicode: "_1f99a",
    htmlEntity: "&#x1F99A",
  },
  "🦜": {
    name: "parrot",
    category: "nature",
    unicode: "_1f99c",
    htmlEntity: "&#x1F99C",
  },
  "🦢": {
    name: "swan",
    category: "nature",
    unicode: "_1f9a2",
    htmlEntity: "&#x1F9A2",
  },
  "🦩": {
    name: "flamingo",
    category: "nature",
    unicode: "_1f9a9",
    htmlEntity: "&#x1F9A9",
  },
  "🕊": {
    name: "dove",
    category: "nature",
    unicode: "_1f54a",
    htmlEntity: "&#x1F54A",
  },
  "🐇": {
    name: "rabbit",
    category: "nature",
    unicode: "_1f407",
    htmlEntity: "&#x1F407",
  },
  "🦝": {
    name: "raccoon",
    category: "nature",
    unicode: "_1f99d",
    htmlEntity: "&#x1F99D",
  },
  "🦨": {
    name: "skunk",
    category: "nature",
    unicode: "_1f9a8",
    htmlEntity: "&#x1F9A8",
  },
  "🦡": {
    name: "badger",
    category: "nature",
    unicode: "_1f9a1",
    htmlEntity: "&#x1F9A1",
  },
  "🦫": {
    name: "beaver",
    category: "nature",
    unicode: "_1f9ab",
    htmlEntity: "&#x1F9AB",
  },
  "🦦": {
    name: "otter",
    category: "nature",
    unicode: "_1f9a6",
    htmlEntity: "&#x1F9A6",
  },
  "🦥": {
    name: "sloth",
    category: "nature",
    unicode: "_1f9a5",
    htmlEntity: "&#x1F9A5",
  },
  "🐁": {
    name: "mouse",
    category: "nature",
    unicode: "_1f401",
    htmlEntity: "&#x1F401",
  },
  "🐀": {
    name: "rat",
    category: "nature",
    unicode: "_1f400",
    htmlEntity: "&#x1F400",
  },
  "🐿": {
    name: "chipmunk",
    category: "nature",
    unicode: "_1f43f",
    htmlEntity: "&#x1F43F",
  },
  "🦔": {
    name: "hedgehog",
    category: "nature",
    unicode: "_1f994",
    htmlEntity: "&#x1F994",
  },
  "🐾": {
    name: "paw-prints",
    category: "nature",
    unicode: "_1f43e",
    htmlEntity: "&#x1F43E",
  },
  "🐉": {
    name: "dragon",
    category: "nature",
    unicode: "_1f409",
    htmlEntity: "&#x1F409",
  },
  "🐲": {
    name: "dragon-face",
    category: "nature",
    unicode: "_1f432",
    htmlEntity: "&#x1F432",
  },
  "🌵": {
    name: "cactus",
    category: "nature",
    unicode: "_1f335",
    htmlEntity: "&#x1F335",
  },
  "🎄": {
    name: "christmas-tree",
    category: "nature",
    unicode: "_1f384",
    htmlEntity: "&#x1F384",
  },
  "🌲": {
    name: "evergreen-tree",
    category: "nature",
    unicode: "_1f332",
    htmlEntity: "&#x1F332",
  },
  "🌳": {
    name: "deciduous-tree",
    category: "nature",
    unicode: "_1f333",
    htmlEntity: "&#x1F333",
  },
  "🌴": {
    name: "palm-tree",
    category: "nature",
    unicode: "_1f334",
    htmlEntity: "&#x1F334",
  },
  "🌱": {
    name: "seedling",
    category: "nature",
    unicode: "_1f331",
    htmlEntity: "&#x1F331",
  },
  "🌿": {
    name: "herb",
    category: "nature",
    unicode: "_1f33f",
    htmlEntity: "&#x1F33F",
  },
  "☘": {
    name: "shamrock",
    category: "nature",
    unicode: "_2618",
    htmlEntity: "&#x2618",
  },
  "🍀": {
    name: "four-leaf-clover",
    category: "nature",
    unicode: "_1f340",
    htmlEntity: "&#x1F340",
  },
  "🎍": {
    name: "pine-decoration",
    category: "nature",
    unicode: "_1f38d",
    htmlEntity: "&#x1F38D",
  },
  "🎋": {
    name: "tanabata-tree",
    category: "nature",
    unicode: "_1f38b",
    htmlEntity: "&#x1F38B",
  },
  "🍃": {
    name: "leaf-fluttering-in-wind",
    category: "nature",
    unicode: "_1f343",
    htmlEntity: "&#x1F343",
  },
  "🍂": {
    name: "fallen-leaf",
    category: "nature",
    unicode: "_1f342",
    htmlEntity: "&#x1F342",
  },
  "🍁": {
    name: "maple-leaf",
    category: "nature",
    unicode: "_1f341",
    htmlEntity: "&#x1F341",
  },
  "🪶": {
    name: "feather",
    category: "nature",
    unicode: "_1fab6",
    htmlEntity: "&#x1FAB6",
  },
  "🍄": {
    name: "mushroom",
    category: "nature",
    unicode: "_1f344",
    htmlEntity: "&#x1F344",
  },
  "🐚": {
    name: "spiral-shell",
    category: "nature",
    unicode: "_1f41a",
    htmlEntity: "&#x1F41A",
  },
  "🪨": {
    name: "rock",
    category: "nature",
    unicode: "_1faa8",
    htmlEntity: "&#x1FAA8",
  },
  "🪵": {
    name: "wood",
    category: "nature",
    unicode: "_1fab5",
    htmlEntity: "&#x1FAB5",
  },
  "🌾": {
    name: "sheaf-of-rice",
    category: "nature",
    unicode: "_1f33e",
    htmlEntity: "&#x1F33E",
  },
  "🪴": {
    name: "potted-plant",
    category: "nature",
    unicode: "_1fab4",
    htmlEntity: "&#x1FAB4",
  },
  "💐": {
    name: "bouquet",
    category: "nature",
    unicode: "_1f490",
    htmlEntity: "&#x1F490",
  },
  "🌷": {
    name: "tulip",
    category: "nature",
    unicode: "_1f337",
    htmlEntity: "&#x1F337",
  },
  "🌹": {
    name: "rose",
    category: "nature",
    unicode: "_1f339",
    htmlEntity: "&#x1F339",
  },
  "🥀": {
    name: "wilted-flower",
    category: "nature",
    unicode: "_1f940",
    htmlEntity: "&#x1F940",
  },
  "🌺": {
    name: "hibiscus",
    category: "nature",
    unicode: "_1f33a",
    htmlEntity: "&#x1F33A",
  },
  "🌸": {
    name: "cherry-blossom",
    category: "nature",
    unicode: "_1f338",
    htmlEntity: "&#x1F338",
  },
  "🌼": {
    name: "blossom",
    category: "nature",
    unicode: "_1f33c",
    htmlEntity: "&#x1F33C",
  },
  "🌻": {
    name: "sunflower",
    category: "nature",
    unicode: "_1f33b",
    htmlEntity: "&#x1F33B",
  },
  "🌞": {
    name: "sun-with-face",
    category: "nature",
    unicode: "_1f31e",
    htmlEntity: "&#x1F31E",
  },
  "🌝": {
    name: "full-moon-face",
    category: "nature",
    unicode: "_1f31d",
    htmlEntity: "&#x1F31D",
  },
  "🌛": {
    name: "first-quarter-moon-face",
    category: "nature",
    unicode: "_1f31b",
    htmlEntity: "&#x1F31B",
  },
  "🌜": {
    name: "last-quarter-moon-face",
    category: "nature",
    unicode: "_1f31c",
    htmlEntity: "&#x1F31C",
  },
  "🌚": {
    name: "new-moon-face",
    category: "nature",
    unicode: "_1f31a",
    htmlEntity: "&#x1F31A",
  },
  "🌕": {
    name: "full-moon",
    category: "nature",
    unicode: "_1f315",
    htmlEntity: "&#x1F315",
  },
  "🌖": {
    name: "waning-gibbous-moon",
    category: "nature",
    unicode: "_1f316",
    htmlEntity: "&#x1F316",
  },
  "🌗": {
    name: "last-quarter-moon",
    category: "nature",
    unicode: "_1f317",
    htmlEntity: "&#x1F317",
  },
  "🌘": {
    name: "waning-crescent-moon",
    category: "nature",
    unicode: "_1f318",
    htmlEntity: "&#x1F318",
  },
  "🌑": {
    name: "new-moon",
    category: "nature",
    unicode: "_1f311",
    htmlEntity: "&#x1F311",
  },
  "🌒": {
    name: "waxing-crescent-moon",
    category: "nature",
    unicode: "_1f312",
    htmlEntity: "&#x1F312",
  },
  "🌓": {
    name: "first-quarter-moon",
    category: "nature",
    unicode: "_1f313",
    htmlEntity: "&#x1F313",
  },
  "🌔": {
    name: "waxing-gibbous-moon",
    category: "nature",
    unicode: "_1f314",
    htmlEntity: "&#x1F314",
  },
  "🌙": {
    name: "crescent-moon",
    category: "nature",
    unicode: "_1f319",
    htmlEntity: "&#x1F319",
  },
  "🌎": {
    name: "globe-showing-americas",
    category: "nature",
    unicode: "_1f30e",
    htmlEntity: "&#x1F30E",
  },
  "🌍": {
    name: "globe-showing-europe-africa",
    category: "nature",
    unicode: "_1f30d",
    htmlEntity: "&#x1F30D",
  },
  "🌏": {
    name: "globe-showing-asia-australia",
    category: "nature",
    unicode: "_1f30f",
    htmlEntity: "&#x1F30F",
  },
  "🪐": {
    name: "ringed-planet",
    category: "nature",
    unicode: "_1fa90",
    htmlEntity: "&#x1FA90",
  },
  "💫": {
    name: "dizzy",
    category: "nature",
    unicode: "_1f4ab",
    htmlEntity: "&#x1F4AB",
  },
  "⭐": {
    name: "star",
    category: "nature",
    unicode: "_2b50",
    htmlEntity: "&#x2B50",
  },
  "🌟": {
    name: "glowing-star",
    category: "nature",
    unicode: "_1f31f",
    htmlEntity: "&#x1F31F",
  },
  "✨": {
    name: "sparkles",
    category: "nature",
    unicode: "_2728",
    htmlEntity: "&#x2728",
  },
  "⚡": {
    name: "high-voltage",
    category: "nature",
    unicode: "_26a1",
    htmlEntity: "&#x26A1",
  },
  "☄": {
    name: "comet",
    category: "nature",
    unicode: "_2604",
    htmlEntity: "&#x2604",
  },
  "💥": {
    name: "collision",
    category: "nature",
    unicode: "_1f4a5",
    htmlEntity: "&#x1F4A5",
  },
  "🔥": {
    name: "fire",
    category: "nature",
    unicode: "_1f525",
    htmlEntity: "&#x1F525",
  },
  "🌪": {
    name: "tornado",
    category: "nature",
    unicode: "_1f32a",
    htmlEntity: "&#x1F32A",
  },
  "🌈": {
    name: "rainbow",
    category: "nature",
    unicode: "_1f308",
    htmlEntity: "&#x1F308",
  },
  "☀": {
    name: "sun",
    category: "nature",
    unicode: "_2600",
    htmlEntity: "&#x2600",
  },
  "🌤": {
    name: "sun-behind-small-cloud",
    category: "nature",
    unicode: "_1f324",
    htmlEntity: "&#x1F324",
  },
  "⛅": {
    name: "sun-behind-cloud",
    category: "nature",
    unicode: "_26c5",
    htmlEntity: "&#x26C5",
  },
  "🌥": {
    name: "sun-behind-large-cloud",
    category: "nature",
    unicode: "_1f325",
    htmlEntity: "&#x1F325",
  },
  "☁": {
    name: "cloud",
    category: "nature",
    unicode: "_2601",
    htmlEntity: "&#x2601",
  },
  "🌦": {
    name: "sun-behind-rain-cloud",
    category: "nature",
    unicode: "_1f326",
    htmlEntity: "&#x1F326",
  },
  "🌧": {
    name: "cloud-with-rain",
    category: "nature",
    unicode: "_1f327",
    htmlEntity: "&#x1F327",
  },
  "⛈": {
    name: "cloud-with-lightning-and-rain",
    category: "nature",
    unicode: "_26c8",
    htmlEntity: "&#x26C8",
  },
  "🌩": {
    name: "cloud-with-lightning",
    category: "nature",
    unicode: "_1f329",
    htmlEntity: "&#x1F329",
  },
  "🌨": {
    name: "cloud-with-snow",
    category: "nature",
    unicode: "_1f328",
    htmlEntity: "&#x1F328",
  },
  "❄": {
    name: "snowflake",
    category: "nature",
    unicode: "_2744",
    htmlEntity: "&#x2744",
  },
  "☃": {
    name: "snowman",
    category: "nature",
    unicode: "_2603",
    htmlEntity: "&#x2603",
  },
  "⛄": {
    name: "snowman-without-snow",
    category: "nature",
    unicode: "_26c4",
    htmlEntity: "&#x26C4",
  },
  "🌬": {
    name: "wind-face",
    category: "nature",
    unicode: "_1f32c",
    htmlEntity: "&#x1F32C",
  },
  "💨": {
    name: "dashing-away",
    category: "nature",
    unicode: "_1f4a8",
    htmlEntity: "&#x1F4A8",
  },
  "💧": {
    name: "droplet",
    category: "nature",
    unicode: "_1f4a7",
    htmlEntity: "&#x1F4A7",
  },
  "💦": {
    name: "sweat-droplets",
    category: "nature",
    unicode: "_1f4a6",
    htmlEntity: "&#x1F4A6",
  },
  "☔": {
    name: "umbrella-with-rain-drops",
    category: "nature",
    unicode: "_2614",
    htmlEntity: "&#x2614",
  },
  "☂": {
    name: "umbrella",
    category: "nature",
    unicode: "_2602",
    htmlEntity: "&#x2602",
  },
  "🌊": {
    name: "water-wave",
    category: "nature",
    unicode: "_1f30a",
    htmlEntity: "&#x1F30A",
  },
  "🌫": {
    name: "fog",
    category: "nature",
    unicode: "_1f32b",
    htmlEntity: "&#x1F32B",
  },
};
