import { EmojiInformation } from "../types/emojiInformation";

export const FLAGS: EmojiInformation = {
  "🏳": {
    name: "white-flag",
    category: "flags",
    unicode: "_1f3f3",
    htmlEntity: "&#x1F3F3",
  },
  "🏴": {
    name: "black-flag",
    category: "flags",
    unicode: "_1f3f4",
    htmlEntity: "&#x1F3F4",
  },
  "🏁": {
    name: "chequered-flag",
    category: "flags",
    unicode: "_1f3c1",
    htmlEntity: "&#x1F3C1",
  },
  "🚩": {
    name: "triangular-flag",
    category: "flags",
    unicode: "_1f6a9",
    htmlEntity: "&#x1F6A9",
  },
  "🏳🌈": {
    name: "rainbow-flag",
    category: "flags",
    unicode: "_1f3f3-1f308",
    htmlEntity: "&#x1F3F3;&#x1F308",
  },
  "🏳⚧": {
    name: "transgender-flag",
    category: "flags",
    unicode: "_1f3f3-26a7",
    htmlEntity: "&#x1F3F3;&#x26A7",
  },
  "🏴☠": {
    name: "pirate-flag",
    category: "flags",
    unicode: "_1f3f4-2620",
    htmlEntity: "&#x1F3F4;&#x2620",
  },
  "🇦🇫": {
    name: "flag-afghanistan",
    category: "flags",
    unicode: "_1f1e6-1f1eb",
    htmlEntity: "&#x1F1E6;&#x1F1EB",
  },
  "🇦🇽": {
    name: "flag-åland-islands",
    category: "flags",
    unicode: "_1f1e6-1f1fd",
    htmlEntity: "&#x1F1E6;&#x1F1FD",
  },
  "🇦🇱": {
    name: "flag-albania",
    category: "flags",
    unicode: "_1f1e6-1f1f1",
    htmlEntity: "&#x1F1E6;&#x1F1F1",
  },
  "🇩🇿": {
    name: "flag-algeria",
    category: "flags",
    unicode: "_1f1e9-1f1ff",
    htmlEntity: "&#x1F1E9;&#x1F1FF",
  },
  "🇦🇸": {
    name: "flag-american-samoa",
    category: "flags",
    unicode: "_1f1e6-1f1f8",
    htmlEntity: "&#x1F1E6;&#x1F1F8",
  },
  "🇦🇩": {
    name: "flag-andorra",
    category: "flags",
    unicode: "_1f1e6-1f1e9",
    htmlEntity: "&#x1F1E6;&#x1F1E9",
  },
  "🇦🇴": {
    name: "flag-angola",
    category: "flags",
    unicode: "_1f1e6-1f1f4",
    htmlEntity: "&#x1F1E6;&#x1F1F4",
  },
  "🇦🇮": {
    name: "flag-anguilla",
    category: "flags",
    unicode: "_1f1e6-1f1ee",
    htmlEntity: "&#x1F1E6;&#x1F1EE",
  },
  "🇦🇶": {
    name: "flag-antarctica",
    category: "flags",
    unicode: "_1f1e6-1f1f6",
    htmlEntity: "&#x1F1E6;&#x1F1F6",
  },
  "🇦🇬": {
    name: "flag-antigua--barbuda",
    category: "flags",
    unicode: "_1f1e6-1f1ec",
    htmlEntity: "&#x1F1E6;&#x1F1EC",
  },
  "🇦🇷": {
    name: "flag-argentina",
    category: "flags",
    unicode: "_1f1e6-1f1f7",
    htmlEntity: "&#x1F1E6;&#x1F1F7",
  },
  "🇦🇲": {
    name: "flag-armenia",
    category: "flags",
    unicode: "_1f1e6-1f1f2",
    htmlEntity: "&#x1F1E6;&#x1F1F2",
  },
  "🇦🇼": {
    name: "flag-aruba",
    category: "flags",
    unicode: "_1f1e6-1f1fc",
    htmlEntity: "&#x1F1E6;&#x1F1FC",
  },
  "🇦🇺": {
    name: "flag-australia",
    category: "flags",
    unicode: "_1f1e6-1f1fa",
    htmlEntity: "&#x1F1E6;&#x1F1FA",
  },
  "🇦🇹": {
    name: "flag-austria",
    category: "flags",
    unicode: "_1f1e6-1f1f9",
    htmlEntity: "&#x1F1E6;&#x1F1F9",
  },
  "🇦🇿": {
    name: "flag-azerbaijan",
    category: "flags",
    unicode: "_1f1e6-1f1ff",
    htmlEntity: "&#x1F1E6;&#x1F1FF",
  },
  "🇧🇸": {
    name: "flag-bahamas",
    category: "flags",
    unicode: "_1f1e7-1f1f8",
    htmlEntity: "&#x1F1E7;&#x1F1F8",
  },
  "🇧🇭": {
    name: "flag-bahrain",
    category: "flags",
    unicode: "_1f1e7-1f1ed",
    htmlEntity: "&#x1F1E7;&#x1F1ED",
  },
  "🇧🇩": {
    name: "flag-bangladesh",
    category: "flags",
    unicode: "_1f1e7-1f1e9",
    htmlEntity: "&#x1F1E7;&#x1F1E9",
  },
  "🇧🇧": {
    name: "flag-barbados",
    category: "flags",
    unicode: "_1f1e7-1f1e7",
    htmlEntity: "&#x1F1E7;&#x1F1E7",
  },
  "🇧🇾": {
    name: "flag-belarus",
    category: "flags",
    unicode: "_1f1e7-1f1fe",
    htmlEntity: "&#x1F1E7;&#x1F1FE",
  },
  "🇧🇪": {
    name: "flag-belgium",
    category: "flags",
    unicode: "_1f1e7-1f1ea",
    htmlEntity: "&#x1F1E7;&#x1F1EA",
  },
  "🇧🇿": {
    name: "flag-belize",
    category: "flags",
    unicode: "_1f1e7-1f1ff",
    htmlEntity: "&#x1F1E7;&#x1F1FF",
  },
  "🇧🇯": {
    name: "flag-benin",
    category: "flags",
    unicode: "_1f1e7-1f1ef",
    htmlEntity: "&#x1F1E7;&#x1F1EF",
  },
  "🇧🇲": {
    name: "flag-bermuda",
    category: "flags",
    unicode: "_1f1e7-1f1f2",
    htmlEntity: "&#x1F1E7;&#x1F1F2",
  },
  "🇧🇹": {
    name: "flag-bhutan",
    category: "flags",
    unicode: "_1f1e7-1f1f9",
    htmlEntity: "&#x1F1E7;&#x1F1F9",
  },
  "🇧🇴": {
    name: "flag-bolivia",
    category: "flags",
    unicode: "_1f1e7-1f1f4",
    htmlEntity: "&#x1F1E7;&#x1F1F4",
  },
  "🇧🇦": {
    name: "flag-bosnia--herzegovina",
    category: "flags",
    unicode: "_1f1e7-1f1e6",
    htmlEntity: "&#x1F1E7;&#x1F1E6",
  },
  "🇧🇼": {
    name: "flag-botswana",
    category: "flags",
    unicode: "_1f1e7-1f1fc",
    htmlEntity: "&#x1F1E7;&#x1F1FC",
  },
  "🇧🇷": {
    name: "flag-brazil",
    category: "flags",
    unicode: "_1f1e7-1f1f7",
    htmlEntity: "&#x1F1E7;&#x1F1F7",
  },
  "🇮🇴": {
    name: "flag-british-indian-ocean-territory",
    category: "flags",
    unicode: "_1f1ee-1f1f4",
    htmlEntity: "&#x1F1EE;&#x1F1F4",
  },
  "🇻🇬": {
    name: "flag-british-virgin-islands",
    category: "flags",
    unicode: "_1f1fb-1f1ec",
    htmlEntity: "&#x1F1FB;&#x1F1EC",
  },
  "🇧🇳": {
    name: "flag-brunei",
    category: "flags",
    unicode: "_1f1e7-1f1f3",
    htmlEntity: "&#x1F1E7;&#x1F1F3",
  },
  "🇧🇬": {
    name: "flag-bulgaria",
    category: "flags",
    unicode: "_1f1e7-1f1ec",
    htmlEntity: "&#x1F1E7;&#x1F1EC",
  },
  "🇧🇫": {
    name: "flag-burkina-faso",
    category: "flags",
    unicode: "_1f1e7-1f1eb",
    htmlEntity: "&#x1F1E7;&#x1F1EB",
  },
  "🇧🇮": {
    name: "flag-burundi",
    category: "flags",
    unicode: "_1f1e7-1f1ee",
    htmlEntity: "&#x1F1E7;&#x1F1EE",
  },
  "🇰🇭": {
    name: "flag-cambodia",
    category: "flags",
    unicode: "_1f1f0-1f1ed",
    htmlEntity: "&#x1F1F0;&#x1F1ED",
  },
  "🇨🇲": {
    name: "flag-cameroon",
    category: "flags",
    unicode: "_1f1e8-1f1f2",
    htmlEntity: "&#x1F1E8;&#x1F1F2",
  },
  "🇨🇦": {
    name: "flag-canada",
    category: "flags",
    unicode: "_1f1e8-1f1e6",
    htmlEntity: "&#x1F1E8;&#x1F1E6",
  },
  "🇮🇨": {
    name: "flag-canary-islands",
    category: "flags",
    unicode: "_1f1ee-1f1e8",
    htmlEntity: "&#x1F1EE;&#x1F1E8",
  },
  "🇨🇻": {
    name: "flag-cape-verde",
    category: "flags",
    unicode: "_1f1e8-1f1fb",
    htmlEntity: "&#x1F1E8;&#x1F1FB",
  },
  "🇧🇶": {
    name: "flag-caribbean-netherlands",
    category: "flags",
    unicode: "_1f1e7-1f1f6",
    htmlEntity: "&#x1F1E7;&#x1F1F6",
  },
  "🇰🇾": {
    name: "flag-cayman-islands",
    category: "flags",
    unicode: "_1f1f0-1f1fe",
    htmlEntity: "&#x1F1F0;&#x1F1FE",
  },
  "🇨🇫": {
    name: "flag-central-african-republic",
    category: "flags",
    unicode: "_1f1e8-1f1eb",
    htmlEntity: "&#x1F1E8;&#x1F1EB",
  },
  "🇹🇩": {
    name: "flag-chad",
    category: "flags",
    unicode: "_1f1f9-1f1e9",
    htmlEntity: "&#x1F1F9;&#x1F1E9",
  },
  "🇨🇱": {
    name: "flag-chile",
    category: "flags",
    unicode: "_1f1e8-1f1f1",
    htmlEntity: "&#x1F1E8;&#x1F1F1",
  },
  "🇨🇳": {
    name: "flag-china",
    category: "flags",
    unicode: "_1f1e8-1f1f3",
    htmlEntity: "&#x1F1E8;&#x1F1F3",
  },
  "🇨🇽": {
    name: "flag-christmas-island",
    category: "flags",
    unicode: "_1f1e8-1f1fd",
    htmlEntity: "&#x1F1E8;&#x1F1FD",
  },
  "🇨🇨": {
    name: "flag-cocos-keeling-islands",
    category: "flags",
    unicode: "_1f1e8-1f1e8",
    htmlEntity: "&#x1F1E8;&#x1F1E8",
  },
  "🇨🇴": {
    name: "flag-colombia",
    category: "flags",
    unicode: "_1f1e8-1f1f4",
    htmlEntity: "&#x1F1E8;&#x1F1F4",
  },
  "🇰🇲": {
    name: "flag-comoros",
    category: "flags",
    unicode: "_1f1f0-1f1f2",
    htmlEntity: "&#x1F1F0;&#x1F1F2",
  },
  "🇨🇬": {
    name: "flag-congo---brazzaville",
    category: "flags",
    unicode: "_1f1e8-1f1ec",
    htmlEntity: "&#x1F1E8;&#x1F1EC",
  },
  "🇨🇩": {
    name: "flag-congo---kinshasa",
    category: "flags",
    unicode: "_1f1e8-1f1e9",
    htmlEntity: "&#x1F1E8;&#x1F1E9",
  },
  "🇨🇰": {
    name: "flag-cook-islands",
    category: "flags",
    unicode: "_1f1e8-1f1f0",
    htmlEntity: "&#x1F1E8;&#x1F1F0",
  },
  "🇨🇷": {
    name: "flag-costa-rica",
    category: "flags",
    unicode: "_1f1e8-1f1f7",
    htmlEntity: "&#x1F1E8;&#x1F1F7",
  },
  "🇨🇮": {
    name: "flag-côte-d’ivoire",
    category: "flags",
    unicode: "_1f1e8-1f1ee",
    htmlEntity: "&#x1F1E8;&#x1F1EE",
  },
  "🇭🇷": {
    name: "flag-croatia",
    category: "flags",
    unicode: "_1f1ed-1f1f7",
    htmlEntity: "&#x1F1ED;&#x1F1F7",
  },
  "🇨🇺": {
    name: "flag-cuba",
    category: "flags",
    unicode: "_1f1e8-1f1fa",
    htmlEntity: "&#x1F1E8;&#x1F1FA",
  },
  "🇨🇼": {
    name: "flag-curaçao",
    category: "flags",
    unicode: "_1f1e8-1f1fc",
    htmlEntity: "&#x1F1E8;&#x1F1FC",
  },
  "🇨🇾": {
    name: "flag-cyprus",
    category: "flags",
    unicode: "_1f1e8-1f1fe",
    htmlEntity: "&#x1F1E8;&#x1F1FE",
  },
  "🇨🇿": {
    name: "flag-czechia",
    category: "flags",
    unicode: "_1f1e8-1f1ff",
    htmlEntity: "&#x1F1E8;&#x1F1FF",
  },
  "🇩🇰": {
    name: "flag-denmark",
    category: "flags",
    unicode: "_1f1e9-1f1f0",
    htmlEntity: "&#x1F1E9;&#x1F1F0",
  },
  "🇩🇯": {
    name: "flag-djibouti",
    category: "flags",
    unicode: "_1f1e9-1f1ef",
    htmlEntity: "&#x1F1E9;&#x1F1EF",
  },
  "🇩🇲": {
    name: "flag-dominica",
    category: "flags",
    unicode: "_1f1e9-1f1f2",
    htmlEntity: "&#x1F1E9;&#x1F1F2",
  },
  "🇩🇴": {
    name: "flag-dominican-republic",
    category: "flags",
    unicode: "_1f1e9-1f1f4",
    htmlEntity: "&#x1F1E9;&#x1F1F4",
  },
  "🇪🇨": {
    name: "flag-ecuador",
    category: "flags",
    unicode: "_1f1ea-1f1e8",
    htmlEntity: "&#x1F1EA;&#x1F1E8",
  },
  "🇪🇬": {
    name: "flag-egypt",
    category: "flags",
    unicode: "_1f1ea-1f1ec",
    htmlEntity: "&#x1F1EA;&#x1F1EC",
  },
  "🇸🇻": {
    name: "flag-el-salvador",
    category: "flags",
    unicode: "_1f1f8-1f1fb",
    htmlEntity: "&#x1F1F8;&#x1F1FB",
  },
  "🇬🇶": {
    name: "flag-equatorial-guinea",
    category: "flags",
    unicode: "_1f1ec-1f1f6",
    htmlEntity: "&#x1F1EC;&#x1F1F6",
  },
  "🇪🇷": {
    name: "flag-eritrea",
    category: "flags",
    unicode: "_1f1ea-1f1f7",
    htmlEntity: "&#x1F1EA;&#x1F1F7",
  },
  "🇪🇪": {
    name: "flag-estonia",
    category: "flags",
    unicode: "_1f1ea-1f1ea",
    htmlEntity: "&#x1F1EA;&#x1F1EA",
  },
  "🇪🇹": {
    name: "flag-ethiopia",
    category: "flags",
    unicode: "_1f1ea-1f1f9",
    htmlEntity: "&#x1F1EA;&#x1F1F9",
  },
  "🇪🇺": {
    name: "flag-european-union",
    category: "flags",
    unicode: "_1f1ea-1f1fa",
    htmlEntity: "&#x1F1EA;&#x1F1FA",
  },
  "🇫🇰": {
    name: "flag-falkland-islands",
    category: "flags",
    unicode: "_1f1eb-1f1f0",
    htmlEntity: "&#x1F1EB;&#x1F1F0",
  },
  "🇫🇴": {
    name: "flag-faroe-islands",
    category: "flags",
    unicode: "_1f1eb-1f1f4",
    htmlEntity: "&#x1F1EB;&#x1F1F4",
  },
  "🇫🇯": {
    name: "flag-fiji",
    category: "flags",
    unicode: "_1f1eb-1f1ef",
    htmlEntity: "&#x1F1EB;&#x1F1EF",
  },
  "🇫🇮": {
    name: "flag-finland",
    category: "flags",
    unicode: "_1f1eb-1f1ee",
    htmlEntity: "&#x1F1EB;&#x1F1EE",
  },
  "🇫🇷": {
    name: "flag-france",
    category: "flags",
    unicode: "_1f1eb-1f1f7",
    htmlEntity: "&#x1F1EB;&#x1F1F7",
  },
  "🇬🇫": {
    name: "flag-french-guiana",
    category: "flags",
    unicode: "_1f1ec-1f1eb",
    htmlEntity: "&#x1F1EC;&#x1F1EB",
  },
  "🇵🇫": {
    name: "flag-french-polynesia",
    category: "flags",
    unicode: "_1f1f5-1f1eb",
    htmlEntity: "&#x1F1F5;&#x1F1EB",
  },
  "🇹🇫": {
    name: "flag-french-southern-territories",
    category: "flags",
    unicode: "_1f1f9-1f1eb",
    htmlEntity: "&#x1F1F9;&#x1F1EB",
  },
  "🇬🇦": {
    name: "flag-gabon",
    category: "flags",
    unicode: "_1f1ec-1f1e6",
    htmlEntity: "&#x1F1EC;&#x1F1E6",
  },
  "🇬🇲": {
    name: "flag-gambia",
    category: "flags",
    unicode: "_1f1ec-1f1f2",
    htmlEntity: "&#x1F1EC;&#x1F1F2",
  },
  "🇬🇪": {
    name: "flag-georgia",
    category: "flags",
    unicode: "_1f1ec-1f1ea",
    htmlEntity: "&#x1F1EC;&#x1F1EA",
  },
  "🇩🇪": {
    name: "flag-germany",
    category: "flags",
    unicode: "_1f1e9-1f1ea",
    htmlEntity: "&#x1F1E9;&#x1F1EA",
  },
  "🇬🇭": {
    name: "flag-ghana",
    category: "flags",
    unicode: "_1f1ec-1f1ed",
    htmlEntity: "&#x1F1EC;&#x1F1ED",
  },
  "🇬🇮": {
    name: "flag-gibraltar",
    category: "flags",
    unicode: "_1f1ec-1f1ee",
    htmlEntity: "&#x1F1EC;&#x1F1EE",
  },
  "🇬🇷": {
    name: "flag-greece",
    category: "flags",
    unicode: "_1f1ec-1f1f7",
    htmlEntity: "&#x1F1EC;&#x1F1F7",
  },
  "🇬🇱": {
    name: "flag-greenland",
    category: "flags",
    unicode: "_1f1ec-1f1f1",
    htmlEntity: "&#x1F1EC;&#x1F1F1",
  },
  "🇬🇩": {
    name: "flag-grenada",
    category: "flags",
    unicode: "_1f1ec-1f1e9",
    htmlEntity: "&#x1F1EC;&#x1F1E9",
  },
  "🇬🇵": {
    name: "flag-guadeloupe",
    category: "flags",
    unicode: "_1f1ec-1f1f5",
    htmlEntity: "&#x1F1EC;&#x1F1F5",
  },
  "🇬🇺": {
    name: "flag-guam",
    category: "flags",
    unicode: "_1f1ec-1f1fa",
    htmlEntity: "&#x1F1EC;&#x1F1FA",
  },
  "🇬🇹": {
    name: "flag-guatemala",
    category: "flags",
    unicode: "_1f1ec-1f1f9",
    htmlEntity: "&#x1F1EC;&#x1F1F9",
  },
  "🇬🇬": {
    name: "flag-guernsey",
    category: "flags",
    unicode: "_1f1ec-1f1ec",
    htmlEntity: "&#x1F1EC;&#x1F1EC",
  },
  "🇬🇳": {
    name: "flag-guinea",
    category: "flags",
    unicode: "_1f1ec-1f1f3",
    htmlEntity: "&#x1F1EC;&#x1F1F3",
  },
  "🇬🇼": {
    name: "flag-guinea-bissau",
    category: "flags",
    unicode: "_1f1ec-1f1fc",
    htmlEntity: "&#x1F1EC;&#x1F1FC",
  },
  "🇬🇾": {
    name: "flag-guyana",
    category: "flags",
    unicode: "_1f1ec-1f1fe",
    htmlEntity: "&#x1F1EC;&#x1F1FE",
  },
  "🇭🇹": {
    name: "flag-haiti",
    category: "flags",
    unicode: "_1f1ed-1f1f9",
    htmlEntity: "&#x1F1ED;&#x1F1F9",
  },
  "🇭🇳": {
    name: "flag-honduras",
    category: "flags",
    unicode: "_1f1ed-1f1f3",
    htmlEntity: "&#x1F1ED;&#x1F1F3",
  },
  "🇭🇰": {
    name: "flag-hong-kong-sar-china",
    category: "flags",
    unicode: "_1f1ed-1f1f0",
    htmlEntity: "&#x1F1ED;&#x1F1F0",
  },
  "🇭🇺": {
    name: "flag-hungary",
    category: "flags",
    unicode: "_1f1ed-1f1fa",
    htmlEntity: "&#x1F1ED;&#x1F1FA",
  },
  "🇮🇸": {
    name: "flag-iceland",
    category: "flags",
    unicode: "_1f1ee-1f1f8",
    htmlEntity: "&#x1F1EE;&#x1F1F8",
  },
  "🇮🇳": {
    name: "flag-india",
    category: "flags",
    unicode: "_1f1ee-1f1f3",
    htmlEntity: "&#x1F1EE;&#x1F1F3",
  },
  "🇮🇩": {
    name: "flag-indonesia",
    category: "flags",
    unicode: "_1f1ee-1f1e9",
    htmlEntity: "&#x1F1EE;&#x1F1E9",
  },
  "🇮🇷": {
    name: "flag-iran",
    category: "flags",
    unicode: "_1f1ee-1f1f7",
    htmlEntity: "&#x1F1EE;&#x1F1F7",
  },
  "🇮🇶": {
    name: "flag-iraq",
    category: "flags",
    unicode: "_1f1ee-1f1f6",
    htmlEntity: "&#x1F1EE;&#x1F1F6",
  },
  "🇮🇪": {
    name: "flag-ireland",
    category: "flags",
    unicode: "_1f1ee-1f1ea",
    htmlEntity: "&#x1F1EE;&#x1F1EA",
  },
  "🇮🇲": {
    name: "flag-isle-of-man",
    category: "flags",
    unicode: "_1f1ee-1f1f2",
    htmlEntity: "&#x1F1EE;&#x1F1F2",
  },
  "🇮🇱": {
    name: "flag-israel",
    category: "flags",
    unicode: "_1f1ee-1f1f1",
    htmlEntity: "&#x1F1EE;&#x1F1F1",
  },
  "🇮🇹": {
    name: "flag-italy",
    category: "flags",
    unicode: "_1f1ee-1f1f9",
    htmlEntity: "&#x1F1EE;&#x1F1F9",
  },
  "🇯🇲": {
    name: "flag-jamaica",
    category: "flags",
    unicode: "_1f1ef-1f1f2",
    htmlEntity: "&#x1F1EF;&#x1F1F2",
  },
  "🇯🇵": {
    name: "flag-japan",
    category: "flags",
    unicode: "_1f1ef-1f1f5",
    htmlEntity: "&#x1F1EF;&#x1F1F5",
  },
  "🎌": {
    name: "crossed-flags",
    category: "flags",
    unicode: "_1f38c",
    htmlEntity: "&#x1F38C",
  },
  "🇯🇪": {
    name: "flag-jersey",
    category: "flags",
    unicode: "_1f1ef-1f1ea",
    htmlEntity: "&#x1F1EF;&#x1F1EA",
  },
  "🇯🇴": {
    name: "flag-jordan",
    category: "flags",
    unicode: "_1f1ef-1f1f4",
    htmlEntity: "&#x1F1EF;&#x1F1F4",
  },
  "🇰🇿": {
    name: "flag-kazakhstan",
    category: "flags",
    unicode: "_1f1f0-1f1ff",
    htmlEntity: "&#x1F1F0;&#x1F1FF",
  },
  "🇰🇪": {
    name: "flag-kenya",
    category: "flags",
    unicode: "_1f1f0-1f1ea",
    htmlEntity: "&#x1F1F0;&#x1F1EA",
  },
  "🇰🇮": {
    name: "flag-kiribati",
    category: "flags",
    unicode: "_1f1f0-1f1ee",
    htmlEntity: "&#x1F1F0;&#x1F1EE",
  },
  "🇽🇰": {
    name: "flag-kosovo",
    category: "flags",
    unicode: "_1f1fd-1f1f0",
    htmlEntity: "&#x1F1FD;&#x1F1F0",
  },
  "🇰🇼": {
    name: "flag-kuwait",
    category: "flags",
    unicode: "_1f1f0-1f1fc",
    htmlEntity: "&#x1F1F0;&#x1F1FC",
  },
  "🇰🇬": {
    name: "flag-kyrgyzstan",
    category: "flags",
    unicode: "_1f1f0-1f1ec",
    htmlEntity: "&#x1F1F0;&#x1F1EC",
  },
  "🇱🇦": {
    name: "flag-laos",
    category: "flags",
    unicode: "_1f1f1-1f1e6",
    htmlEntity: "&#x1F1F1;&#x1F1E6",
  },
  "🇱🇻": {
    name: "flag-latvia",
    category: "flags",
    unicode: "_1f1f1-1f1fb",
    htmlEntity: "&#x1F1F1;&#x1F1FB",
  },
  "🇱🇧": {
    name: "flag-lebanon",
    category: "flags",
    unicode: "_1f1f1-1f1e7",
    htmlEntity: "&#x1F1F1;&#x1F1E7",
  },
  "🇱🇸": {
    name: "flag-lesotho",
    category: "flags",
    unicode: "_1f1f1-1f1f8",
    htmlEntity: "&#x1F1F1;&#x1F1F8",
  },
  "🇱🇷": {
    name: "flag-liberia",
    category: "flags",
    unicode: "_1f1f1-1f1f7",
    htmlEntity: "&#x1F1F1;&#x1F1F7",
  },
  "🇱🇾": {
    name: "flag-libya",
    category: "flags",
    unicode: "_1f1f1-1f1fe",
    htmlEntity: "&#x1F1F1;&#x1F1FE",
  },
  "🇱🇮": {
    name: "flag-liechtenstein",
    category: "flags",
    unicode: "_1f1f1-1f1ee",
    htmlEntity: "&#x1F1F1;&#x1F1EE",
  },
  "🇱🇹": {
    name: "flag-lithuania",
    category: "flags",
    unicode: "_1f1f1-1f1f9",
    htmlEntity: "&#x1F1F1;&#x1F1F9",
  },
  "🇱🇺": {
    name: "flag-luxembourg",
    category: "flags",
    unicode: "_1f1f1-1f1fa",
    htmlEntity: "&#x1F1F1;&#x1F1FA",
  },
  "🇲🇴": {
    name: "flag-macao-sar-china",
    category: "flags",
    unicode: "_1f1f2-1f1f4",
    htmlEntity: "&#x1F1F2;&#x1F1F4",
  },
  "🇲🇰": {
    name: "flag-macedonia",
    category: "flags",
    unicode: "_1f1f2-1f1f0",
    htmlEntity: "&#x1F1F2;&#x1F1F0",
  },
  "🇲🇬": {
    name: "flag-madagascar",
    category: "flags",
    unicode: "_1f1f2-1f1ec",
    htmlEntity: "&#x1F1F2;&#x1F1EC",
  },
  "🇲🇼": {
    name: "flag-malawi",
    category: "flags",
    unicode: "_1f1f2-1f1fc",
    htmlEntity: "&#x1F1F2;&#x1F1FC",
  },
  "🇲🇾": {
    name: "flag-malaysia",
    category: "flags",
    unicode: "_1f1f2-1f1fe",
    htmlEntity: "&#x1F1F2;&#x1F1FE",
  },
  "🇲🇻": {
    name: "flag-maldives",
    category: "flags",
    unicode: "_1f1f2-1f1fb",
    htmlEntity: "&#x1F1F2;&#x1F1FB",
  },
  "🇲🇱": {
    name: "flag-mali",
    category: "flags",
    unicode: "_1f1f2-1f1f1",
    htmlEntity: "&#x1F1F2;&#x1F1F1",
  },
  "🇲🇹": {
    name: "flag-malta",
    category: "flags",
    unicode: "_1f1f2-1f1f9",
    htmlEntity: "&#x1F1F2;&#x1F1F9",
  },
  "🇲🇭": {
    name: "flag-marshall-islands",
    category: "flags",
    unicode: "_1f1f2-1f1ed",
    htmlEntity: "&#x1F1F2;&#x1F1ED",
  },
  "🇲🇶": {
    name: "flag-martinique",
    category: "flags",
    unicode: "_1f1f2-1f1f6",
    htmlEntity: "&#x1F1F2;&#x1F1F6",
  },
  "🇲🇷": {
    name: "flag-mauritania",
    category: "flags",
    unicode: "_1f1f2-1f1f7",
    htmlEntity: "&#x1F1F2;&#x1F1F7",
  },
  "🇲🇺": {
    name: "flag-mauritius",
    category: "flags",
    unicode: "_1f1f2-1f1fa",
    htmlEntity: "&#x1F1F2;&#x1F1FA",
  },
  "🇾🇹": {
    name: "flag-mayotte",
    category: "flags",
    unicode: "_1f1fe-1f1f9",
    htmlEntity: "&#x1F1FE;&#x1F1F9",
  },
  "🇲🇽": {
    name: "flag-mexico",
    category: "flags",
    unicode: "_1f1f2-1f1fd",
    htmlEntity: "&#x1F1F2;&#x1F1FD",
  },
  "🇫🇲": {
    name: "flag-micronesia",
    category: "flags",
    unicode: "_1f1eb-1f1f2",
    htmlEntity: "&#x1F1EB;&#x1F1F2",
  },
  "🇲🇩": {
    name: "flag-moldova",
    category: "flags",
    unicode: "_1f1f2-1f1e9",
    htmlEntity: "&#x1F1F2;&#x1F1E9",
  },
  "🇲🇨": {
    name: "flag-monaco",
    category: "flags",
    unicode: "_1f1f2-1f1e8",
    htmlEntity: "&#x1F1F2;&#x1F1E8",
  },
  "🇲🇳": {
    name: "flag-mongolia",
    category: "flags",
    unicode: "_1f1f2-1f1f3",
    htmlEntity: "&#x1F1F2;&#x1F1F3",
  },
  "🇲🇪": {
    name: "flag-montenegro",
    category: "flags",
    unicode: "_1f1f2-1f1ea",
    htmlEntity: "&#x1F1F2;&#x1F1EA",
  },
  "🇲🇸": {
    name: "flag-montserrat",
    category: "flags",
    unicode: "_1f1f2-1f1f8",
    htmlEntity: "&#x1F1F2;&#x1F1F8",
  },
  "🇲🇦": {
    name: "flag-morocco",
    category: "flags",
    unicode: "_1f1f2-1f1e6",
    htmlEntity: "&#x1F1F2;&#x1F1E6",
  },
  "🇲🇿": {
    name: "flag-mozambique",
    category: "flags",
    unicode: "_1f1f2-1f1ff",
    htmlEntity: "&#x1F1F2;&#x1F1FF",
  },
  "🇲🇲": {
    name: "flag-myanmar-burma",
    category: "flags",
    unicode: "_1f1f2-1f1f2",
    htmlEntity: "&#x1F1F2;&#x1F1F2",
  },
  "🇳🇦": {
    name: "flag-namibia",
    category: "flags",
    unicode: "_1f1f3-1f1e6",
    htmlEntity: "&#x1F1F3;&#x1F1E6",
  },
  "🇳🇷": {
    name: "flag-nauru",
    category: "flags",
    unicode: "_1f1f3-1f1f7",
    htmlEntity: "&#x1F1F3;&#x1F1F7",
  },
  "🇳🇵": {
    name: "flag-nepal",
    category: "flags",
    unicode: "_1f1f3-1f1f5",
    htmlEntity: "&#x1F1F3;&#x1F1F5",
  },
  "🇳🇱": {
    name: "flag-netherlands",
    category: "flags",
    unicode: "_1f1f3-1f1f1",
    htmlEntity: "&#x1F1F3;&#x1F1F1",
  },
  "🇳🇨": {
    name: "flag-new-caledonia",
    category: "flags",
    unicode: "_1f1f3-1f1e8",
    htmlEntity: "&#x1F1F3;&#x1F1E8",
  },
  "🇳🇿": {
    name: "flag-new-zealand",
    category: "flags",
    unicode: "_1f1f3-1f1ff",
    htmlEntity: "&#x1F1F3;&#x1F1FF",
  },
  "🇳🇮": {
    name: "flag-nicaragua",
    category: "flags",
    unicode: "_1f1f3-1f1ee",
    htmlEntity: "&#x1F1F3;&#x1F1EE",
  },
  "🇳🇪": {
    name: "flag-niger",
    category: "flags",
    unicode: "_1f1f3-1f1ea",
    htmlEntity: "&#x1F1F3;&#x1F1EA",
  },
  "🇳🇬": {
    name: "flag-nigeria",
    category: "flags",
    unicode: "_1f1f3-1f1ec",
    htmlEntity: "&#x1F1F3;&#x1F1EC",
  },
  "🇳🇺": {
    name: "flag-niue",
    category: "flags",
    unicode: "_1f1f3-1f1fa",
    htmlEntity: "&#x1F1F3;&#x1F1FA",
  },
  "🇳🇫": {
    name: "flag-norfolk-island",
    category: "flags",
    unicode: "_1f1f3-1f1eb",
    htmlEntity: "&#x1F1F3;&#x1F1EB",
  },
  "🇰🇵": {
    name: "flag-north-korea",
    category: "flags",
    unicode: "_1f1f0-1f1f5",
    htmlEntity: "&#x1F1F0;&#x1F1F5",
  },
  "🇲🇵": {
    name: "flag-northern-mariana-islands",
    category: "flags",
    unicode: "_1f1f2-1f1f5",
    htmlEntity: "&#x1F1F2;&#x1F1F5",
  },
  "🇳🇴": {
    name: "flag-norway",
    category: "flags",
    unicode: "_1f1f3-1f1f4",
    htmlEntity: "&#x1F1F3;&#x1F1F4",
  },
  "🇴🇲": {
    name: "flag-oman",
    category: "flags",
    unicode: "_1f1f4-1f1f2",
    htmlEntity: "&#x1F1F4;&#x1F1F2",
  },
  "🇵🇰": {
    name: "flag-pakistan",
    category: "flags",
    unicode: "_1f1f5-1f1f0",
    htmlEntity: "&#x1F1F5;&#x1F1F0",
  },
  "🇵🇼": {
    name: "flag-palau",
    category: "flags",
    unicode: "_1f1f5-1f1fc",
    htmlEntity: "&#x1F1F5;&#x1F1FC",
  },
  "🇵🇸": {
    name: "flag-palestinian-territories",
    category: "flags",
    unicode: "_1f1f5-1f1f8",
    htmlEntity: "&#x1F1F5;&#x1F1F8",
  },
  "🇵🇦": {
    name: "flag-panama",
    category: "flags",
    unicode: "_1f1f5-1f1e6",
    htmlEntity: "&#x1F1F5;&#x1F1E6",
  },
  "🇵🇬": {
    name: "flag-papua-new-guinea",
    category: "flags",
    unicode: "_1f1f5-1f1ec",
    htmlEntity: "&#x1F1F5;&#x1F1EC",
  },
  "🇵🇾": {
    name: "flag-paraguay",
    category: "flags",
    unicode: "_1f1f5-1f1fe",
    htmlEntity: "&#x1F1F5;&#x1F1FE",
  },
  "🇵🇪": {
    name: "flag-peru",
    category: "flags",
    unicode: "_1f1f5-1f1ea",
    htmlEntity: "&#x1F1F5;&#x1F1EA",
  },
  "🇵🇭": {
    name: "flag-philippines",
    category: "flags",
    unicode: "_1f1f5-1f1ed",
    htmlEntity: "&#x1F1F5;&#x1F1ED",
  },
  "🇵🇳": {
    name: "flag-pitcairn-islands",
    category: "flags",
    unicode: "_1f1f5-1f1f3",
    htmlEntity: "&#x1F1F5;&#x1F1F3",
  },
  "🇵🇱": {
    name: "flag-poland",
    category: "flags",
    unicode: "_1f1f5-1f1f1",
    htmlEntity: "&#x1F1F5;&#x1F1F1",
  },
  "🇵🇹": {
    name: "flag-portugal",
    category: "flags",
    unicode: "_1f1f5-1f1f9",
    htmlEntity: "&#x1F1F5;&#x1F1F9",
  },
  "🇵🇷": {
    name: "flag-puerto-rico",
    category: "flags",
    unicode: "_1f1f5-1f1f7",
    htmlEntity: "&#x1F1F5;&#x1F1F7",
  },
  "🇶🇦": {
    name: "flag-qatar",
    category: "flags",
    unicode: "_1f1f6-1f1e6",
    htmlEntity: "&#x1F1F6;&#x1F1E6",
  },
  "🇷🇪": {
    name: "flag-réunion",
    category: "flags",
    unicode: "_1f1f7-1f1ea",
    htmlEntity: "&#x1F1F7;&#x1F1EA",
  },
  "🇷🇴": {
    name: "flag-romania",
    category: "flags",
    unicode: "_1f1f7-1f1f4",
    htmlEntity: "&#x1F1F7;&#x1F1F4",
  },
  "🇷🇺": {
    name: "flag-russia",
    category: "flags",
    unicode: "_1f1f7-1f1fa",
    htmlEntity: "&#x1F1F7;&#x1F1FA",
  },
  "🇷🇼": {
    name: "flag-rwanda",
    category: "flags",
    unicode: "_1f1f7-1f1fc",
    htmlEntity: "&#x1F1F7;&#x1F1FC",
  },
  "🇼🇸": {
    name: "flag-samoa",
    category: "flags",
    unicode: "_1f1fc-1f1f8",
    htmlEntity: "&#x1F1FC;&#x1F1F8",
  },
  "🇸🇲": {
    name: "flag-san-marino",
    category: "flags",
    unicode: "_1f1f8-1f1f2",
    htmlEntity: "&#x1F1F8;&#x1F1F2",
  },
  "🇸🇹": {
    name: "flag-são-tomé--príncipe",
    category: "flags",
    unicode: "_1f1f8-1f1f9",
    htmlEntity: "&#x1F1F8;&#x1F1F9",
  },
  "🇸🇦": {
    name: "flag-saudi-arabia",
    category: "flags",
    unicode: "_1f1f8-1f1e6",
    htmlEntity: "&#x1F1F8;&#x1F1E6",
  },
  "🇸🇳": {
    name: "flag-senegal",
    category: "flags",
    unicode: "_1f1f8-1f1f3",
    htmlEntity: "&#x1F1F8;&#x1F1F3",
  },
  "🇷🇸": {
    name: "flag-serbia",
    category: "flags",
    unicode: "_1f1f7-1f1f8",
    htmlEntity: "&#x1F1F7;&#x1F1F8",
  },
  "🇸🇨": {
    name: "flag-seychelles",
    category: "flags",
    unicode: "_1f1f8-1f1e8",
    htmlEntity: "&#x1F1F8;&#x1F1E8",
  },
  "🇸🇱": {
    name: "flag-sierra-leone",
    category: "flags",
    unicode: "_1f1f8-1f1f1",
    htmlEntity: "&#x1F1F8;&#x1F1F1",
  },
  "🇸🇬": {
    name: "flag-singapore",
    category: "flags",
    unicode: "_1f1f8-1f1ec",
    htmlEntity: "&#x1F1F8;&#x1F1EC",
  },
  "🇸🇽": {
    name: "flag-sint-maarten",
    category: "flags",
    unicode: "_1f1f8-1f1fd",
    htmlEntity: "&#x1F1F8;&#x1F1FD",
  },
  "🇸🇰": {
    name: "flag-slovakia",
    category: "flags",
    unicode: "_1f1f8-1f1f0",
    htmlEntity: "&#x1F1F8;&#x1F1F0",
  },
  "🇸🇮": {
    name: "flag-slovenia",
    category: "flags",
    unicode: "_1f1f8-1f1ee",
    htmlEntity: "&#x1F1F8;&#x1F1EE",
  },
  "🇬🇸": {
    name: "flag-south-georgia--south-sandwich-islands",
    category: "flags",
    unicode: "_1f1ec-1f1f8",
    htmlEntity: "&#x1F1EC;&#x1F1F8",
  },
  "🇸🇧": {
    name: "flag-solomon-islands",
    category: "flags",
    unicode: "_1f1f8-1f1e7",
    htmlEntity: "&#x1F1F8;&#x1F1E7",
  },
  "🇸🇴": {
    name: "flag-somalia",
    category: "flags",
    unicode: "_1f1f8-1f1f4",
    htmlEntity: "&#x1F1F8;&#x1F1F4",
  },
  "🇿🇦": {
    name: "flag-south-africa",
    category: "flags",
    unicode: "_1f1ff-1f1e6",
    htmlEntity: "&#x1F1FF;&#x1F1E6",
  },
  "🇰🇷": {
    name: "flag-south-korea",
    category: "flags",
    unicode: "_1f1f0-1f1f7",
    htmlEntity: "&#x1F1F0;&#x1F1F7",
  },
  "🇸🇸": {
    name: "flag-south-sudan",
    category: "flags",
    unicode: "_1f1f8-1f1f8",
    htmlEntity: "&#x1F1F8;&#x1F1F8",
  },
  "🇪🇸": {
    name: "flag-spain",
    category: "flags",
    unicode: "_1f1ea-1f1f8",
    htmlEntity: "&#x1F1EA;&#x1F1F8",
  },
  "🇱🇰": {
    name: "flag-sri-lanka",
    category: "flags",
    unicode: "_1f1f1-1f1f0",
    htmlEntity: "&#x1F1F1;&#x1F1F0",
  },
  "🇧🇱": {
    name: "flag-st-barthélemy",
    category: "flags",
    unicode: "_1f1e7-1f1f1",
    htmlEntity: "&#x1F1E7;&#x1F1F1",
  },
  "🇸🇭": {
    name: "flag-st-helena",
    category: "flags",
    unicode: "_1f1f8-1f1ed",
    htmlEntity: "&#x1F1F8;&#x1F1ED",
  },
  "🇰🇳": {
    name: "flag-st-kitts--nevis",
    category: "flags",
    unicode: "_1f1f0-1f1f3",
    htmlEntity: "&#x1F1F0;&#x1F1F3",
  },
  "🇱🇨": {
    name: "flag-st-lucia",
    category: "flags",
    unicode: "_1f1f1-1f1e8",
    htmlEntity: "&#x1F1F1;&#x1F1E8",
  },
  "🇵🇲": {
    name: "flag-st-pierre--miquelon",
    category: "flags",
    unicode: "_1f1f5-1f1f2",
    htmlEntity: "&#x1F1F5;&#x1F1F2",
  },
  "🇻🇨": {
    name: "flag-st-vincent--grenadines",
    category: "flags",
    unicode: "_1f1fb-1f1e8",
    htmlEntity: "&#x1F1FB;&#x1F1E8",
  },
  "🇸🇩": {
    name: "flag-sudan",
    category: "flags",
    unicode: "_1f1f8-1f1e9",
    htmlEntity: "&#x1F1F8;&#x1F1E9",
  },
  "🇸🇷": {
    name: "flag-suriname",
    category: "flags",
    unicode: "_1f1f8-1f1f7",
    htmlEntity: "&#x1F1F8;&#x1F1F7",
  },
  "🇸🇿": {
    name: "flag-eswatini",
    category: "flags",
    unicode: "_1f1f8-1f1ff",
    htmlEntity: "&#x1F1F8;&#x1F1FF",
  },
  "🇸🇪": {
    name: "flag-sweden",
    category: "flags",
    unicode: "_1f1f8-1f1ea",
    htmlEntity: "&#x1F1F8;&#x1F1EA",
  },
  "🇨🇭": {
    name: "flag-switzerland",
    category: "flags",
    unicode: "_1f1e8-1f1ed",
    htmlEntity: "&#x1F1E8;&#x1F1ED",
  },
  "🇸🇾": {
    name: "flag-syria",
    category: "flags",
    unicode: "_1f1f8-1f1fe",
    htmlEntity: "&#x1F1F8;&#x1F1FE",
  },
  "🇹🇼": {
    name: "flag-taiwan",
    category: "flags",
    unicode: "_1f1f9-1f1fc",
    htmlEntity: "&#x1F1F9;&#x1F1FC",
  },
  "🇹🇯": {
    name: "flag-tajikistan",
    category: "flags",
    unicode: "_1f1f9-1f1ef",
    htmlEntity: "&#x1F1F9;&#x1F1EF",
  },
  "🇹🇿": {
    name: "flag-tanzania",
    category: "flags",
    unicode: "_1f1f9-1f1ff",
    htmlEntity: "&#x1F1F9;&#x1F1FF",
  },
  "🇹🇭": {
    name: "flag-thailand",
    category: "flags",
    unicode: "_1f1f9-1f1ed",
    htmlEntity: "&#x1F1F9;&#x1F1ED",
  },
  "🇹🇱": {
    name: "flag-timor-leste",
    category: "flags",
    unicode: "_1f1f9-1f1f1",
    htmlEntity: "&#x1F1F9;&#x1F1F1",
  },
  "🇹🇬": {
    name: "flag-togo",
    category: "flags",
    unicode: "_1f1f9-1f1ec",
    htmlEntity: "&#x1F1F9;&#x1F1EC",
  },
  "🇹🇰": {
    name: "flag-tokelau",
    category: "flags",
    unicode: "_1f1f9-1f1f0",
    htmlEntity: "&#x1F1F9;&#x1F1F0",
  },
  "🇹🇴": {
    name: "flag-tonga",
    category: "flags",
    unicode: "_1f1f9-1f1f4",
    htmlEntity: "&#x1F1F9;&#x1F1F4",
  },
  "🇹🇹": {
    name: "flag-trinidad--tobago",
    category: "flags",
    unicode: "_1f1f9-1f1f9",
    htmlEntity: "&#x1F1F9;&#x1F1F9",
  },
  "🇹🇳": {
    name: "flag-tunisia",
    category: "flags",
    unicode: "_1f1f9-1f1f3",
    htmlEntity: "&#x1F1F9;&#x1F1F3",
  },
  "🇹🇷": {
    name: "flag-turkey",
    category: "flags",
    unicode: "_1f1f9-1f1f7",
    htmlEntity: "&#x1F1F9;&#x1F1F7",
  },
  "🇹🇲": {
    name: "flag-turkmenistan",
    category: "flags",
    unicode: "_1f1f9-1f1f2",
    htmlEntity: "&#x1F1F9;&#x1F1F2",
  },
  "🇹🇨": {
    name: "flag-turks--caicos-islands",
    category: "flags",
    unicode: "_1f1f9-1f1e8",
    htmlEntity: "&#x1F1F9;&#x1F1E8",
  },
  "🇻🇮": {
    name: "flag-us-virgin-islands",
    category: "flags",
    unicode: "_1f1fb-1f1ee",
    htmlEntity: "&#x1F1FB;&#x1F1EE",
  },
  "🇹🇻": {
    name: "flag-tuvalu",
    category: "flags",
    unicode: "_1f1f9-1f1fb",
    htmlEntity: "&#x1F1F9;&#x1F1FB",
  },
  "🇺🇬": {
    name: "flag-uganda",
    category: "flags",
    unicode: "_1f1fa-1f1ec",
    htmlEntity: "&#x1F1FA;&#x1F1EC",
  },
  "🇺🇦": {
    name: "flag-ukraine",
    category: "flags",
    unicode: "_1f1fa-1f1e6",
    htmlEntity: "&#x1F1FA;&#x1F1E6",
  },
  "🇦🇪": {
    name: "flag-united-arab-emirates",
    category: "flags",
    unicode: "_1f1e6-1f1ea",
    htmlEntity: "&#x1F1E6;&#x1F1EA",
  },
  "🇬🇧": {
    name: "flag-united-kingdom",
    category: "flags",
    unicode: "_1f1ec-1f1e7",
    htmlEntity: "&#x1F1EC;&#x1F1E7",
  },
  "🏴󠁧󠁢󠁥󠁮󠁧󠁿": {
    name: "flag-england",
    category: "flags",
    unicode: "_1f3f4-e0067-e0062-e0065-e006e-e0067-e007f",
    htmlEntity:
      "&#x1F3F4;&#xE0067;&#xE0062;&#xE0065;&#xE006E;&#xE0067;&#xE007F",
  },
  "🏴󠁧󠁢󠁳󠁣󠁴󠁿": {
    name: "flag-scotland",
    category: "flags",
    unicode: "_1f3f4-e0067-e0062-e0073-e0063-e0074-e007f",
    htmlEntity:
      "&#x1F3F4;&#xE0067;&#xE0062;&#xE0073;&#xE0063;&#xE0074;&#xE007F",
  },
  "🏴󠁧󠁢󠁷󠁬󠁳󠁿": {
    name: "flag-wales",
    category: "flags",
    unicode: "_1f3f4-e0067-e0062-e0077-e006c-e0073-e007f",
    htmlEntity:
      "&#x1F3F4;&#xE0067;&#xE0062;&#xE0077;&#xE006C;&#xE0073;&#xE007F",
  },
  "🇺🇸": {
    name: "flag-united-states",
    category: "flags",
    unicode: "_1f1fa-1f1f8",
    htmlEntity: "&#x1F1FA;&#x1F1F8",
  },
  "🇺🇾": {
    name: "flag-uruguay",
    category: "flags",
    unicode: "_1f1fa-1f1fe",
    htmlEntity: "&#x1F1FA;&#x1F1FE",
  },
  "🇺🇿": {
    name: "flag-uzbekistan",
    category: "flags",
    unicode: "_1f1fa-1f1ff",
    htmlEntity: "&#x1F1FA;&#x1F1FF",
  },
  "🇻🇺": {
    name: "flag-vanuatu",
    category: "flags",
    unicode: "_1f1fb-1f1fa",
    htmlEntity: "&#x1F1FB;&#x1F1FA",
  },
  "🇻🇦": {
    name: "flag-vatican-city",
    category: "flags",
    unicode: "_1f1fb-1f1e6",
    htmlEntity: "&#x1F1FB;&#x1F1E6",
  },
  "🇻🇪": {
    name: "flag-venezuela",
    category: "flags",
    unicode: "_1f1fb-1f1ea",
    htmlEntity: "&#x1F1FB;&#x1F1EA",
  },
  "🇻🇳": {
    name: "flag-vietnam",
    category: "flags",
    unicode: "_1f1fb-1f1f3",
    htmlEntity: "&#x1F1FB;&#x1F1F3",
  },
  "🇼🇫": {
    name: "flag-wallis--futuna",
    category: "flags",
    unicode: "_1f1fc-1f1eb",
    htmlEntity: "&#x1F1FC;&#x1F1EB",
  },
  "🇪🇭": {
    name: "flag-western-sahara",
    category: "flags",
    unicode: "_1f1ea-1f1ed",
    htmlEntity: "&#x1F1EA;&#x1F1ED",
  },
  "🇾🇪": {
    name: "flag-yemen",
    category: "flags",
    unicode: "_1f1fe-1f1ea",
    htmlEntity: "&#x1F1FE;&#x1F1EA",
  },
  "🇿🇲": {
    name: "flag-zambia",
    category: "flags",
    unicode: "_1f1ff-1f1f2",
    htmlEntity: "&#x1F1FF;&#x1F1F2",
  },
  "🇿🇼": {
    name: "flag-zimbabwe",
    category: "flags",
    unicode: "_1f1ff-1f1fc",
    htmlEntity: "&#x1F1FF;&#x1F1FC",
  },
  "🇦🇨": {
    name: "flag-ascension-island",
    category: "flags",
    unicode: "_1f1e6-1f1e8",
    htmlEntity: "&#x1F1E6;&#x1F1E8",
  },
  "🇧🇻": {
    name: "flag-bouvet-island",
    category: "flags",
    unicode: "_1f1e7-1f1fb",
    htmlEntity: "&#x1F1E7;&#x1F1FB",
  },
  "🇨🇵": {
    name: "flag-clipperton-island",
    category: "flags",
    unicode: "_1f1e8-1f1f5",
    htmlEntity: "&#x1F1E8;&#x1F1F5",
  },
  "🇪🇦": {
    name: "flag-ceuta--melilla",
    category: "flags",
    unicode: "_1f1ea-1f1e6",
    htmlEntity: "&#x1F1EA;&#x1F1E6",
  },
  "🇩🇬": {
    name: "flag-diego-garcia",
    category: "flags",
    unicode: "_1f1e9-1f1ec",
    htmlEntity: "&#x1F1E9;&#x1F1EC",
  },
  "🇭🇲": {
    name: "flag-heard--mcdonald-islands",
    category: "flags",
    unicode: "_1f1ed-1f1f2",
    htmlEntity: "&#x1F1ED;&#x1F1F2",
  },
  "🇲🇫": {
    name: "flag-st-martin",
    category: "flags",
    unicode: "_1f1f2-1f1eb",
    htmlEntity: "&#x1F1F2;&#x1F1EB",
  },
  "🇸🇯": {
    name: "flag-svalbard--jan-mayen",
    category: "flags",
    unicode: "_1f1f8-1f1ef",
    htmlEntity: "&#x1F1F8;&#x1F1EF",
  },
  "🇹🇦": {
    name: "flag-tristan-da-cunha",
    category: "flags",
    unicode: "_1f1f9-1f1e6",
    htmlEntity: "&#x1F1F9;&#x1F1E6",
  },
  "🇺🇲": {
    name: "flag-us-outlying-islands",
    category: "flags",
    unicode: "_1f1fa-1f1f2",
    htmlEntity: "&#x1F1FA;&#x1F1F2",
  },
  "🇺🇳": {
    name: "flag-united-nations",
    category: "flags",
    unicode: "_1f1fa-1f1f3",
    htmlEntity: "&#x1F1FA;&#x1F1F3",
  },
};
