import { EmojiInformation } from "../types/emojiInformation";

export const FOOD_AND_DRINK: EmojiInformation = {
  "🍏": {
    name: "green-apple",
    category: "food",
    unicode: "_1f34f",
    htmlEntity: "&#x1F34F",
  },
  "🍎": {
    name: "red-apple",
    category: "food",
    unicode: "_1f34e",
    htmlEntity: "&#x1F34E",
  },
  "🍐": {
    name: "pear",
    category: "food",
    unicode: "_1f350",
    htmlEntity: "&#x1F350",
  },
  "🍊": {
    name: "tangerine",
    category: "food",
    unicode: "_1f34a",
    htmlEntity: "&#x1F34A",
  },
  "🍋": {
    name: "lemon",
    category: "food",
    unicode: "_1f34b",
    htmlEntity: "&#x1F34B",
  },
  "🍌": {
    name: "banana",
    category: "food",
    unicode: "_1f34c",
    htmlEntity: "&#x1F34C",
  },
  "🍉": {
    name: "watermelon",
    category: "food",
    unicode: "_1f349",
    htmlEntity: "&#x1F349",
  },
  "🍇": {
    name: "grapes",
    category: "food",
    unicode: "_1f347",
    htmlEntity: "&#x1F347",
  },
  "🫐": {
    name: "blueberries",
    category: "food",
    unicode: "_1fad0",
    htmlEntity: "&#x1FAD0",
  },
  "🍓": {
    name: "strawberry",
    category: "food",
    unicode: "_1f353",
    htmlEntity: "&#x1F353",
  },
  "🍈": {
    name: "melon",
    category: "food",
    unicode: "_1f348",
    htmlEntity: "&#x1F348",
  },
  "🍒": {
    name: "cherries",
    category: "food",
    unicode: "_1f352",
    htmlEntity: "&#x1F352",
  },
  "🍑": {
    name: "peach",
    category: "food",
    unicode: "_1f351",
    htmlEntity: "&#x1F351",
  },
  "🥭": {
    name: "mango",
    category: "food",
    unicode: "_1f96d",
    htmlEntity: "&#x1F96D",
  },
  "🍍": {
    name: "pineapple",
    category: "food",
    unicode: "_1f34d",
    htmlEntity: "&#x1F34D",
  },
  "🥥": {
    name: "coconut",
    category: "food",
    unicode: "_1f965",
    htmlEntity: "&#x1F965",
  },
  "🥝": {
    name: "kiwi-fruit",
    category: "food",
    unicode: "_1f95d",
    htmlEntity: "&#x1F95D",
  },
  "🍅": {
    name: "tomato",
    category: "food",
    unicode: "_1f345",
    htmlEntity: "&#x1F345",
  },
  "🍆": {
    name: "eggplant",
    category: "food",
    unicode: "_1f346",
    htmlEntity: "&#x1F346",
  },
  "🥑": {
    name: "avocado",
    category: "food",
    unicode: "_1f951",
    htmlEntity: "&#x1F951",
  },
  "🫒": {
    name: "olive",
    category: "food",
    unicode: "_1fad2",
    htmlEntity: "&#x1FAD2",
  },
  "🥦": {
    name: "broccoli",
    category: "food",
    unicode: "_1f966",
    htmlEntity: "&#x1F966",
  },
  "🥬": {
    name: "leafy-green",
    category: "food",
    unicode: "_1f96c",
    htmlEntity: "&#x1F96C",
  },
  "🫑": {
    name: "bell-pepper",
    category: "food",
    unicode: "_1fad1",
    htmlEntity: "&#x1FAD1",
  },
  "🥒": {
    name: "cucumber",
    category: "food",
    unicode: "_1f952",
    htmlEntity: "&#x1F952",
  },
  "🌶": {
    name: "hot-pepper",
    category: "food",
    unicode: "_1f336",
    htmlEntity: "&#x1F336",
  },
  "🌽": {
    name: "ear-of-corn",
    category: "food",
    unicode: "_1f33d",
    htmlEntity: "&#x1F33D",
  },
  "🥕": {
    name: "carrot",
    category: "food",
    unicode: "_1f955",
    htmlEntity: "&#x1F955",
  },
  "🧄": {
    name: "garlic",
    category: "food",
    unicode: "_1f9c4",
    htmlEntity: "&#x1F9C4",
  },
  "🧅": {
    name: "onion",
    category: "food",
    unicode: "_1f9c5",
    htmlEntity: "&#x1F9C5",
  },
  "🥔": {
    name: "potato",
    category: "food",
    unicode: "_1f954",
    htmlEntity: "&#x1F954",
  },
  "🍠": {
    name: "roasted-sweet-potato",
    category: "food",
    unicode: "_1f360",
    htmlEntity: "&#x1F360",
  },
  "🥐": {
    name: "croissant",
    category: "food",
    unicode: "_1f950",
    htmlEntity: "&#x1F950",
  },
  "🥯": {
    name: "bagel",
    category: "food",
    unicode: "_1f96f",
    htmlEntity: "&#x1F96F",
  },
  "🍞": {
    name: "bread",
    category: "food",
    unicode: "_1f35e",
    htmlEntity: "&#x1F35E",
  },
  "🥖": {
    name: "baguette-bread",
    category: "food",
    unicode: "_1f956",
    htmlEntity: "&#x1F956",
  },
  "🫓": {
    name: "flatbread",
    category: "food",
    unicode: "_1fad3",
    htmlEntity: "&#x1FAD3",
  },
  "🥨": {
    name: "pretzel",
    category: "food",
    unicode: "_1f968",
    htmlEntity: "&#x1F968",
  },
  "🧀": {
    name: "cheese-wedge",
    category: "food",
    unicode: "_1f9c0",
    htmlEntity: "&#x1F9C0",
  },
  "🥚": {
    name: "egg",
    category: "food",
    unicode: "_1f95a",
    htmlEntity: "&#x1F95A",
  },
  "🍳": {
    name: "cooking",
    category: "food",
    unicode: "_1f373",
    htmlEntity: "&#x1F373",
  },
  "🧈": {
    name: "butter",
    category: "food",
    unicode: "_1f9c8",
    htmlEntity: "&#x1F9C8",
  },
  "🥞": {
    name: "pancakes",
    category: "food",
    unicode: "_1f95e",
    htmlEntity: "&#x1F95E",
  },
  "🧇": {
    name: "waffle",
    category: "food",
    unicode: "_1f9c7",
    htmlEntity: "&#x1F9C7",
  },
  "🥓": {
    name: "bacon",
    category: "food",
    unicode: "_1f953",
    htmlEntity: "&#x1F953",
  },
  "🥩": {
    name: "cut-of-meat",
    category: "food",
    unicode: "_1f969",
    htmlEntity: "&#x1F969",
  },
  "🍗": {
    name: "poultry-leg",
    category: "food",
    unicode: "_1f357",
    htmlEntity: "&#x1F357",
  },
  "🍖": {
    name: "meat-on-bone",
    category: "food",
    unicode: "_1f356",
    htmlEntity: "&#x1F356",
  },
  "🌭": {
    name: "hot-dog",
    category: "food",
    unicode: "_1f32d",
    htmlEntity: "&#x1F32D",
  },
  "🍔": {
    name: "hamburger",
    category: "food",
    unicode: "_1f354",
    htmlEntity: "&#x1F354",
  },
  "🍟": {
    name: "french-fries",
    category: "food",
    unicode: "_1f35f",
    htmlEntity: "&#x1F35F",
  },
  "🍕": {
    name: "pizza",
    category: "food",
    unicode: "_1f355",
    htmlEntity: "&#x1F355",
  },
  "🥪": {
    name: "sandwich",
    category: "food",
    unicode: "_1f96a",
    htmlEntity: "&#x1F96A",
  },
  "🥙": {
    name: "stuffed-flatbread",
    category: "food",
    unicode: "_1f959",
    htmlEntity: "&#x1F959",
  },
  "🧆": {
    name: "falafel",
    category: "food",
    unicode: "_1f9c6",
    htmlEntity: "&#x1F9C6",
  },
  "🌮": {
    name: "taco",
    category: "food",
    unicode: "_1f32e",
    htmlEntity: "&#x1F32E",
  },
  "🌯": {
    name: "burrito",
    category: "food",
    unicode: "_1f32f",
    htmlEntity: "&#x1F32F",
  },
  "🫔": {
    name: "tamale",
    category: "food",
    unicode: "_1fad4",
    htmlEntity: "&#x1FAD4",
  },
  "🥗": {
    name: "green-salad",
    category: "food",
    unicode: "_1f957",
    htmlEntity: "&#x1F957",
  },
  "🥘": {
    name: "shallow-pan-of-food",
    category: "food",
    unicode: "_1f958",
    htmlEntity: "&#x1F958",
  },
  "🫕": {
    name: "fondue",
    category: "food",
    unicode: "_1fad5",
    htmlEntity: "&#x1FAD5",
  },
  "🥫": {
    name: "canned-food",
    category: "food",
    unicode: "_1f96b",
    htmlEntity: "&#x1F96B",
  },
  "🍝": {
    name: "spaghetti",
    category: "food",
    unicode: "_1f35d",
    htmlEntity: "&#x1F35D",
  },
  "🍜": {
    name: "steaming-bowl",
    category: "food",
    unicode: "_1f35c",
    htmlEntity: "&#x1F35C",
  },
  "🍲": {
    name: "pot-of-food",
    category: "food",
    unicode: "_1f372",
    htmlEntity: "&#x1F372",
  },
  "🍛": {
    name: "curry-rice",
    category: "food",
    unicode: "_1f35b",
    htmlEntity: "&#x1F35B",
  },
  "🍣": {
    name: "sushi",
    category: "food",
    unicode: "_1f363",
    htmlEntity: "&#x1F363",
  },
  "🍱": {
    name: "bento-box",
    category: "food",
    unicode: "_1f371",
    htmlEntity: "&#x1F371",
  },
  "🥟": {
    name: "dumpling",
    category: "food",
    unicode: "_1f95f",
    htmlEntity: "&#x1F95F",
  },
  "🦪": {
    name: "oyster",
    category: "food",
    unicode: "_1f9aa",
    htmlEntity: "&#x1F9AA",
  },
  "🍤": {
    name: "fried-shrimp",
    category: "food",
    unicode: "_1f364",
    htmlEntity: "&#x1F364",
  },
  "🍙": {
    name: "rice-ball",
    category: "food",
    unicode: "_1f359",
    htmlEntity: "&#x1F359",
  },
  "🍚": {
    name: "cooked-rice",
    category: "food",
    unicode: "_1f35a",
    htmlEntity: "&#x1F35A",
  },
  "🍘": {
    name: "rice-cracker",
    category: "food",
    unicode: "_1f358",
    htmlEntity: "&#x1F358",
  },
  "🍥": {
    name: "fish-cake-with-swirl",
    category: "food",
    unicode: "_1f365",
    htmlEntity: "&#x1F365",
  },
  "🥠": {
    name: "fortune-cookie",
    category: "food",
    unicode: "_1f960",
    htmlEntity: "&#x1F960",
  },
  "🥮": {
    name: "moon-cake",
    category: "food",
    unicode: "_1f96e",
    htmlEntity: "&#x1F96E",
  },
  "🍢": {
    name: "oden",
    category: "food",
    unicode: "_1f362",
    htmlEntity: "&#x1F362",
  },
  "🍡": {
    name: "dango",
    category: "food",
    unicode: "_1f361",
    htmlEntity: "&#x1F361",
  },
  "🍧": {
    name: "shaved-ice",
    category: "food",
    unicode: "_1f367",
    htmlEntity: "&#x1F367",
  },
  "🍨": {
    name: "ice-cream",
    category: "food",
    unicode: "_1f368",
    htmlEntity: "&#x1F368",
  },
  "🍦": {
    name: "soft-ice-cream",
    category: "food",
    unicode: "_1f366",
    htmlEntity: "&#x1F366",
  },
  "🥧": {
    name: "pie",
    category: "food",
    unicode: "_1f967",
    htmlEntity: "&#x1F967",
  },
  "🧁": {
    name: "cupcake",
    category: "food",
    unicode: "_1f9c1",
    htmlEntity: "&#x1F9C1",
  },
  "🍰": {
    name: "shortcake",
    category: "food",
    unicode: "_1f370",
    htmlEntity: "&#x1F370",
  },
  "🎂": {
    name: "birthday-cake",
    category: "food",
    unicode: "_1f382",
    htmlEntity: "&#x1F382",
  },
  "🍮": {
    name: "custard",
    category: "food",
    unicode: "_1f36e",
    htmlEntity: "&#x1F36E",
  },
  "🍭": {
    name: "lollipop",
    category: "food",
    unicode: "_1f36d",
    htmlEntity: "&#x1F36D",
  },
  "🍬": {
    name: "candy",
    category: "food",
    unicode: "_1f36c",
    htmlEntity: "&#x1F36C",
  },
  "🍫": {
    name: "chocolate-bar",
    category: "food",
    unicode: "_1f36b",
    htmlEntity: "&#x1F36B",
  },
  "🍿": {
    name: "popcorn",
    category: "food",
    unicode: "_1f37f",
    htmlEntity: "&#x1F37F",
  },
  "🍩": {
    name: "doughnut",
    category: "food",
    unicode: "_1f369",
    htmlEntity: "&#x1F369",
  },
  "🍪": {
    name: "cookie",
    category: "food",
    unicode: "_1f36a",
    htmlEntity: "&#x1F36A",
  },
  "🌰": {
    name: "chestnut",
    category: "food",
    unicode: "_1f330",
    htmlEntity: "&#x1F330",
  },
  "🥜": {
    name: "peanuts",
    category: "food",
    unicode: "_1f95c",
    htmlEntity: "&#x1F95C",
  },
  "🍯": {
    name: "honey-pot",
    category: "food",
    unicode: "_1f36f",
    htmlEntity: "&#x1F36F",
  },
  "🥛": {
    name: "glass-of-milk",
    category: "food",
    unicode: "_1f95b",
    htmlEntity: "&#x1F95B",
  },
  "🍼": {
    name: "baby-bottle",
    category: "food",
    unicode: "_1f37c",
    htmlEntity: "&#x1F37C",
  },
  "☕": {
    name: "hot-beverage",
    category: "food",
    unicode: "_2615",
    htmlEntity: "&#x2615",
  },
  "🍵": {
    name: "teacup-without-handle",
    category: "food",
    unicode: "_1f375",
    htmlEntity: "&#x1F375",
  },
  "🫖": {
    name: "teapot",
    category: "food",
    unicode: "_1fad6",
    htmlEntity: "&#x1FAD6",
  },
  "🧉": {
    name: "mate",
    category: "food",
    unicode: "_1f9c9",
    htmlEntity: "&#x1F9C9",
  },
  "🧋": {
    name: "bubble-tea",
    category: "food",
    unicode: "_1f9cb",
    htmlEntity: "&#x1F9CB",
  },
  "🧃": {
    name: "beverage-box",
    category: "food",
    unicode: "_1f9c3",
    htmlEntity: "&#x1F9C3",
  },
  "🥤": {
    name: "cup-with-straw",
    category: "food",
    unicode: "_1f964",
    htmlEntity: "&#x1F964",
  },
  "🍶": {
    name: "sake",
    category: "food",
    unicode: "_1f376",
    htmlEntity: "&#x1F376",
  },
  "🍺": {
    name: "beer-mug",
    category: "food",
    unicode: "_1f37a",
    htmlEntity: "&#x1F37A",
  },
  "🍻": {
    name: "clinking-beer-mugs",
    category: "food",
    unicode: "_1f37b",
    htmlEntity: "&#x1F37B",
  },
  "🥂": {
    name: "clinking-glasses",
    category: "food",
    unicode: "_1f942",
    htmlEntity: "&#x1F942",
  },
  "🍷": {
    name: "wine-glass",
    category: "food",
    unicode: "_1f377",
    htmlEntity: "&#x1F377",
  },
  "🥃": {
    name: "tumbler-glass",
    category: "food",
    unicode: "_1f943",
    htmlEntity: "&#x1F943",
  },
  "🍸": {
    name: "cocktail-glass",
    category: "food",
    unicode: "_1f378",
    htmlEntity: "&#x1F378",
  },
  "🍹": {
    name: "tropical-drink",
    category: "food",
    unicode: "_1f379",
    htmlEntity: "&#x1F379",
  },
  "🍾": {
    name: "bottle-with-popping-cork",
    category: "food",
    unicode: "_1f37e",
    htmlEntity: "&#x1F37E",
  },
  "🧊": {
    name: "ice-cube",
    category: "food",
    unicode: "_1f9ca",
    htmlEntity: "&#x1F9CA",
  },
  "🥄": {
    name: "spoon",
    category: "food",
    unicode: "_1f944",
    htmlEntity: "&#x1F944",
  },
  "🍴": {
    name: "fork-and-knife",
    category: "food",
    unicode: "_1f374",
    htmlEntity: "&#x1F374",
  },
  "🍽": {
    name: "fork-and-knife-with-plate",
    category: "food",
    unicode: "_1f37d",
    htmlEntity: "&#x1F37D",
  },
  "🥣": {
    name: "bowl-with-spoon",
    category: "food",
    unicode: "_1f963",
    htmlEntity: "&#x1F963",
  },
  "🥡": {
    name: "takeout-box",
    category: "food",
    unicode: "_1f961",
    htmlEntity: "&#x1F961",
  },
  "🥢": {
    name: "chopsticks",
    category: "food",
    unicode: "_1f962",
    htmlEntity: "&#x1F962",
  },
  "🧂": {
    name: "salt",
    category: "food",
    unicode: "_1f9c2",
    htmlEntity: "&#x1F9C2",
  },
};
