import { EmojiInformation } from "../types/emojiInformation";

export const OBJECTS: EmojiInformation = {
  "⌚": {
    name: "watch",
    category: "objects",
    unicode: "_231a",
    htmlEntity: "&#x231A",
  },
  "📱": {
    name: "mobile-phone",
    category: "objects",
    unicode: "_1f4f1",
    htmlEntity: "&#x1F4F1",
  },
  "📲": {
    name: "mobile-phone-with-arrow",
    category: "objects",
    unicode: "_1f4f2",
    htmlEntity: "&#x1F4F2",
  },
  "💻": {
    name: "laptop-computer",
    category: "objects",
    unicode: "_1f4bb",
    htmlEntity: "&#x1F4BB",
  },
  "⌨": {
    name: "keyboard",
    category: "objects",
    unicode: "_2328",
    htmlEntity: "&#x2328",
  },
  "🖥": {
    name: "desktop-computer",
    category: "objects",
    unicode: "_1f5a5",
    htmlEntity: "&#x1F5A5",
  },
  "🖨": {
    name: "printer",
    category: "objects",
    unicode: "_1f5a8",
    htmlEntity: "&#x1F5A8",
  },
  "🖱": {
    name: "computer-mouse",
    category: "objects",
    unicode: "_1f5b1",
    htmlEntity: "&#x1F5B1",
  },
  "🖲": {
    name: "trackball",
    category: "objects",
    unicode: "_1f5b2",
    htmlEntity: "&#x1F5B2",
  },
  "🕹": {
    name: "joystick",
    category: "objects",
    unicode: "_1f579",
    htmlEntity: "&#x1F579",
  },
  "🗜": {
    name: "clamp",
    category: "objects",
    unicode: "_1f5dc",
    htmlEntity: "&#x1F5DC",
  },
  "💽": {
    name: "computer-disk",
    category: "objects",
    unicode: "_1f4bd",
    htmlEntity: "&#x1F4BD",
  },
  "💾": {
    name: "floppy-disk",
    category: "objects",
    unicode: "_1f4be",
    htmlEntity: "&#x1F4BE",
  },
  "💿": {
    name: "optical-disk",
    category: "objects",
    unicode: "_1f4bf",
    htmlEntity: "&#x1F4BF",
  },
  "📀": {
    name: "dvd",
    category: "objects",
    unicode: "_1f4c0",
    htmlEntity: "&#x1F4C0",
  },
  "📼": {
    name: "videocassette",
    category: "objects",
    unicode: "_1f4fc",
    htmlEntity: "&#x1F4FC",
  },
  "📷": {
    name: "camera",
    category: "objects",
    unicode: "_1f4f7",
    htmlEntity: "&#x1F4F7",
  },
  "📸": {
    name: "camera-with-flash",
    category: "objects",
    unicode: "_1f4f8",
    htmlEntity: "&#x1F4F8",
  },
  "📹": {
    name: "video-camera",
    category: "objects",
    unicode: "_1f4f9",
    htmlEntity: "&#x1F4F9",
  },
  "🎥": {
    name: "movie-camera",
    category: "objects",
    unicode: "_1f3a5",
    htmlEntity: "&#x1F3A5",
  },
  "📽": {
    name: "film-projector",
    category: "objects",
    unicode: "_1f4fd",
    htmlEntity: "&#x1F4FD",
  },
  "🎞": {
    name: "film-frames",
    category: "objects",
    unicode: "_1f39e",
    htmlEntity: "&#x1F39E",
  },
  "📞": {
    name: "telephone-receiver",
    category: "objects",
    unicode: "_1f4de",
    htmlEntity: "&#x1F4DE",
  },
  "☎": {
    name: "telephone",
    category: "objects",
    unicode: "_260e",
    htmlEntity: "&#x260E",
  },
  "📟": {
    name: "pager",
    category: "objects",
    unicode: "_1f4df",
    htmlEntity: "&#x1F4DF",
  },
  "📠": {
    name: "fax-machine",
    category: "objects",
    unicode: "_1f4e0",
    htmlEntity: "&#x1F4E0",
  },
  "📺": {
    name: "television",
    category: "objects",
    unicode: "_1f4fa",
    htmlEntity: "&#x1F4FA",
  },
  "📻": {
    name: "radio",
    category: "objects",
    unicode: "_1f4fb",
    htmlEntity: "&#x1F4FB",
  },
  "🎙": {
    name: "studio-microphone",
    category: "objects",
    unicode: "_1f399",
    htmlEntity: "&#x1F399",
  },
  "🎚": {
    name: "level-slider",
    category: "objects",
    unicode: "_1f39a",
    htmlEntity: "&#x1F39A",
  },
  "🎛": {
    name: "control-knobs",
    category: "objects",
    unicode: "_1f39b",
    htmlEntity: "&#x1F39B",
  },
  "🧭": {
    name: "compass",
    category: "objects",
    unicode: "_1f9ed",
    htmlEntity: "&#x1F9ED",
  },
  "⏱": {
    name: "stopwatch",
    category: "objects",
    unicode: "_23f1",
    htmlEntity: "&#x23F1",
  },
  "⏲": {
    name: "timer-clock",
    category: "objects",
    unicode: "_23f2",
    htmlEntity: "&#x23F2",
  },
  "⏰": {
    name: "alarm-clock",
    category: "objects",
    unicode: "_23f0",
    htmlEntity: "&#x23F0",
  },
  "🕰": {
    name: "mantelpiece-clock",
    category: "objects",
    unicode: "_1f570",
    htmlEntity: "&#x1F570",
  },
  "⌛": {
    name: "hourglass-done",
    category: "objects",
    unicode: "_231b",
    htmlEntity: "&#x231B",
  },
  "⏳": {
    name: "hourglass-not-done",
    category: "objects",
    unicode: "_23f3",
    htmlEntity: "&#x23F3",
  },
  "📡": {
    name: "satellite-antenna",
    category: "objects",
    unicode: "_1f4e1",
    htmlEntity: "&#x1F4E1",
  },
  "🔋": {
    name: "battery",
    category: "objects",
    unicode: "_1f50b",
    htmlEntity: "&#x1F50B",
  },
  "🔌": {
    name: "electric-plug",
    category: "objects",
    unicode: "_1f50c",
    htmlEntity: "&#x1F50C",
  },
  "💡": {
    name: "light-bulb",
    category: "objects",
    unicode: "_1f4a1",
    htmlEntity: "&#x1F4A1",
  },
  "🔦": {
    name: "flashlight",
    category: "objects",
    unicode: "_1f526",
    htmlEntity: "&#x1F526",
  },
  "🕯": {
    name: "candle",
    category: "objects",
    unicode: "_1f56f",
    htmlEntity: "&#x1F56F",
  },
  "🪔": {
    name: "diya-lamp",
    category: "objects",
    unicode: "_1fa94",
    htmlEntity: "&#x1FA94",
  },
  "🧯": {
    name: "fire-extinguisher",
    category: "objects",
    unicode: "_1f9ef",
    htmlEntity: "&#x1F9EF",
  },
  "🛢": {
    name: "oil-drum",
    category: "objects",
    unicode: "_1f6e2",
    htmlEntity: "&#x1F6E2",
  },
  "💸": {
    name: "money-with-wings",
    category: "objects",
    unicode: "_1f4b8",
    htmlEntity: "&#x1F4B8",
  },
  "💵": {
    name: "dollar-banknote",
    category: "objects",
    unicode: "_1f4b5",
    htmlEntity: "&#x1F4B5",
  },
  "💴": {
    name: "yen-banknote",
    category: "objects",
    unicode: "_1f4b4",
    htmlEntity: "&#x1F4B4",
  },
  "💶": {
    name: "euro-banknote",
    category: "objects",
    unicode: "_1f4b6",
    htmlEntity: "&#x1F4B6",
  },
  "💷": {
    name: "pound-banknote",
    category: "objects",
    unicode: "_1f4b7",
    htmlEntity: "&#x1F4B7",
  },
  "🪙": {
    name: "coin",
    category: "objects",
    unicode: "_1fa99",
    htmlEntity: "&#x1FA99",
  },
  "💰": {
    name: "money-bag",
    category: "objects",
    unicode: "_1f4b0",
    htmlEntity: "&#x1F4B0",
  },
  "💳": {
    name: "credit-card",
    category: "objects",
    unicode: "_1f4b3",
    htmlEntity: "&#x1F4B3",
  },
  "💎": {
    name: "gem-stone",
    category: "objects",
    unicode: "_1f48e",
    htmlEntity: "&#x1F48E",
  },
  "⚖": {
    name: "balance-scale",
    category: "objects",
    unicode: "_2696",
    htmlEntity: "&#x2696",
  },
  "🪜": {
    name: "ladder",
    category: "objects",
    unicode: "_1fa9c",
    htmlEntity: "&#x1FA9C",
  },
  "🧰": {
    name: "toolbox",
    category: "objects",
    unicode: "_1f9f0",
    htmlEntity: "&#x1F9F0",
  },
  "🪛": {
    name: "screwdriver",
    category: "objects",
    unicode: "_1fa9b",
    htmlEntity: "&#x1FA9B",
  },
  "🔧": {
    name: "wrench",
    category: "objects",
    unicode: "_1f527",
    htmlEntity: "&#x1F527",
  },
  "🔨": {
    name: "hammer",
    category: "objects",
    unicode: "_1f528",
    htmlEntity: "&#x1F528",
  },
  "⚒": {
    name: "hammer-and-pick",
    category: "objects",
    unicode: "_2692",
    htmlEntity: "&#x2692",
  },
  "🛠": {
    name: "hammer-and-wrench",
    category: "objects",
    unicode: "_1f6e0",
    htmlEntity: "&#x1F6E0",
  },
  "⛏": {
    name: "pick",
    category: "objects",
    unicode: "_26cf",
    htmlEntity: "&#x26CF",
  },
  "🔩": {
    name: "nut-and-bolt",
    category: "objects",
    unicode: "_1f529",
    htmlEntity: "&#x1F529",
  },
  "⚙": {
    name: "gear",
    category: "objects",
    unicode: "_2699",
    htmlEntity: "&#x2699",
  },
  "🧱": {
    name: "brick",
    category: "objects",
    unicode: "_1f9f1",
    htmlEntity: "&#x1F9F1",
  },
  "⛓": {
    name: "chains",
    category: "objects",
    unicode: "_26d3",
    htmlEntity: "&#x26D3",
  },
  "🪝": {
    name: "hook",
    category: "objects",
    unicode: "_1fa9d",
    htmlEntity: "&#x1FA9D",
  },
  "🪢": {
    name: "knot",
    category: "objects",
    unicode: "_1faa2",
    htmlEntity: "&#x1FAA2",
  },
  "🧲": {
    name: "magnet",
    category: "objects",
    unicode: "_1f9f2",
    htmlEntity: "&#x1F9F2",
  },
  "🔫": {
    name: "pistol",
    category: "objects",
    unicode: "_1f52b",
    htmlEntity: "&#x1F52B",
  },
  "💣": {
    name: "bomb",
    category: "objects",
    unicode: "_1f4a3",
    htmlEntity: "&#x1F4A3",
  },
  "🧨": {
    name: "firecracker",
    category: "objects",
    unicode: "_1f9e8",
    htmlEntity: "&#x1F9E8",
  },
  "🪓": {
    name: "axe",
    category: "objects",
    unicode: "_1fa93",
    htmlEntity: "&#x1FA93",
  },
  "🪚": {
    name: "carpentry-saw",
    category: "objects",
    unicode: "_1fa9a",
    htmlEntity: "&#x1FA9A",
  },
  "🔪": {
    name: "kitchen-knife",
    category: "objects",
    unicode: "_1f52a",
    htmlEntity: "&#x1F52A",
  },
  "🗡": {
    name: "dagger",
    category: "objects",
    unicode: "_1f5e1",
    htmlEntity: "&#x1F5E1",
  },
  "⚔": {
    name: "crossed-swords",
    category: "objects",
    unicode: "_2694",
    htmlEntity: "&#x2694",
  },
  "🛡": {
    name: "shield",
    category: "objects",
    unicode: "_1f6e1",
    htmlEntity: "&#x1F6E1",
  },
  "🚬": {
    name: "cigarette",
    category: "objects",
    unicode: "_1f6ac",
    htmlEntity: "&#x1F6AC",
  },
  "⚰": {
    name: "coffin",
    category: "objects",
    unicode: "_26b0",
    htmlEntity: "&#x26B0",
  },
  "🪦": {
    name: "headstone",
    category: "objects",
    unicode: "_1faa6",
    htmlEntity: "&#x1FAA6",
  },
  "⚱": {
    name: "funeral-urn",
    category: "objects",
    unicode: "_26b1",
    htmlEntity: "&#x26B1",
  },
  "🏺": {
    name: "amphora",
    category: "objects",
    unicode: "_1f3fa",
    htmlEntity: "&#x1F3FA",
  },
  "🪄": {
    name: "magic-wand",
    category: "objects",
    unicode: "_1fa84",
    htmlEntity: "&#x1FA84",
  },
  "🔮": {
    name: "crystal-ball",
    category: "objects",
    unicode: "_1f52e",
    htmlEntity: "&#x1F52E",
  },
  "📿": {
    name: "prayer-beads",
    category: "objects",
    unicode: "_1f4ff",
    htmlEntity: "&#x1F4FF",
  },
  "🧿": {
    name: "nazar-amulet",
    category: "objects",
    unicode: "_1f9ff",
    htmlEntity: "&#x1F9FF",
  },
  "💈": {
    name: "barber-pole",
    category: "objects",
    unicode: "_1f488",
    htmlEntity: "&#x1F488",
  },
  "⚗": {
    name: "alembic",
    category: "objects",
    unicode: "_2697",
    htmlEntity: "&#x2697",
  },
  "🔭": {
    name: "telescope",
    category: "objects",
    unicode: "_1f52d",
    htmlEntity: "&#x1F52D",
  },
  "🔬": {
    name: "microscope",
    category: "objects",
    unicode: "_1f52c",
    htmlEntity: "&#x1F52C",
  },
  "🕳": {
    name: "hole",
    category: "objects",
    unicode: "_1f573",
    htmlEntity: "&#x1F573",
  },
  "🪟": {
    name: "window",
    category: "objects",
    unicode: "_1fa9f",
    htmlEntity: "&#x1FA9F",
  },
  "🩹": {
    name: "adhesive-bandage",
    category: "objects",
    unicode: "_1fa79",
    htmlEntity: "&#x1FA79",
  },
  "🩺": {
    name: "stethoscope",
    category: "objects",
    unicode: "_1fa7a",
    htmlEntity: "&#x1FA7A",
  },
  "💊": {
    name: "pill",
    category: "objects",
    unicode: "_1f48a",
    htmlEntity: "&#x1F48A",
  },
  "💉": {
    name: "syringe",
    category: "objects",
    unicode: "_1f489",
    htmlEntity: "&#x1F489",
  },
  "🩸": {
    name: "drop-of-blood",
    category: "objects",
    unicode: "_1fa78",
    htmlEntity: "&#x1FA78",
  },
  "🧬": {
    name: "dna",
    category: "objects",
    unicode: "_1f9ec",
    htmlEntity: "&#x1F9EC",
  },
  "🦠": {
    name: "microbe",
    category: "objects",
    unicode: "_1f9a0",
    htmlEntity: "&#x1F9A0",
  },
  "🧫": {
    name: "petri-dish",
    category: "objects",
    unicode: "_1f9eb",
    htmlEntity: "&#x1F9EB",
  },
  "🧪": {
    name: "test-tube",
    category: "objects",
    unicode: "_1f9ea",
    htmlEntity: "&#x1F9EA",
  },
  "🌡": {
    name: "thermometer",
    category: "objects",
    unicode: "_1f321",
    htmlEntity: "&#x1F321",
  },
  "🪤": {
    name: "mouse-trap",
    category: "objects",
    unicode: "_1faa4",
    htmlEntity: "&#x1FAA4",
  },
  "🧹": {
    name: "broom",
    category: "objects",
    unicode: "_1f9f9",
    htmlEntity: "&#x1F9F9",
  },
  "🧺": {
    name: "basket",
    category: "objects",
    unicode: "_1f9fa",
    htmlEntity: "&#x1F9FA",
  },
  "🪡": {
    name: "sewing-needle",
    category: "objects",
    unicode: "_1faa1",
    htmlEntity: "&#x1FAA1",
  },
  "🧻": {
    name: "roll-of-paper",
    category: "objects",
    unicode: "_1f9fb",
    htmlEntity: "&#x1F9FB",
  },
  "🚽": {
    name: "toilet",
    category: "objects",
    unicode: "_1f6bd",
    htmlEntity: "&#x1F6BD",
  },
  "🪠": {
    name: "plunger",
    category: "objects",
    unicode: "_1faa0",
    htmlEntity: "&#x1FAA0",
  },
  "🪣": {
    name: "bucket",
    category: "objects",
    unicode: "_1faa3",
    htmlEntity: "&#x1FAA3",
  },
  "🚰": {
    name: "potable-water",
    category: "objects",
    unicode: "_1f6b0",
    htmlEntity: "&#x1F6B0",
  },
  "🚿": {
    name: "shower",
    category: "objects",
    unicode: "_1f6bf",
    htmlEntity: "&#x1F6BF",
  },
  "🛁": {
    name: "bathtub",
    category: "objects",
    unicode: "_1f6c1",
    htmlEntity: "&#x1F6C1",
  },
  "🛀": {
    name: "person-taking-bath",
    category: "objects",
    unicode: "_1f6c0",
    htmlEntity: "&#x1F6C0",
  },
  "🛀🏻": {
    name: "person-taking-bath-light-skin-tone",
    category: "diversity",
    unicode: "_1f6c0-1f3fb",
    htmlEntity: "&#x1F6C0;&#x1F3FB",
  },
  "🛀🏼": {
    name: "person-taking-bath-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f6c0-1f3fc",
    htmlEntity: "&#x1F6C0;&#x1F3FC",
  },
  "🛀🏽": {
    name: "person-taking-bath-medium-skin-tone",
    category: "diversity",
    unicode: "_1f6c0-1f3fd",
    htmlEntity: "&#x1F6C0;&#x1F3FD",
  },
  "🛀🏾": {
    name: "person-taking-bath-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f6c0-1f3fe",
    htmlEntity: "&#x1F6C0;&#x1F3FE",
  },
  "🛀🏿": {
    name: "person-taking-bath-dark-skin-tone",
    category: "diversity",
    unicode: "_1f6c0-1f3ff",
    htmlEntity: "&#x1F6C0;&#x1F3FF",
  },
  "🪥": {
    name: "toothbrush",
    category: "objects",
    unicode: "_1faa5",
    htmlEntity: "&#x1FAA5",
  },
  "🧼": {
    name: "soap",
    category: "objects",
    unicode: "_1f9fc",
    htmlEntity: "&#x1F9FC",
  },
  "🪒": {
    name: "razor",
    category: "objects",
    unicode: "_1fa92",
    htmlEntity: "&#x1FA92",
  },
  "🧽": {
    name: "sponge",
    category: "objects",
    unicode: "_1f9fd",
    htmlEntity: "&#x1F9FD",
  },
  "🧴": {
    name: "lotion-bottle",
    category: "objects",
    unicode: "_1f9f4",
    htmlEntity: "&#x1F9F4",
  },
  "🛎": {
    name: "bellhop-bell",
    category: "objects",
    unicode: "_1f6ce",
    htmlEntity: "&#x1F6CE",
  },
  "🔑": {
    name: "key",
    category: "objects",
    unicode: "_1f511",
    htmlEntity: "&#x1F511",
  },
  "🗝": {
    name: "old-key",
    category: "objects",
    unicode: "_1f5dd",
    htmlEntity: "&#x1F5DD",
  },
  "🚪": {
    name: "door",
    category: "objects",
    unicode: "_1f6aa",
    htmlEntity: "&#x1F6AA",
  },
  "🪑": {
    name: "chair",
    category: "objects",
    unicode: "_1fa91",
    htmlEntity: "&#x1FA91",
  },
  "🪞": {
    name: "mirror",
    category: "objects",
    unicode: "_1fa9e",
    htmlEntity: "&#x1FA9E",
  },
  "🛋": {
    name: "couch-and-lamp",
    category: "objects",
    unicode: "_1f6cb",
    htmlEntity: "&#x1F6CB",
  },
  "🛏": {
    name: "bed",
    category: "objects",
    unicode: "_1f6cf",
    htmlEntity: "&#x1F6CF",
  },
  "🛌": {
    name: "person-in-bed",
    category: "objects",
    unicode: "_1f6cc",
    htmlEntity: "&#x1F6CC",
  },
  "🛌🏻": {
    name: "person-in-bed-light-skin-tone",
    category: "diversity",
    unicode: "_1f6cc-1f3fb",
    htmlEntity: "&#x1F6CC;&#x1F3FB",
  },
  "🛌🏼": {
    name: "person-in-bed-medium-light-skin-tone",
    category: "diversity",
    unicode: "_1f6cc-1f3fc",
    htmlEntity: "&#x1F6CC;&#x1F3FC",
  },
  "🛌🏽": {
    name: "person-in-bed-medium-skin-tone",
    category: "diversity",
    unicode: "_1f6cc-1f3fd",
    htmlEntity: "&#x1F6CC;&#x1F3FD",
  },
  "🛌🏾": {
    name: "person-in-bed-medium-dark-skin-tone",
    category: "diversity",
    unicode: "_1f6cc-1f3fe",
    htmlEntity: "&#x1F6CC;&#x1F3FE",
  },
  "🛌🏿": {
    name: "person-in-bed-dark-skin-tone",
    category: "diversity",
    unicode: "_1f6cc-1f3ff",
    htmlEntity: "&#x1F6CC;&#x1F3FF",
  },
  "🧸": {
    name: "teddy-bear",
    category: "objects",
    unicode: "_1f9f8",
    htmlEntity: "&#x1F9F8",
  },
  "🖼": {
    name: "framed-picture",
    category: "objects",
    unicode: "_1f5bc",
    htmlEntity: "&#x1F5BC",
  },
  "🛍": {
    name: "shopping-bags",
    category: "objects",
    unicode: "_1f6cd",
    htmlEntity: "&#x1F6CD",
  },
  "🛒": {
    name: "shopping-cart",
    category: "objects",
    unicode: "_1f6d2",
    htmlEntity: "&#x1F6D2",
  },
  "🎁": {
    name: "wrapped-gift",
    category: "objects",
    unicode: "_1f381",
    htmlEntity: "&#x1F381",
  },
  "🎈": {
    name: "balloon",
    category: "objects",
    unicode: "_1f388",
    htmlEntity: "&#x1F388",
  },
  "🎏": {
    name: "carp-streamer",
    category: "objects",
    unicode: "_1f38f",
    htmlEntity: "&#x1F38F",
  },
  "🎀": {
    name: "ribbon",
    category: "objects",
    unicode: "_1f380",
    htmlEntity: "&#x1F380",
  },
  "🎊": {
    name: "confetti-ball",
    category: "objects",
    unicode: "_1f38a",
    htmlEntity: "&#x1F38A",
  },
  "🎉": {
    name: "party-popper",
    category: "objects",
    unicode: "_1f389",
    htmlEntity: "&#x1F389",
  },
  "🪅": {
    name: "piñata",
    category: "objects",
    unicode: "_1fa85",
    htmlEntity: "&#x1FA85",
  },
  "🪆": {
    name: "nesting-dolls",
    category: "objects",
    unicode: "_1fa86",
    htmlEntity: "&#x1FA86",
  },
  "🎎": {
    name: "japanese-dolls",
    category: "objects",
    unicode: "_1f38e",
    htmlEntity: "&#x1F38E",
  },
  "🏮": {
    name: "red-paper-lantern",
    category: "objects",
    unicode: "_1f3ee",
    htmlEntity: "&#x1F3EE",
  },
  "🎐": {
    name: "wind-chime",
    category: "objects",
    unicode: "_1f390",
    htmlEntity: "&#x1F390",
  },
  "🧧": {
    name: "red-envelope",
    category: "objects",
    unicode: "_1f9e7",
    htmlEntity: "&#x1F9E7",
  },
  "✉": {
    name: "envelope",
    category: "objects",
    unicode: "_2709",
    htmlEntity: "&#x2709",
  },
  "📩": {
    name: "envelope-with-arrow",
    category: "objects",
    unicode: "_1f4e9",
    htmlEntity: "&#x1F4E9",
  },
  "📨": {
    name: "incoming-envelope",
    category: "objects",
    unicode: "_1f4e8",
    htmlEntity: "&#x1F4E8",
  },
  "📧": {
    name: "e-mail",
    category: "objects",
    unicode: "_1f4e7",
    htmlEntity: "&#x1F4E7",
  },
  "💌": {
    name: "love-letter",
    category: "objects",
    unicode: "_1f48c",
    htmlEntity: "&#x1F48C",
  },
  "📥": {
    name: "inbox-tray",
    category: "objects",
    unicode: "_1f4e5",
    htmlEntity: "&#x1F4E5",
  },
  "📤": {
    name: "outbox-tray",
    category: "objects",
    unicode: "_1f4e4",
    htmlEntity: "&#x1F4E4",
  },
  "📦": {
    name: "package",
    category: "objects",
    unicode: "_1f4e6",
    htmlEntity: "&#x1F4E6",
  },
  "🏷": {
    name: "label",
    category: "objects",
    unicode: "_1f3f7",
    htmlEntity: "&#x1F3F7",
  },
  "📪": {
    name: "closed-mailbox-with-lowered-flag",
    category: "objects",
    unicode: "_1f4ea",
    htmlEntity: "&#x1F4EA",
  },
  "📫": {
    name: "closed-mailbox-with-raised-flag",
    category: "objects",
    unicode: "_1f4eb",
    htmlEntity: "&#x1F4EB",
  },
  "📬": {
    name: "open-mailbox-with-raised-flag",
    category: "objects",
    unicode: "_1f4ec",
    htmlEntity: "&#x1F4EC",
  },
  "📭": {
    name: "open-mailbox-with-lowered-flag",
    category: "objects",
    unicode: "_1f4ed",
    htmlEntity: "&#x1F4ED",
  },
  "📮": {
    name: "postbox",
    category: "objects",
    unicode: "_1f4ee",
    htmlEntity: "&#x1F4EE",
  },
  "📯": {
    name: "postal-horn",
    category: "objects",
    unicode: "_1f4ef",
    htmlEntity: "&#x1F4EF",
  },
  "🪧": {
    name: "placard",
    category: "objects",
    unicode: "_1faa7",
    htmlEntity: "&#x1FAA7",
  },
  "📜": {
    name: "scroll",
    category: "objects",
    unicode: "_1f4dc",
    htmlEntity: "&#x1F4DC",
  },
  "📃": {
    name: "page-with-curl",
    category: "objects",
    unicode: "_1f4c3",
    htmlEntity: "&#x1F4C3",
  },
  "📄": {
    name: "page-facing-up",
    category: "objects",
    unicode: "_1f4c4",
    htmlEntity: "&#x1F4C4",
  },
  "📑": {
    name: "bookmark-tabs",
    category: "objects",
    unicode: "_1f4d1",
    htmlEntity: "&#x1F4D1",
  },
  "🧾": {
    name: "receipt",
    category: "objects",
    unicode: "_1f9fe",
    htmlEntity: "&#x1F9FE",
  },
  "📊": {
    name: "bar-chart",
    category: "objects",
    unicode: "_1f4ca",
    htmlEntity: "&#x1F4CA",
  },
  "📈": {
    name: "chart-increasing",
    category: "objects",
    unicode: "_1f4c8",
    htmlEntity: "&#x1F4C8",
  },
  "📉": {
    name: "chart-decreasing",
    category: "objects",
    unicode: "_1f4c9",
    htmlEntity: "&#x1F4C9",
  },
  "🗒": {
    name: "spiral-notepad",
    category: "objects",
    unicode: "_1f5d2",
    htmlEntity: "&#x1F5D2",
  },
  "🗓": {
    name: "spiral-calendar",
    category: "objects",
    unicode: "_1f5d3",
    htmlEntity: "&#x1F5D3",
  },
  "📆": {
    name: "tear-off-calendar",
    category: "objects",
    unicode: "_1f4c6",
    htmlEntity: "&#x1F4C6",
  },
  "📅": {
    name: "calendar",
    category: "objects",
    unicode: "_1f4c5",
    htmlEntity: "&#x1F4C5",
  },
  "🗑": {
    name: "wastebasket",
    category: "objects",
    unicode: "_1f5d1",
    htmlEntity: "&#x1F5D1",
  },
  "📇": {
    name: "card-index",
    category: "objects",
    unicode: "_1f4c7",
    htmlEntity: "&#x1F4C7",
  },
  "🗃": {
    name: "card-file-box",
    category: "objects",
    unicode: "_1f5c3",
    htmlEntity: "&#x1F5C3",
  },
  "🗳": {
    name: "ballot-box-with-ballot",
    category: "objects",
    unicode: "_1f5f3",
    htmlEntity: "&#x1F5F3",
  },
  "🗄": {
    name: "file-cabinet",
    category: "objects",
    unicode: "_1f5c4",
    htmlEntity: "&#x1F5C4",
  },
  "📋": {
    name: "clipboard",
    category: "objects",
    unicode: "_1f4cb",
    htmlEntity: "&#x1F4CB",
  },
  "📁": {
    name: "file-folder",
    category: "objects",
    unicode: "_1f4c1",
    htmlEntity: "&#x1F4C1",
  },
  "📂": {
    name: "open-file-folder",
    category: "objects",
    unicode: "_1f4c2",
    htmlEntity: "&#x1F4C2",
  },
  "🗂": {
    name: "card-index-dividers",
    category: "objects",
    unicode: "_1f5c2",
    htmlEntity: "&#x1F5C2",
  },
  "🗞": {
    name: "rolled-up-newspaper",
    category: "objects",
    unicode: "_1f5de",
    htmlEntity: "&#x1F5DE",
  },
  "📰": {
    name: "newspaper",
    category: "objects",
    unicode: "_1f4f0",
    htmlEntity: "&#x1F4F0",
  },
  "📓": {
    name: "notebook",
    category: "objects",
    unicode: "_1f4d3",
    htmlEntity: "&#x1F4D3",
  },
  "📔": {
    name: "notebook-with-decorative-cover",
    category: "objects",
    unicode: "_1f4d4",
    htmlEntity: "&#x1F4D4",
  },
  "📒": {
    name: "ledger",
    category: "objects",
    unicode: "_1f4d2",
    htmlEntity: "&#x1F4D2",
  },
  "📕": {
    name: "closed-book",
    category: "objects",
    unicode: "_1f4d5",
    htmlEntity: "&#x1F4D5",
  },
  "📗": {
    name: "green-book",
    category: "objects",
    unicode: "_1f4d7",
    htmlEntity: "&#x1F4D7",
  },
  "📘": {
    name: "blue-book",
    category: "objects",
    unicode: "_1f4d8",
    htmlEntity: "&#x1F4D8",
  },
  "📙": {
    name: "orange-book",
    category: "objects",
    unicode: "_1f4d9",
    htmlEntity: "&#x1F4D9",
  },
  "📚": {
    name: "books",
    category: "objects",
    unicode: "_1f4da",
    htmlEntity: "&#x1F4DA",
  },
  "📖": {
    name: "open-book",
    category: "objects",
    unicode: "_1f4d6",
    htmlEntity: "&#x1F4D6",
  },
  "🔖": {
    name: "bookmark",
    category: "objects",
    unicode: "_1f516",
    htmlEntity: "&#x1F516",
  },
  "🧷": {
    name: "safety-pin",
    category: "objects",
    unicode: "_1f9f7",
    htmlEntity: "&#x1F9F7",
  },
  "🔗": {
    name: "link",
    category: "objects",
    unicode: "_1f517",
    htmlEntity: "&#x1F517",
  },
  "📎": {
    name: "paperclip",
    category: "objects",
    unicode: "_1f4ce",
    htmlEntity: "&#x1F4CE",
  },
  "🖇": {
    name: "linked-paperclips",
    category: "objects",
    unicode: "_1f587",
    htmlEntity: "&#x1F587",
  },
  "📐": {
    name: "triangular-ruler",
    category: "objects",
    unicode: "_1f4d0",
    htmlEntity: "&#x1F4D0",
  },
  "📏": {
    name: "straight-ruler",
    category: "objects",
    unicode: "_1f4cf",
    htmlEntity: "&#x1F4CF",
  },
  "🧮": {
    name: "abacus",
    category: "objects",
    unicode: "_1f9ee",
    htmlEntity: "&#x1F9EE",
  },
  "📌": {
    name: "pushpin",
    category: "objects",
    unicode: "_1f4cc",
    htmlEntity: "&#x1F4CC",
  },
  "📍": {
    name: "round-pushpin",
    category: "objects",
    unicode: "_1f4cd",
    htmlEntity: "&#x1F4CD",
  },
  "✂": {
    name: "scissors",
    category: "objects",
    unicode: "_2702",
    htmlEntity: "&#x2702",
  },
  "🖊": {
    name: "pen",
    category: "objects",
    unicode: "_1f58a",
    htmlEntity: "&#x1F58A",
  },
  "🖋": {
    name: "fountain-pen",
    category: "objects",
    unicode: "_1f58b",
    htmlEntity: "&#x1F58B",
  },
  "✒": {
    name: "black-nib",
    category: "objects",
    unicode: "_2712",
    htmlEntity: "&#x2712",
  },
  "🖌": {
    name: "paintbrush",
    category: "objects",
    unicode: "_1f58c",
    htmlEntity: "&#x1F58C",
  },
  "🖍": {
    name: "crayon",
    category: "objects",
    unicode: "_1f58d",
    htmlEntity: "&#x1F58D",
  },
  "📝": {
    name: "memo",
    category: "objects",
    unicode: "_1f4dd",
    htmlEntity: "&#x1F4DD",
  },
  "✏": {
    name: "pencil",
    category: "objects",
    unicode: "_270f",
    htmlEntity: "&#x270F",
  },
  "🔍": {
    name: "magnifying-glass-tilted-left",
    category: "objects",
    unicode: "_1f50d",
    htmlEntity: "&#x1F50D",
  },
  "🔎": {
    name: "magnifying-glass-tilted-right",
    category: "objects",
    unicode: "_1f50e",
    htmlEntity: "&#x1F50E",
  },
  "🔏": {
    name: "locked-with-pen",
    category: "objects",
    unicode: "_1f50f",
    htmlEntity: "&#x1F50F",
  },
  "🔐": {
    name: "locked-with-key",
    category: "objects",
    unicode: "_1f510",
    htmlEntity: "&#x1F510",
  },
  "🔒": {
    name: "locked",
    category: "objects",
    unicode: "_1f512",
    htmlEntity: "&#x1F512",
  },
  "🔓": {
    name: "unlocked",
    category: "objects",
    unicode: "_1f513",
    htmlEntity: "&#x1F513",
  },
};
