import { EmojiInformation } from "../types/emojiInformation";

export const SYMBOLS: EmojiInformation = {
  "0": {
    name: "digit-zero",
    category: "symbols",
    unicode: "_0030",
    htmlEntity: "&#x0030",
  },
  "1": {
    name: "digit-one",
    category: "symbols",
    unicode: "_0031",
    htmlEntity: "&#x0031",
  },
  "2": {
    name: "digit-two",
    category: "symbols",
    unicode: "_0032",
    htmlEntity: "&#x0032",
  },
  "3": {
    name: "digit-three",
    category: "symbols",
    unicode: "_0033",
    htmlEntity: "&#x0033",
  },
  "4": {
    name: "digit-four",
    category: "symbols",
    unicode: "_0034",
    htmlEntity: "&#x0034",
  },
  "5": {
    name: "digit-five",
    category: "symbols",
    unicode: "_0035",
    htmlEntity: "&#x0035",
  },
  "6": {
    name: "digit-six",
    category: "symbols",
    unicode: "_0036",
    htmlEntity: "&#x0036",
  },
  "7": {
    name: "digit-seven",
    category: "symbols",
    unicode: "_0037",
    htmlEntity: "&#x0037",
  },
  "8": {
    name: "digit-eight",
    category: "symbols",
    unicode: "_0038",
    htmlEntity: "&#x0038",
  },
  "9": {
    name: "digit-nine",
    category: "symbols",
    unicode: "_0039",
    htmlEntity: "&#x0039",
  },
  "❤": {
    name: "red-heart",
    category: "symbols",
    unicode: "_2764",
    htmlEntity: "&#x2764",
  },
  "🧡": {
    name: "orange-heart",
    category: "symbols",
    unicode: "_1f9e1",
    htmlEntity: "&#x1F9E1",
  },
  "💛": {
    name: "yellow-heart",
    category: "symbols",
    unicode: "_1f49b",
    htmlEntity: "&#x1F49B",
  },
  "💚": {
    name: "green-heart",
    category: "symbols",
    unicode: "_1f49a",
    htmlEntity: "&#x1F49A",
  },
  "💙": {
    name: "blue-heart",
    category: "symbols",
    unicode: "_1f499",
    htmlEntity: "&#x1F499",
  },
  "💜": {
    name: "purple-heart",
    category: "symbols",
    unicode: "_1f49c",
    htmlEntity: "&#x1F49C",
  },
  "🖤": {
    name: "black-heart",
    category: "symbols",
    unicode: "_1f5a4",
    htmlEntity: "&#x1F5A4",
  },
  "🤎": {
    name: "brown-heart",
    category: "symbols",
    unicode: "_1f90e",
    htmlEntity: "&#x1F90E",
  },
  "🤍": {
    name: "white-heart",
    category: "symbols",
    unicode: "_1f90d",
    htmlEntity: "&#x1F90D",
  },
  "💔": {
    name: "broken-heart",
    category: "symbols",
    unicode: "_1f494",
    htmlEntity: "&#x1F494",
  },
  "❣": {
    name: "heart-exclamation",
    category: "symbols",
    unicode: "_2763",
    htmlEntity: "&#x2763",
  },
  "💕": {
    name: "two-hearts",
    category: "symbols",
    unicode: "_1f495",
    htmlEntity: "&#x1F495",
  },
  "💞": {
    name: "revolving-hearts",
    category: "symbols",
    unicode: "_1f49e",
    htmlEntity: "&#x1F49E",
  },
  "💓": {
    name: "beating-heart",
    category: "symbols",
    unicode: "_1f493",
    htmlEntity: "&#x1F493",
  },
  "💗": {
    name: "growing-heart",
    category: "symbols",
    unicode: "_1f497",
    htmlEntity: "&#x1F497",
  },
  "💖": {
    name: "sparkling-heart",
    category: "symbols",
    unicode: "_1f496",
    htmlEntity: "&#x1F496",
  },
  "💘": {
    name: "heart-with-arrow",
    category: "symbols",
    unicode: "_1f498",
    htmlEntity: "&#x1F498",
  },
  "💝": {
    name: "heart-with-ribbon",
    category: "symbols",
    unicode: "_1f49d",
    htmlEntity: "&#x1F49D",
  },
  "❤🩹": {
    name: "mending-heart",
    category: "symbols",
    unicode: "_2764-1fa79",
    htmlEntity: "&#x2764;&#x1FA79",
  },
  "❤🔥": {
    name: "heart-on-fire",
    category: "symbols",
    unicode: "_2764-1f525",
    htmlEntity: "&#x2764;&#x1F525",
  },
  "💟": {
    name: "heart-decoration",
    category: "symbols",
    unicode: "_1f49f",
    htmlEntity: "&#x1F49F",
  },
  "☮": {
    name: "peace-symbol",
    category: "symbols",
    unicode: "_262e",
    htmlEntity: "&#x262E",
  },
  "✝": {
    name: "latin-cross",
    category: "symbols",
    unicode: "_271d",
    htmlEntity: "&#x271D",
  },
  "☪": {
    name: "star-and-crescent",
    category: "symbols",
    unicode: "_262a",
    htmlEntity: "&#x262A",
  },
  "🕉": {
    name: "om",
    category: "symbols",
    unicode: "_1f549",
    htmlEntity: "&#x1F549",
  },
  "☸": {
    name: "wheel-of-dharma",
    category: "symbols",
    unicode: "_2638",
    htmlEntity: "&#x2638",
  },
  "✡": {
    name: "star-of-david",
    category: "symbols",
    unicode: "_2721",
    htmlEntity: "&#x2721",
  },
  "🔯": {
    name: "dotted-six-pointed-star",
    category: "symbols",
    unicode: "_1f52f",
    htmlEntity: "&#x1F52F",
  },
  "🕎": {
    name: "menorah",
    category: "symbols",
    unicode: "_1f54e",
    htmlEntity: "&#x1F54E",
  },
  "☯": {
    name: "yin-yang",
    category: "symbols",
    unicode: "_262f",
    htmlEntity: "&#x262F",
  },
  "☦": {
    name: "orthodox-cross",
    category: "symbols",
    unicode: "_2626",
    htmlEntity: "&#x2626",
  },
  "🛐": {
    name: "place-of-worship",
    category: "symbols",
    unicode: "_1f6d0",
    htmlEntity: "&#x1F6D0",
  },
  "⛎": {
    name: "ophiuchus",
    category: "symbols",
    unicode: "_26ce",
    htmlEntity: "&#x26CE",
  },
  "♈": {
    name: "aries",
    category: "symbols",
    unicode: "_2648",
    htmlEntity: "&#x2648",
  },
  "♉": {
    name: "taurus",
    category: "symbols",
    unicode: "_2649",
    htmlEntity: "&#x2649",
  },
  "♊": {
    name: "gemini",
    category: "symbols",
    unicode: "_264a",
    htmlEntity: "&#x264A",
  },
  "♋": {
    name: "cancer",
    category: "symbols",
    unicode: "_264b",
    htmlEntity: "&#x264B",
  },
  "♌": {
    name: "leo",
    category: "symbols",
    unicode: "_264c",
    htmlEntity: "&#x264C",
  },
  "♍": {
    name: "virgo",
    category: "symbols",
    unicode: "_264d",
    htmlEntity: "&#x264D",
  },
  "♎": {
    name: "libra",
    category: "symbols",
    unicode: "_264e",
    htmlEntity: "&#x264E",
  },
  "♏": {
    name: "scorpio",
    category: "symbols",
    unicode: "_264f",
    htmlEntity: "&#x264F",
  },
  "♐": {
    name: "sagittarius",
    category: "symbols",
    unicode: "_2650",
    htmlEntity: "&#x2650",
  },
  "♑": {
    name: "capricorn",
    category: "symbols",
    unicode: "_2651",
    htmlEntity: "&#x2651",
  },
  "♒": {
    name: "aquarius",
    category: "symbols",
    unicode: "_2652",
    htmlEntity: "&#x2652",
  },
  "♓": {
    name: "pisces",
    category: "symbols",
    unicode: "_2653",
    htmlEntity: "&#x2653",
  },
  "🆔": {
    name: "id-button",
    category: "symbols",
    unicode: "_1f194",
    htmlEntity: "&#x1F194",
  },
  "⚛": {
    name: "atom-symbol",
    category: "symbols",
    unicode: "_269b",
    htmlEntity: "&#x269B",
  },
  "🉑": {
    name: "japanese-“acceptable”-button",
    category: "symbols",
    unicode: "_1f251",
    htmlEntity: "&#x1F251",
  },
  "☢": {
    name: "radioactive",
    category: "symbols",
    unicode: "_2622",
    htmlEntity: "&#x2622",
  },
  "☣": {
    name: "biohazard",
    category: "symbols",
    unicode: "_2623",
    htmlEntity: "&#x2623",
  },
  "📴": {
    name: "mobile-phone-off",
    category: "symbols",
    unicode: "_1f4f4",
    htmlEntity: "&#x1F4F4",
  },
  "📳": {
    name: "vibration-mode",
    category: "symbols",
    unicode: "_1f4f3",
    htmlEntity: "&#x1F4F3",
  },
  "🈶": {
    name: "japanese-“not-free-of-charge”-button",
    category: "symbols",
    unicode: "_1f236",
    htmlEntity: "&#x1F236",
  },
  "🈚": {
    name: "japanese-“free-of-charge”-button",
    category: "symbols",
    unicode: "_1f21a",
    htmlEntity: "&#x1F21A",
  },
  "🈸": {
    name: "japanese-“application”-button",
    category: "symbols",
    unicode: "_1f238",
    htmlEntity: "&#x1F238",
  },
  "🈺": {
    name: "japanese-“open-for-business”-button",
    category: "symbols",
    unicode: "_1f23a",
    htmlEntity: "&#x1F23A",
  },
  "🈷": {
    name: "japanese-“monthly-amount”-button",
    category: "symbols",
    unicode: "_1f237",
    htmlEntity: "&#x1F237",
  },
  "✴": {
    name: "eight-pointed-star",
    category: "symbols",
    unicode: "_2734",
    htmlEntity: "&#x2734",
  },
  "🆚": {
    name: "vs-button",
    category: "symbols",
    unicode: "_1f19a",
    htmlEntity: "&#x1F19A",
  },
  "💮": {
    name: "white-flower",
    category: "symbols",
    unicode: "_1f4ae",
    htmlEntity: "&#x1F4AE",
  },
  "🉐": {
    name: "japanese-“bargain”-button",
    category: "symbols",
    unicode: "_1f250",
    htmlEntity: "&#x1F250",
  },
  "㊙": {
    name: "japanese-“secret”-button",
    category: "symbols",
    unicode: "_3299",
    htmlEntity: "&#x3299",
  },
  "㊗": {
    name: "japanese-“congratulations”-button",
    category: "symbols",
    unicode: "_3297",
    htmlEntity: "&#x3297",
  },
  "🈴": {
    name: "japanese-“passing-grade”-button",
    category: "symbols",
    unicode: "_1f234",
    htmlEntity: "&#x1F234",
  },
  "🈵": {
    name: "japanese-“no-vacancy”-button",
    category: "symbols",
    unicode: "_1f235",
    htmlEntity: "&#x1F235",
  },
  "🈹": {
    name: "japanese-“discount”-button",
    category: "symbols",
    unicode: "_1f239",
    htmlEntity: "&#x1F239",
  },
  "🈲": {
    name: "japanese-“prohibited”-button",
    category: "symbols",
    unicode: "_1f232",
    htmlEntity: "&#x1F232",
  },
  "🅰": {
    name: "a-button-blood-type",
    category: "symbols",
    unicode: "_1f170",
    htmlEntity: "&#x1F170",
  },
  "🅱": {
    name: "b-button-blood-type",
    category: "symbols",
    unicode: "_1f171",
    htmlEntity: "&#x1F171",
  },
  "🆎": {
    name: "ab-button-blood-type",
    category: "symbols",
    unicode: "_1f18e",
    htmlEntity: "&#x1F18E",
  },
  "🆑": {
    name: "cl-button",
    category: "symbols",
    unicode: "_1f191",
    htmlEntity: "&#x1F191",
  },
  "🅾": {
    name: "o-button-blood-type",
    category: "symbols",
    unicode: "_1f17e",
    htmlEntity: "&#x1F17E",
  },
  "🆘": {
    name: "sos-button",
    category: "symbols",
    unicode: "_1f198",
    htmlEntity: "&#x1F198",
  },
  "❌": {
    name: "cross-mark",
    category: "symbols",
    unicode: "_274c",
    htmlEntity: "&#x274C",
  },
  "⭕": {
    name: "hollow-red-circle",
    category: "symbols",
    unicode: "_2b55",
    htmlEntity: "&#x2B55",
  },
  "🛑": {
    name: "stop-sign",
    category: "symbols",
    unicode: "_1f6d1",
    htmlEntity: "&#x1F6D1",
  },
  "⛔": {
    name: "no-entry",
    category: "symbols",
    unicode: "_26d4",
    htmlEntity: "&#x26D4",
  },
  "📛": {
    name: "name-badge",
    category: "symbols",
    unicode: "_1f4db",
    htmlEntity: "&#x1F4DB",
  },
  "🚫": {
    name: "prohibited",
    category: "symbols",
    unicode: "_1f6ab",
    htmlEntity: "&#x1F6AB",
  },
  "💯": {
    name: "hundred-points",
    category: "symbols",
    unicode: "_1f4af",
    htmlEntity: "&#x1F4AF",
  },
  "💢": {
    name: "anger-symbol",
    category: "symbols",
    unicode: "_1f4a2",
    htmlEntity: "&#x1F4A2",
  },
  "♨": {
    name: "hot-springs",
    category: "symbols",
    unicode: "_2668",
    htmlEntity: "&#x2668",
  },
  "🚷": {
    name: "no-pedestrians",
    category: "symbols",
    unicode: "_1f6b7",
    htmlEntity: "&#x1F6B7",
  },
  "🚯": {
    name: "no-littering",
    category: "symbols",
    unicode: "_1f6af",
    htmlEntity: "&#x1F6AF",
  },
  "🚳": {
    name: "no-bicycles",
    category: "symbols",
    unicode: "_1f6b3",
    htmlEntity: "&#x1F6B3",
  },
  "🚱": {
    name: "non-potable-water",
    category: "symbols",
    unicode: "_1f6b1",
    htmlEntity: "&#x1F6B1",
  },
  "🔞": {
    name: "no-one-under-eighteen",
    category: "symbols",
    unicode: "_1f51e",
    htmlEntity: "&#x1F51E",
  },
  "📵": {
    name: "no-mobile-phones",
    category: "symbols",
    unicode: "_1f4f5",
    htmlEntity: "&#x1F4F5",
  },
  "🚭": {
    name: "no-smoking",
    category: "symbols",
    unicode: "_1f6ad",
    htmlEntity: "&#x1F6AD",
  },
  "❗": {
    name: "exclamation-mark",
    category: "symbols",
    unicode: "_2757",
    htmlEntity: "&#x2757",
  },
  "❕": {
    name: "white-exclamation-mark",
    category: "symbols",
    unicode: "_2755",
    htmlEntity: "&#x2755",
  },
  "❓": {
    name: "question-mark",
    category: "symbols",
    unicode: "_2753",
    htmlEntity: "&#x2753",
  },
  "❔": {
    name: "white-question-mark",
    category: "symbols",
    unicode: "_2754",
    htmlEntity: "&#x2754",
  },
  "‼": {
    name: "double-exclamation-mark",
    category: "symbols",
    unicode: "_203c",
    htmlEntity: "&#x203C",
  },
  "⁉": {
    name: "exclamation-question-mark",
    category: "symbols",
    unicode: "_2049",
    htmlEntity: "&#x2049",
  },
  "🔅": {
    name: "dim-button",
    category: "symbols",
    unicode: "_1f505",
    htmlEntity: "&#x1F505",
  },
  "🔆": {
    name: "bright-button",
    category: "symbols",
    unicode: "_1f506",
    htmlEntity: "&#x1F506",
  },
  "〽": {
    name: "part-alternation-mark",
    category: "symbols",
    unicode: "_303d",
    htmlEntity: "&#x303D",
  },
  "⚠": {
    name: "warning",
    category: "symbols",
    unicode: "_26a0",
    htmlEntity: "&#x26A0",
  },
  "🚸": {
    name: "children-crossing",
    category: "symbols",
    unicode: "_1f6b8",
    htmlEntity: "&#x1F6B8",
  },
  "🔱": {
    name: "trident-emblem",
    category: "symbols",
    unicode: "_1f531",
    htmlEntity: "&#x1F531",
  },
  "⚜": {
    name: "fleur-de-lis",
    category: "symbols",
    unicode: "_269c",
    htmlEntity: "&#x269C",
  },
  "🔰": {
    name: "japanese-symbol-for-beginner",
    category: "symbols",
    unicode: "_1f530",
    htmlEntity: "&#x1F530",
  },
  "♻": {
    name: "recycling-symbol",
    category: "symbols",
    unicode: "_267b",
    htmlEntity: "&#x267B",
  },
  "✅": {
    name: "check-mark-button",
    category: "symbols",
    unicode: "_2705",
    htmlEntity: "&#x2705",
  },
  "🈯": {
    name: "japanese-“reserved”-button",
    category: "symbols",
    unicode: "_1f22f",
    htmlEntity: "&#x1F22F",
  },
  "💹": {
    name: "chart-increasing-with-yen",
    category: "symbols",
    unicode: "_1f4b9",
    htmlEntity: "&#x1F4B9",
  },
  "❇": {
    name: "sparkle",
    category: "symbols",
    unicode: "_2747",
    htmlEntity: "&#x2747",
  },
  "✳": {
    name: "eight-spoked-asterisk",
    category: "symbols",
    unicode: "_2733",
    htmlEntity: "&#x2733",
  },
  "❎": {
    name: "cross-mark-button",
    category: "symbols",
    unicode: "_274e",
    htmlEntity: "&#x274E",
  },
  "🌐": {
    name: "globe-with-meridians",
    category: "symbols",
    unicode: "_1f310",
    htmlEntity: "&#x1F310",
  },
  "💠": {
    name: "diamond-with-a-dot",
    category: "symbols",
    unicode: "_1f4a0",
    htmlEntity: "&#x1F4A0",
  },
  "Ⓜ": {
    name: "circled-m",
    category: "symbols",
    unicode: "_24c2",
    htmlEntity: "&#x24C2",
  },
  "🌀": {
    name: "cyclone",
    category: "symbols",
    unicode: "_1f300",
    htmlEntity: "&#x1F300",
  },
  "💤": {
    name: "zzz",
    category: "symbols",
    unicode: "_1f4a4",
    htmlEntity: "&#x1F4A4",
  },
  "🏧": {
    name: "atm-sign",
    category: "symbols",
    unicode: "_1f3e7",
    htmlEntity: "&#x1F3E7",
  },
  "🚾": {
    name: "water-closet",
    category: "symbols",
    unicode: "_1f6be",
    htmlEntity: "&#x1F6BE",
  },
  "♿": {
    name: "wheelchair-symbol",
    category: "symbols",
    unicode: "_267f",
    htmlEntity: "&#x267F",
  },
  "🅿": {
    name: "p-button",
    category: "symbols",
    unicode: "_1f17f",
    htmlEntity: "&#x1F17F",
  },
  "🈳": {
    name: "japanese-“vacancy”-button",
    category: "symbols",
    unicode: "_1f233",
    htmlEntity: "&#x1F233",
  },
  "🈂": {
    name: "japanese-“service-charge”-button",
    category: "symbols",
    unicode: "_1f202",
    htmlEntity: "&#x1F202",
  },
  "🛂": {
    name: "passport-control",
    category: "symbols",
    unicode: "_1f6c2",
    htmlEntity: "&#x1F6C2",
  },
  "🛃": {
    name: "customs",
    category: "symbols",
    unicode: "_1f6c3",
    htmlEntity: "&#x1F6C3",
  },
  "🛄": {
    name: "baggage-claim",
    category: "symbols",
    unicode: "_1f6c4",
    htmlEntity: "&#x1F6C4",
  },
  "🛅": {
    name: "left-luggage",
    category: "symbols",
    unicode: "_1f6c5",
    htmlEntity: "&#x1F6C5",
  },
  "🛗": {
    name: "elevator",
    category: "symbols",
    unicode: "_1f6d7",
    htmlEntity: "&#x1F6D7",
  },
  "🚹": {
    name: "men’s-room",
    category: "symbols",
    unicode: "_1f6b9",
    htmlEntity: "&#x1F6B9",
  },
  "🚺": {
    name: "women’s-room",
    category: "symbols",
    unicode: "_1f6ba",
    htmlEntity: "&#x1F6BA",
  },
  "🚼": {
    name: "baby-symbol",
    category: "symbols",
    unicode: "_1f6bc",
    htmlEntity: "&#x1F6BC",
  },
  "🚻": {
    name: "restroom",
    category: "symbols",
    unicode: "_1f6bb",
    htmlEntity: "&#x1F6BB",
  },
  "🚮": {
    name: "litter-in-bin-sign",
    category: "symbols",
    unicode: "_1f6ae",
    htmlEntity: "&#x1F6AE",
  },
  "🎦": {
    name: "cinema",
    category: "symbols",
    unicode: "_1f3a6",
    htmlEntity: "&#x1F3A6",
  },
  "📶": {
    name: "antenna-bars",
    category: "symbols",
    unicode: "_1f4f6",
    htmlEntity: "&#x1F4F6",
  },
  "🈁": {
    name: "japanese-“here”-button",
    category: "symbols",
    unicode: "_1f201",
    htmlEntity: "&#x1F201",
  },
  "🔣": {
    name: "input-symbols",
    category: "symbols",
    unicode: "_1f523",
    htmlEntity: "&#x1F523",
  },
  ℹ: {
    name: "information",
    category: "symbols",
    unicode: "_2139",
    htmlEntity: "&#x2139",
  },
  "🔤": {
    name: "input-latin-letters",
    category: "symbols",
    unicode: "_1f524",
    htmlEntity: "&#x1F524",
  },
  "🔡": {
    name: "input-latin-lowercase",
    category: "symbols",
    unicode: "_1f521",
    htmlEntity: "&#x1F521",
  },
  "🔠": {
    name: "input-latin-uppercase",
    category: "symbols",
    unicode: "_1f520",
    htmlEntity: "&#x1F520",
  },
  "🆖": {
    name: "ng-button",
    category: "symbols",
    unicode: "_1f196",
    htmlEntity: "&#x1F196",
  },
  "🆗": {
    name: "ok-button",
    category: "symbols",
    unicode: "_1f197",
    htmlEntity: "&#x1F197",
  },
  "🆙": {
    name: "up!-button",
    category: "symbols",
    unicode: "_1f199",
    htmlEntity: "&#x1F199",
  },
  "🆒": {
    name: "cool-button",
    category: "symbols",
    unicode: "_1f192",
    htmlEntity: "&#x1F192",
  },
  "🆕": {
    name: "new-button",
    category: "symbols",
    unicode: "_1f195",
    htmlEntity: "&#x1F195",
  },
  "🆓": {
    name: "free-button",
    category: "symbols",
    unicode: "_1f193",
    htmlEntity: "&#x1F193",
  },
  "0⃣": {
    name: "keycap-0",
    category: "symbols",
    unicode: "_0030-20e3",
    htmlEntity: "&#x0030;&#x20E3",
  },
  "1⃣": {
    name: "keycap-1",
    category: "symbols",
    unicode: "_0031-20e3",
    htmlEntity: "&#x0031;&#x20E3",
  },
  "2⃣": {
    name: "keycap-2",
    category: "symbols",
    unicode: "_0032-20e3",
    htmlEntity: "&#x0032;&#x20E3",
  },
  "3⃣": {
    name: "keycap-3",
    category: "symbols",
    unicode: "_0033-20e3",
    htmlEntity: "&#x0033;&#x20E3",
  },
  "4⃣": {
    name: "keycap-4",
    category: "symbols",
    unicode: "_0034-20e3",
    htmlEntity: "&#x0034;&#x20E3",
  },
  "5⃣": {
    name: "keycap-5",
    category: "symbols",
    unicode: "_0035-20e3",
    htmlEntity: "&#x0035;&#x20E3",
  },
  "6⃣": {
    name: "keycap-6",
    category: "symbols",
    unicode: "_0036-20e3",
    htmlEntity: "&#x0036;&#x20E3",
  },
  "7⃣": {
    name: "keycap-7",
    category: "symbols",
    unicode: "_0037-20e3",
    htmlEntity: "&#x0037;&#x20E3",
  },
  "8⃣": {
    name: "keycap-8",
    category: "symbols",
    unicode: "_0038-20e3",
    htmlEntity: "&#x0038;&#x20E3",
  },
  "9⃣": {
    name: "keycap-9",
    category: "symbols",
    unicode: "_0039-20e3",
    htmlEntity: "&#x0039;&#x20E3",
  },
  "🔟": {
    name: "keycap-10",
    category: "symbols",
    unicode: "_1f51f",
    htmlEntity: "&#x1F51F",
  },
  "🔢": {
    name: "input-numbers",
    category: "symbols",
    unicode: "_1f522",
    htmlEntity: "&#x1F522",
  },
  "#⃣": {
    name: "keycap-#",
    category: "symbols",
    unicode: "_0023-20e3",
    htmlEntity: "&#x0023;&#x20E3",
  },
  "*⃣": {
    name: "keycap-*",
    category: "symbols",
    unicode: "_002a-20e3",
    htmlEntity: "&#x002A;&#x20E3",
  },
  "⏏": {
    name: "eject-button",
    category: "symbols",
    unicode: "_23cf",
    htmlEntity: "&#x23CF",
  },
  "▶": {
    name: "play-button",
    category: "symbols",
    unicode: "_25b6",
    htmlEntity: "&#x25B6",
  },
  "⏸": {
    name: "pause-button",
    category: "symbols",
    unicode: "_23f8",
    htmlEntity: "&#x23F8",
  },
  "⏯": {
    name: "play-or-pause-button",
    category: "symbols",
    unicode: "_23ef",
    htmlEntity: "&#x23EF",
  },
  "⏹": {
    name: "stop-button",
    category: "symbols",
    unicode: "_23f9",
    htmlEntity: "&#x23F9",
  },
  "⏺": {
    name: "record-button",
    category: "symbols",
    unicode: "_23fa",
    htmlEntity: "&#x23FA",
  },
  "⏭": {
    name: "next-track-button",
    category: "symbols",
    unicode: "_23ed",
    htmlEntity: "&#x23ED",
  },
  "⏮": {
    name: "last-track-button",
    category: "symbols",
    unicode: "_23ee",
    htmlEntity: "&#x23EE",
  },
  "⏩": {
    name: "fast-forward-button",
    category: "symbols",
    unicode: "_23e9",
    htmlEntity: "&#x23E9",
  },
  "⏪": {
    name: "fast-reverse-button",
    category: "symbols",
    unicode: "_23ea",
    htmlEntity: "&#x23EA",
  },
  "⏫": {
    name: "fast-up-button",
    category: "symbols",
    unicode: "_23eb",
    htmlEntity: "&#x23EB",
  },
  "⏬": {
    name: "fast-down-button",
    category: "symbols",
    unicode: "_23ec",
    htmlEntity: "&#x23EC",
  },
  "◀": {
    name: "reverse-button",
    category: "symbols",
    unicode: "_25c0",
    htmlEntity: "&#x25C0",
  },
  "🔼": {
    name: "upwards-button",
    category: "symbols",
    unicode: "_1f53c",
    htmlEntity: "&#x1F53C",
  },
  "🔽": {
    name: "downwards-button",
    category: "symbols",
    unicode: "_1f53d",
    htmlEntity: "&#x1F53D",
  },
  "➡": {
    name: "right-arrow",
    category: "symbols",
    unicode: "_27a1",
    htmlEntity: "&#x27A1",
  },
  "⬅": {
    name: "left-arrow",
    category: "symbols",
    unicode: "_2b05",
    htmlEntity: "&#x2B05",
  },
  "⬆": {
    name: "up-arrow",
    category: "symbols",
    unicode: "_2b06",
    htmlEntity: "&#x2B06",
  },
  "⬇": {
    name: "down-arrow",
    category: "symbols",
    unicode: "_2b07",
    htmlEntity: "&#x2B07",
  },
  "↗": {
    name: "up-right-arrow",
    category: "symbols",
    unicode: "_2197",
    htmlEntity: "&#x2197",
  },
  "↘": {
    name: "down-right-arrow",
    category: "symbols",
    unicode: "_2198",
    htmlEntity: "&#x2198",
  },
  "↙": {
    name: "down-left-arrow",
    category: "symbols",
    unicode: "_2199",
    htmlEntity: "&#x2199",
  },
  "↖": {
    name: "up-left-arrow",
    category: "symbols",
    unicode: "_2196",
    htmlEntity: "&#x2196",
  },
  "↕": {
    name: "up-down-arrow",
    category: "symbols",
    unicode: "_2195",
    htmlEntity: "&#x2195",
  },
  "↔": {
    name: "left-right-arrow",
    category: "symbols",
    unicode: "_2194",
    htmlEntity: "&#x2194",
  },
  "↪": {
    name: "left-arrow-curving-right",
    category: "symbols",
    unicode: "_21aa",
    htmlEntity: "&#x21AA",
  },
  "↩": {
    name: "right-arrow-curving-left",
    category: "symbols",
    unicode: "_21a9",
    htmlEntity: "&#x21A9",
  },
  "⤴": {
    name: "right-arrow-curving-up",
    category: "symbols",
    unicode: "_2934",
    htmlEntity: "&#x2934",
  },
  "⤵": {
    name: "right-arrow-curving-down",
    category: "symbols",
    unicode: "_2935",
    htmlEntity: "&#x2935",
  },
  "🔀": {
    name: "shuffle-tracks-button",
    category: "symbols",
    unicode: "_1f500",
    htmlEntity: "&#x1F500",
  },
  "🔁": {
    name: "repeat-button",
    category: "symbols",
    unicode: "_1f501",
    htmlEntity: "&#x1F501",
  },
  "🔂": {
    name: "repeat-single-button",
    category: "symbols",
    unicode: "_1f502",
    htmlEntity: "&#x1F502",
  },
  "🔄": {
    name: "counterclockwise-arrows-button",
    category: "symbols",
    unicode: "_1f504",
    htmlEntity: "&#x1F504",
  },
  "🔃": {
    name: "clockwise-vertical-arrows",
    category: "symbols",
    unicode: "_1f503",
    htmlEntity: "&#x1F503",
  },
  "🎵": {
    name: "musical-note",
    category: "symbols",
    unicode: "_1f3b5",
    htmlEntity: "&#x1F3B5",
  },
  "🎶": {
    name: "musical-notes",
    category: "symbols",
    unicode: "_1f3b6",
    htmlEntity: "&#x1F3B6",
  },
  "➕": {
    name: "plus-sign",
    category: "symbols",
    unicode: "_2795",
    htmlEntity: "&#x2795",
  },
  "➖": {
    name: "minus-sign",
    category: "symbols",
    unicode: "_2796",
    htmlEntity: "&#x2796",
  },
  "➗": {
    name: "division-sign",
    category: "symbols",
    unicode: "_2797",
    htmlEntity: "&#x2797",
  },
  "✖": {
    name: "multiplication-sign",
    category: "symbols",
    unicode: "_2716",
    htmlEntity: "&#x2716",
  },
  "♾": {
    name: "infinity",
    category: "symbols",
    unicode: "_267e",
    htmlEntity: "&#x267E",
  },
  "💲": {
    name: "heavy-dollar-sign",
    category: "symbols",
    unicode: "_1f4b2",
    htmlEntity: "&#x1F4B2",
  },
  "💱": {
    name: "currency-exchange",
    category: "symbols",
    unicode: "_1f4b1",
    htmlEntity: "&#x1F4B1",
  },
  "™": {
    name: "trade-mark",
    category: "symbols",
    unicode: "_2122",
    htmlEntity: "&#x2122",
  },
  "©": {
    name: "copyright",
    category: "symbols",
    unicode: "_00a9",
    htmlEntity: "&#x00A9",
  },
  "®": {
    name: "registered",
    category: "symbols",
    unicode: "_00ae",
    htmlEntity: "&#x00AE",
  },
  "〰": {
    name: "wavy-dash",
    category: "symbols",
    unicode: "_3030",
    htmlEntity: "&#x3030",
  },
  "➰": {
    name: "curly-loop",
    category: "symbols",
    unicode: "_27b0",
    htmlEntity: "&#x27B0",
  },
  "➿": {
    name: "double-curly-loop",
    category: "symbols",
    unicode: "_27bf",
    htmlEntity: "&#x27BF",
  },
  "🔚": {
    name: "end-arrow",
    category: "symbols",
    unicode: "_1f51a",
    htmlEntity: "&#x1F51A",
  },
  "🔙": {
    name: "back-arrow",
    category: "symbols",
    unicode: "_1f519",
    htmlEntity: "&#x1F519",
  },
  "🔛": {
    name: "on!-arrow",
    category: "symbols",
    unicode: "_1f51b",
    htmlEntity: "&#x1F51B",
  },
  "🔝": {
    name: "top-arrow",
    category: "symbols",
    unicode: "_1f51d",
    htmlEntity: "&#x1F51D",
  },
  "🔜": {
    name: "soon-arrow",
    category: "symbols",
    unicode: "_1f51c",
    htmlEntity: "&#x1F51C",
  },
  "✔": {
    name: "check-mark",
    category: "symbols",
    unicode: "_2714",
    htmlEntity: "&#x2714",
  },
  "☑": {
    name: "check-box-with-check",
    category: "symbols",
    unicode: "_2611",
    htmlEntity: "&#x2611",
  },
  "🔘": {
    name: "radio-button",
    category: "symbols",
    unicode: "_1f518",
    htmlEntity: "&#x1F518",
  },
  "⚪": {
    name: "white-circle",
    category: "symbols",
    unicode: "_26aa",
    htmlEntity: "&#x26AA",
  },
  "⚫": {
    name: "black-circle",
    category: "symbols",
    unicode: "_26ab",
    htmlEntity: "&#x26AB",
  },
  "🔴": {
    name: "red-circle",
    category: "symbols",
    unicode: "_1f534",
    htmlEntity: "&#x1F534",
  },
  "🔵": {
    name: "blue-circle",
    category: "symbols",
    unicode: "_1f535",
    htmlEntity: "&#x1F535",
  },
  "🟤": {
    name: "brown-circle",
    category: "symbols",
    unicode: "_1f7e4",
    htmlEntity: "&#x1F7E4",
  },
  "🟣": {
    name: "purple-circle",
    category: "symbols",
    unicode: "_1f7e3",
    htmlEntity: "&#x1F7E3",
  },
  "🟢": {
    name: "green-circle",
    category: "symbols",
    unicode: "_1f7e2",
    htmlEntity: "&#x1F7E2",
  },
  "🟡": {
    name: "yellow-circle",
    category: "symbols",
    unicode: "_1f7e1",
    htmlEntity: "&#x1F7E1",
  },
  "🟠": {
    name: "orange-circle",
    category: "symbols",
    unicode: "_1f7e0",
    htmlEntity: "&#x1F7E0",
  },
  "🔺": {
    name: "red-triangle-pointed-up",
    category: "symbols",
    unicode: "_1f53a",
    htmlEntity: "&#x1F53A",
  },
  "🔻": {
    name: "red-triangle-pointed-down",
    category: "symbols",
    unicode: "_1f53b",
    htmlEntity: "&#x1F53B",
  },
  "🔸": {
    name: "small-orange-diamond",
    category: "symbols",
    unicode: "_1f538",
    htmlEntity: "&#x1F538",
  },
  "🔹": {
    name: "small-blue-diamond",
    category: "symbols",
    unicode: "_1f539",
    htmlEntity: "&#x1F539",
  },
  "🔶": {
    name: "large-orange-diamond",
    category: "symbols",
    unicode: "_1f536",
    htmlEntity: "&#x1F536",
  },
  "🔷": {
    name: "large-blue-diamond",
    category: "symbols",
    unicode: "_1f537",
    htmlEntity: "&#x1F537",
  },
  "🔳": {
    name: "white-square-button",
    category: "symbols",
    unicode: "_1f533",
    htmlEntity: "&#x1F533",
  },
  "🔲": {
    name: "black-square-button",
    category: "symbols",
    unicode: "_1f532",
    htmlEntity: "&#x1F532",
  },
  "▪": {
    name: "black-small-square",
    category: "symbols",
    unicode: "_25aa",
    htmlEntity: "&#x25AA",
  },
  "▫": {
    name: "white-small-square",
    category: "symbols",
    unicode: "_25ab",
    htmlEntity: "&#x25AB",
  },
  "◾": {
    name: "black-medium-small-square",
    category: "symbols",
    unicode: "_25fe",
    htmlEntity: "&#x25FE",
  },
  "◽": {
    name: "white-medium-small-square",
    category: "symbols",
    unicode: "_25fd",
    htmlEntity: "&#x25FD",
  },
  "◼": {
    name: "black-medium-square",
    category: "symbols",
    unicode: "_25fc",
    htmlEntity: "&#x25FC",
  },
  "◻": {
    name: "white-medium-square",
    category: "symbols",
    unicode: "_25fb",
    htmlEntity: "&#x25FB",
  },
  "⬛": {
    name: "black-large-square",
    category: "symbols",
    unicode: "_2b1b",
    htmlEntity: "&#x2B1B",
  },
  "⬜": {
    name: "white-large-square",
    category: "symbols",
    unicode: "_2b1c",
    htmlEntity: "&#x2B1C",
  },
  "🟧": {
    name: "orange-square",
    category: "symbols",
    unicode: "_1f7e7",
    htmlEntity: "&#x1F7E7",
  },
  "🟦": {
    name: "blue-square",
    category: "symbols",
    unicode: "_1f7e6",
    htmlEntity: "&#x1F7E6",
  },
  "🟥": {
    name: "red-square",
    category: "symbols",
    unicode: "_1f7e5",
    htmlEntity: "&#x1F7E5",
  },
  "🟫": {
    name: "brown-square",
    category: "symbols",
    unicode: "_1f7eb",
    htmlEntity: "&#x1F7EB",
  },
  "🟪": {
    name: "purple-square",
    category: "symbols",
    unicode: "_1f7ea",
    htmlEntity: "&#x1F7EA",
  },
  "🟩": {
    name: "green-square",
    category: "symbols",
    unicode: "_1f7e9",
    htmlEntity: "&#x1F7E9",
  },
  "🟨": {
    name: "yellow-square",
    category: "symbols",
    unicode: "_1f7e8",
    htmlEntity: "&#x1F7E8",
  },
  "🔈": {
    name: "speaker-low-volume",
    category: "symbols",
    unicode: "_1f508",
    htmlEntity: "&#x1F508",
  },
  "🔇": {
    name: "muted-speaker",
    category: "symbols",
    unicode: "_1f507",
    htmlEntity: "&#x1F507",
  },
  "🔉": {
    name: "speaker-medium-volume",
    category: "symbols",
    unicode: "_1f509",
    htmlEntity: "&#x1F509",
  },
  "🔊": {
    name: "speaker-high-volume",
    category: "symbols",
    unicode: "_1f50a",
    htmlEntity: "&#x1F50A",
  },
  "🔔": {
    name: "bell",
    category: "symbols",
    unicode: "_1f514",
    htmlEntity: "&#x1F514",
  },
  "🔕": {
    name: "bell-with-slash",
    category: "symbols",
    unicode: "_1f515",
    htmlEntity: "&#x1F515",
  },
  "📣": {
    name: "megaphone",
    category: "symbols",
    unicode: "_1f4e3",
    htmlEntity: "&#x1F4E3",
  },
  "📢": {
    name: "loudspeaker",
    category: "symbols",
    unicode: "_1f4e2",
    htmlEntity: "&#x1F4E2",
  },
  "🗨": {
    name: "left-speech-bubble",
    category: "symbols",
    unicode: "_1f5e8",
    htmlEntity: "&#x1F5E8",
  },
  "👁🗨": {
    name: "eye-in-speech-bubble",
    category: "symbols",
    unicode: "_1f441-1f5e8",
    htmlEntity: "&#x1F441;&#x1F5E8",
  },
  "💬": {
    name: "speech-balloon",
    category: "symbols",
    unicode: "_1f4ac",
    htmlEntity: "&#x1F4AC",
  },
  "💭": {
    name: "thought-balloon",
    category: "symbols",
    unicode: "_1f4ad",
    htmlEntity: "&#x1F4AD",
  },
  "🗯": {
    name: "right-anger-bubble",
    category: "symbols",
    unicode: "_1f5ef",
    htmlEntity: "&#x1F5EF",
  },
  "♠": {
    name: "spade-suit",
    category: "symbols",
    unicode: "_2660",
    htmlEntity: "&#x2660",
  },
  "♣": {
    name: "club-suit",
    category: "symbols",
    unicode: "_2663",
    htmlEntity: "&#x2663",
  },
  "♥": {
    name: "heart-suit",
    category: "symbols",
    unicode: "_2665",
    htmlEntity: "&#x2665",
  },
  "♦": {
    name: "diamond-suit",
    category: "symbols",
    unicode: "_2666",
    htmlEntity: "&#x2666",
  },
  "🃏": {
    name: "joker",
    category: "symbols",
    unicode: "_1f0cf",
    htmlEntity: "&#x1F0CF",
  },
  "🎴": {
    name: "flower-playing-cards",
    category: "symbols",
    unicode: "_1f3b4",
    htmlEntity: "&#x1F3B4",
  },
  "🀄": {
    name: "mahjong-red-dragon",
    category: "symbols",
    unicode: "_1f004",
    htmlEntity: "&#x1F004",
  },
  "🕐": {
    name: "one-o’clock",
    category: "symbols",
    unicode: "_1f550",
    htmlEntity: "&#x1F550",
  },
  "🕑": {
    name: "two-o’clock",
    category: "symbols",
    unicode: "_1f551",
    htmlEntity: "&#x1F551",
  },
  "🕒": {
    name: "three-o’clock",
    category: "symbols",
    unicode: "_1f552",
    htmlEntity: "&#x1F552",
  },
  "🕓": {
    name: "four-o’clock",
    category: "symbols",
    unicode: "_1f553",
    htmlEntity: "&#x1F553",
  },
  "🕔": {
    name: "five-o’clock",
    category: "symbols",
    unicode: "_1f554",
    htmlEntity: "&#x1F554",
  },
  "🕕": {
    name: "six-o’clock",
    category: "symbols",
    unicode: "_1f555",
    htmlEntity: "&#x1F555",
  },
  "🕖": {
    name: "seven-o’clock",
    category: "symbols",
    unicode: "_1f556",
    htmlEntity: "&#x1F556",
  },
  "🕗": {
    name: "eight-o’clock",
    category: "symbols",
    unicode: "_1f557",
    htmlEntity: "&#x1F557",
  },
  "🕘": {
    name: "nine-o’clock",
    category: "symbols",
    unicode: "_1f558",
    htmlEntity: "&#x1F558",
  },
  "🕙": {
    name: "ten-o’clock",
    category: "symbols",
    unicode: "_1f559",
    htmlEntity: "&#x1F559",
  },
  "🕚": {
    name: "eleven-o’clock",
    category: "symbols",
    unicode: "_1f55a",
    htmlEntity: "&#x1F55A",
  },
  "🕛": {
    name: "twelve-o’clock",
    category: "symbols",
    unicode: "_1f55b",
    htmlEntity: "&#x1F55B",
  },
  "🕜": {
    name: "one-thirty",
    category: "symbols",
    unicode: "_1f55c",
    htmlEntity: "&#x1F55C",
  },
  "🕝": {
    name: "two-thirty",
    category: "symbols",
    unicode: "_1f55d",
    htmlEntity: "&#x1F55D",
  },
  "🕞": {
    name: "three-thirty",
    category: "symbols",
    unicode: "_1f55e",
    htmlEntity: "&#x1F55E",
  },
  "🕟": {
    name: "four-thirty",
    category: "symbols",
    unicode: "_1f55f",
    htmlEntity: "&#x1F55F",
  },
  "🕠": {
    name: "five-thirty",
    category: "symbols",
    unicode: "_1f560",
    htmlEntity: "&#x1F560",
  },
  "🕡": {
    name: "six-thirty",
    category: "symbols",
    unicode: "_1f561",
    htmlEntity: "&#x1F561",
  },
  "🕢": {
    name: "seven-thirty",
    category: "symbols",
    unicode: "_1f562",
    htmlEntity: "&#x1F562",
  },
  "🕣": {
    name: "eight-thirty",
    category: "symbols",
    unicode: "_1f563",
    htmlEntity: "&#x1F563",
  },
  "🕤": {
    name: "nine-thirty",
    category: "symbols",
    unicode: "_1f564",
    htmlEntity: "&#x1F564",
  },
  "🕥": {
    name: "ten-thirty",
    category: "symbols",
    unicode: "_1f565",
    htmlEntity: "&#x1F565",
  },
  "🕦": {
    name: "eleven-thirty",
    category: "symbols",
    unicode: "_1f566",
    htmlEntity: "&#x1F566",
  },
  "🕧": {
    name: "twelve-thirty",
    category: "symbols",
    unicode: "_1f567",
    htmlEntity: "&#x1F567",
  },
  "#": {
    name: "pound-symbol",
    category: "symbols",
    unicode: "_0023",
    htmlEntity: "&#x0023",
  },
  "*": {
    name: "asterisk",
    category: "symbols",
    unicode: "_002a",
    htmlEntity: "&#x002A",
  },
  "♀": {
    name: "female-sign",
    category: "symbols",
    unicode: "_2640",
    htmlEntity: "&#x2640",
  },
  "♂": {
    name: "male-sign",
    category: "symbols",
    unicode: "_2642",
    htmlEntity: "&#x2642",
  },
  "⚧": {
    name: "transgender-symbol",
    category: "symbols",
    unicode: "_26a7",
    htmlEntity: "&#x26A7",
  },
  "⚕": {
    name: "medical-symbol",
    category: "symbols",
    unicode: "_2695",
    htmlEntity: "&#x2695",
  },
};
