import { EmojiInformation } from "../types/emojiInformation";

export const SYMBOLS: EmojiInformation = {
  "red-heart": {
    name: "red-heart",
    category: "symbols",
    unicode: "_2764",
    htmlEntity: "&#x2764",
  },
  "orange-heart": {
    name: "orange-heart",
    category: "symbols",
    unicode: "_1f9e1",
    htmlEntity: "&#x1F9E1",
  },
  "yellow-heart": {
    name: "yellow-heart",
    category: "symbols",
    unicode: "_1f49b",
    htmlEntity: "&#x1F49B",
  },
  "green-heart": {
    name: "green-heart",
    category: "symbols",
    unicode: "_1f49a",
    htmlEntity: "&#x1F49A",
  },
  "blue-heart": {
    name: "blue-heart",
    category: "symbols",
    unicode: "_1f499",
    htmlEntity: "&#x1F499",
  },
  "purple-heart": {
    name: "purple-heart",
    category: "symbols",
    unicode: "_1f49c",
    htmlEntity: "&#x1F49C",
  },
  "black-heart": {
    name: "black-heart",
    category: "symbols",
    unicode: "_1f5a4",
    htmlEntity: "&#x1F5A4",
  },
  "brown-heart": {
    name: "brown-heart",
    category: "symbols",
    unicode: "_1f90e",
    htmlEntity: "&#x1F90E",
  },
  "white-heart": {
    name: "white-heart",
    category: "symbols",
    unicode: "_1f90d",
    htmlEntity: "&#x1F90D",
  },
  "broken-heart": {
    name: "broken-heart",
    category: "symbols",
    unicode: "_1f494",
    htmlEntity: "&#x1F494",
  },
  "heart-exclamation": {
    name: "heart-exclamation",
    category: "symbols",
    unicode: "_2763",
    htmlEntity: "&#x2763",
  },
  "two-hearts": {
    name: "two-hearts",
    category: "symbols",
    unicode: "_1f495",
    htmlEntity: "&#x1F495",
  },
  "revolving-hearts": {
    name: "revolving-hearts",
    category: "symbols",
    unicode: "_1f49e",
    htmlEntity: "&#x1F49E",
  },
  "beating-heart": {
    name: "beating-heart",
    category: "symbols",
    unicode: "_1f493",
    htmlEntity: "&#x1F493",
  },
  "growing-heart": {
    name: "growing-heart",
    category: "symbols",
    unicode: "_1f497",
    htmlEntity: "&#x1F497",
  },
  "sparkling-heart": {
    name: "sparkling-heart",
    category: "symbols",
    unicode: "_1f496",
    htmlEntity: "&#x1F496",
  },
  "heart-with-arrow": {
    name: "heart-with-arrow",
    category: "symbols",
    unicode: "_1f498",
    htmlEntity: "&#x1F498",
  },
  "heart-with-ribbon": {
    name: "heart-with-ribbon",
    category: "symbols",
    unicode: "_1f49d",
    htmlEntity: "&#x1F49D",
  },
  "mending-heart": {
    name: "mending-heart",
    category: "symbols",
    unicode: "_2764-1fa79",
    htmlEntity: "&#x2764;&#x1FA79",
  },
  "heart-on-fire": {
    name: "heart-on-fire",
    category: "symbols",
    unicode: "_2764-1f525",
    htmlEntity: "&#x2764;&#x1F525",
  },
  "heart-decoration": {
    name: "heart-decoration",
    category: "symbols",
    unicode: "_1f49f",
    htmlEntity: "&#x1F49F",
  },
  "peace-symbol": {
    name: "peace-symbol",
    category: "symbols",
    unicode: "_262e",
    htmlEntity: "&#x262E",
  },
  "latin-cross": {
    name: "latin-cross",
    category: "symbols",
    unicode: "_271d",
    htmlEntity: "&#x271D",
  },
  "star-and-crescent": {
    name: "star-and-crescent",
    category: "symbols",
    unicode: "_262a",
    htmlEntity: "&#x262A",
  },
  om: {
    name: "om",
    category: "symbols",
    unicode: "_1f549",
    htmlEntity: "&#x1F549",
  },
  "wheel-of-dharma": {
    name: "wheel-of-dharma",
    category: "symbols",
    unicode: "_2638",
    htmlEntity: "&#x2638",
  },
  "star-of-david": {
    name: "star-of-david",
    category: "symbols",
    unicode: "_2721",
    htmlEntity: "&#x2721",
  },
  "dotted-six-pointed-star": {
    name: "dotted-six-pointed-star",
    category: "symbols",
    unicode: "_1f52f",
    htmlEntity: "&#x1F52F",
  },
  menorah: {
    name: "menorah",
    category: "symbols",
    unicode: "_1f54e",
    htmlEntity: "&#x1F54E",
  },
  "yin-yang": {
    name: "yin-yang",
    category: "symbols",
    unicode: "_262f",
    htmlEntity: "&#x262F",
  },
  "orthodox-cross": {
    name: "orthodox-cross",
    category: "symbols",
    unicode: "_2626",
    htmlEntity: "&#x2626",
  },
  "place-of-worship": {
    name: "place-of-worship",
    category: "symbols",
    unicode: "_1f6d0",
    htmlEntity: "&#x1F6D0",
  },
  ophiuchus: {
    name: "ophiuchus",
    category: "symbols",
    unicode: "_26ce",
    htmlEntity: "&#x26CE",
  },
  aries: {
    name: "aries",
    category: "symbols",
    unicode: "_2648",
    htmlEntity: "&#x2648",
  },
  taurus: {
    name: "taurus",
    category: "symbols",
    unicode: "_2649",
    htmlEntity: "&#x2649",
  },
  gemini: {
    name: "gemini",
    category: "symbols",
    unicode: "_264a",
    htmlEntity: "&#x264A",
  },
  cancer: {
    name: "cancer",
    category: "symbols",
    unicode: "_264b",
    htmlEntity: "&#x264B",
  },
  leo: {
    name: "leo",
    category: "symbols",
    unicode: "_264c",
    htmlEntity: "&#x264C",
  },
  virgo: {
    name: "virgo",
    category: "symbols",
    unicode: "_264d",
    htmlEntity: "&#x264D",
  },
  libra: {
    name: "libra",
    category: "symbols",
    unicode: "_264e",
    htmlEntity: "&#x264E",
  },
  scorpio: {
    name: "scorpio",
    category: "symbols",
    unicode: "_264f",
    htmlEntity: "&#x264F",
  },
  sagittarius: {
    name: "sagittarius",
    category: "symbols",
    unicode: "_2650",
    htmlEntity: "&#x2650",
  },
  capricorn: {
    name: "capricorn",
    category: "symbols",
    unicode: "_2651",
    htmlEntity: "&#x2651",
  },
  aquarius: {
    name: "aquarius",
    category: "symbols",
    unicode: "_2652",
    htmlEntity: "&#x2652",
  },
  pisces: {
    name: "pisces",
    category: "symbols",
    unicode: "_2653",
    htmlEntity: "&#x2653",
  },
  "id-button": {
    name: "id-button",
    category: "symbols",
    unicode: "_1f194",
    htmlEntity: "&#x1F194",
  },
  "atom-symbol": {
    name: "atom-symbol",
    category: "symbols",
    unicode: "_269b",
    htmlEntity: "&#x269B",
  },
  "japanese-“acceptable”-button": {
    name: "japanese-“acceptable”-button",
    category: "symbols",
    unicode: "_1f251",
    htmlEntity: "&#x1F251",
  },
  radioactive: {
    name: "radioactive",
    category: "symbols",
    unicode: "_2622",
    htmlEntity: "&#x2622",
  },
  biohazard: {
    name: "biohazard",
    category: "symbols",
    unicode: "_2623",
    htmlEntity: "&#x2623",
  },
  "mobile-phone-off": {
    name: "mobile-phone-off",
    category: "symbols",
    unicode: "_1f4f4",
    htmlEntity: "&#x1F4F4",
  },
  "vibration-mode": {
    name: "vibration-mode",
    category: "symbols",
    unicode: "_1f4f3",
    htmlEntity: "&#x1F4F3",
  },
  "japanese-“not-free-of-charge”-button": {
    name: "japanese-“not-free-of-charge”-button",
    category: "symbols",
    unicode: "_1f236",
    htmlEntity: "&#x1F236",
  },
  "japanese-“free-of-charge”-button": {
    name: "japanese-“free-of-charge”-button",
    category: "symbols",
    unicode: "_1f21a",
    htmlEntity: "&#x1F21A",
  },
  "japanese-“application”-button": {
    name: "japanese-“application”-button",
    category: "symbols",
    unicode: "_1f238",
    htmlEntity: "&#x1F238",
  },
  "japanese-“open-for-business”-button": {
    name: "japanese-“open-for-business”-button",
    category: "symbols",
    unicode: "_1f23a",
    htmlEntity: "&#x1F23A",
  },
  "japanese-“monthly-amount”-button": {
    name: "japanese-“monthly-amount”-button",
    category: "symbols",
    unicode: "_1f237",
    htmlEntity: "&#x1F237",
  },
  "eight-pointed-star": {
    name: "eight-pointed-star",
    category: "symbols",
    unicode: "_2734",
    htmlEntity: "&#x2734",
  },
  "vs-button": {
    name: "vs-button",
    category: "symbols",
    unicode: "_1f19a",
    htmlEntity: "&#x1F19A",
  },
  "white-flower": {
    name: "white-flower",
    category: "symbols",
    unicode: "_1f4ae",
    htmlEntity: "&#x1F4AE",
  },
  "japanese-“bargain”-button": {
    name: "japanese-“bargain”-button",
    category: "symbols",
    unicode: "_1f250",
    htmlEntity: "&#x1F250",
  },
  "japanese-“secret”-button": {
    name: "japanese-“secret”-button",
    category: "symbols",
    unicode: "_3299",
    htmlEntity: "&#x3299",
  },
  "japanese-“congratulations”-button": {
    name: "japanese-“congratulations”-button",
    category: "symbols",
    unicode: "_3297",
    htmlEntity: "&#x3297",
  },
  "japanese-“passing-grade”-button": {
    name: "japanese-“passing-grade”-button",
    category: "symbols",
    unicode: "_1f234",
    htmlEntity: "&#x1F234",
  },
  "japanese-“no-vacancy”-button": {
    name: "japanese-“no-vacancy”-button",
    category: "symbols",
    unicode: "_1f235",
    htmlEntity: "&#x1F235",
  },
  "japanese-“discount”-button": {
    name: "japanese-“discount”-button",
    category: "symbols",
    unicode: "_1f239",
    htmlEntity: "&#x1F239",
  },
  "japanese-“prohibited”-button": {
    name: "japanese-“prohibited”-button",
    category: "symbols",
    unicode: "_1f232",
    htmlEntity: "&#x1F232",
  },
  "a-button-blood-type": {
    name: "a-button-blood-type",
    category: "symbols",
    unicode: "_1f170",
    htmlEntity: "&#x1F170",
  },
  "b-button-blood-type": {
    name: "b-button-blood-type",
    category: "symbols",
    unicode: "_1f171",
    htmlEntity: "&#x1F171",
  },
  "ab-button-blood-type": {
    name: "ab-button-blood-type",
    category: "symbols",
    unicode: "_1f18e",
    htmlEntity: "&#x1F18E",
  },
  "cl-button": {
    name: "cl-button",
    category: "symbols",
    unicode: "_1f191",
    htmlEntity: "&#x1F191",
  },
  "o-button-blood-type": {
    name: "o-button-blood-type",
    category: "symbols",
    unicode: "_1f17e",
    htmlEntity: "&#x1F17E",
  },
  "sos-button": {
    name: "sos-button",
    category: "symbols",
    unicode: "_1f198",
    htmlEntity: "&#x1F198",
  },
  "cross-mark": {
    name: "cross-mark",
    category: "symbols",
    unicode: "_274c",
    htmlEntity: "&#x274C",
  },
  "hollow-red-circle": {
    name: "hollow-red-circle",
    category: "symbols",
    unicode: "_2b55",
    htmlEntity: "&#x2B55",
  },
  "stop-sign": {
    name: "stop-sign",
    category: "symbols",
    unicode: "_1f6d1",
    htmlEntity: "&#x1F6D1",
  },
  "no-entry": {
    name: "no-entry",
    category: "symbols",
    unicode: "_26d4",
    htmlEntity: "&#x26D4",
  },
  "name-badge": {
    name: "name-badge",
    category: "symbols",
    unicode: "_1f4db",
    htmlEntity: "&#x1F4DB",
  },
  prohibited: {
    name: "prohibited",
    category: "symbols",
    unicode: "_1f6ab",
    htmlEntity: "&#x1F6AB",
  },
  "hundred-points": {
    name: "hundred-points",
    category: "symbols",
    unicode: "_1f4af",
    htmlEntity: "&#x1F4AF",
  },
  "anger-symbol": {
    name: "anger-symbol",
    category: "symbols",
    unicode: "_1f4a2",
    htmlEntity: "&#x1F4A2",
  },
  "hot-springs": {
    name: "hot-springs",
    category: "symbols",
    unicode: "_2668",
    htmlEntity: "&#x2668",
  },
  "no-pedestrians": {
    name: "no-pedestrians",
    category: "symbols",
    unicode: "_1f6b7",
    htmlEntity: "&#x1F6B7",
  },
  "no-littering": {
    name: "no-littering",
    category: "symbols",
    unicode: "_1f6af",
    htmlEntity: "&#x1F6AF",
  },
  "no-bicycles": {
    name: "no-bicycles",
    category: "symbols",
    unicode: "_1f6b3",
    htmlEntity: "&#x1F6B3",
  },
  "non-potable-water": {
    name: "non-potable-water",
    category: "symbols",
    unicode: "_1f6b1",
    htmlEntity: "&#x1F6B1",
  },
  "no-one-under-eighteen": {
    name: "no-one-under-eighteen",
    category: "symbols",
    unicode: "_1f51e",
    htmlEntity: "&#x1F51E",
  },
  "no-mobile-phones": {
    name: "no-mobile-phones",
    category: "symbols",
    unicode: "_1f4f5",
    htmlEntity: "&#x1F4F5",
  },
  "no-smoking": {
    name: "no-smoking",
    category: "symbols",
    unicode: "_1f6ad",
    htmlEntity: "&#x1F6AD",
  },
  "exclamation-mark": {
    name: "exclamation-mark",
    category: "symbols",
    unicode: "_2757",
    htmlEntity: "&#x2757",
  },
  "white-exclamation-mark": {
    name: "white-exclamation-mark",
    category: "symbols",
    unicode: "_2755",
    htmlEntity: "&#x2755",
  },
  "question-mark": {
    name: "question-mark",
    category: "symbols",
    unicode: "_2753",
    htmlEntity: "&#x2753",
  },
  "white-question-mark": {
    name: "white-question-mark",
    category: "symbols",
    unicode: "_2754",
    htmlEntity: "&#x2754",
  },
  "double-exclamation-mark": {
    name: "double-exclamation-mark",
    category: "symbols",
    unicode: "_203c",
    htmlEntity: "&#x203C",
  },
  "exclamation-question-mark": {
    name: "exclamation-question-mark",
    category: "symbols",
    unicode: "_2049",
    htmlEntity: "&#x2049",
  },
  "dim-button": {
    name: "dim-button",
    category: "symbols",
    unicode: "_1f505",
    htmlEntity: "&#x1F505",
  },
  "bright-button": {
    name: "bright-button",
    category: "symbols",
    unicode: "_1f506",
    htmlEntity: "&#x1F506",
  },
  "part-alternation-mark": {
    name: "part-alternation-mark",
    category: "symbols",
    unicode: "_303d",
    htmlEntity: "&#x303D",
  },
  warning: {
    name: "warning",
    category: "symbols",
    unicode: "_26a0",
    htmlEntity: "&#x26A0",
  },
  "children-crossing": {
    name: "children-crossing",
    category: "symbols",
    unicode: "_1f6b8",
    htmlEntity: "&#x1F6B8",
  },
  "trident-emblem": {
    name: "trident-emblem",
    category: "symbols",
    unicode: "_1f531",
    htmlEntity: "&#x1F531",
  },
  "fleur-de-lis": {
    name: "fleur-de-lis",
    category: "symbols",
    unicode: "_269c",
    htmlEntity: "&#x269C",
  },
  "japanese-symbol-for-beginner": {
    name: "japanese-symbol-for-beginner",
    category: "symbols",
    unicode: "_1f530",
    htmlEntity: "&#x1F530",
  },
  "recycling-symbol": {
    name: "recycling-symbol",
    category: "symbols",
    unicode: "_267b",
    htmlEntity: "&#x267B",
  },
  "check-mark-button": {
    name: "check-mark-button",
    category: "symbols",
    unicode: "_2705",
    htmlEntity: "&#x2705",
  },
  "japanese-“reserved”-button": {
    name: "japanese-“reserved”-button",
    category: "symbols",
    unicode: "_1f22f",
    htmlEntity: "&#x1F22F",
  },
  "chart-increasing-with-yen": {
    name: "chart-increasing-with-yen",
    category: "symbols",
    unicode: "_1f4b9",
    htmlEntity: "&#x1F4B9",
  },
  sparkle: {
    name: "sparkle",
    category: "symbols",
    unicode: "_2747",
    htmlEntity: "&#x2747",
  },
  "eight-spoked-asterisk": {
    name: "eight-spoked-asterisk",
    category: "symbols",
    unicode: "_2733",
    htmlEntity: "&#x2733",
  },
  "cross-mark-button": {
    name: "cross-mark-button",
    category: "symbols",
    unicode: "_274e",
    htmlEntity: "&#x274E",
  },
  "globe-with-meridians": {
    name: "globe-with-meridians",
    category: "symbols",
    unicode: "_1f310",
    htmlEntity: "&#x1F310",
  },
  "diamond-with-a-dot": {
    name: "diamond-with-a-dot",
    category: "symbols",
    unicode: "_1f4a0",
    htmlEntity: "&#x1F4A0",
  },
  "circled-m": {
    name: "circled-m",
    category: "symbols",
    unicode: "_24c2",
    htmlEntity: "&#x24C2",
  },
  cyclone: {
    name: "cyclone",
    category: "symbols",
    unicode: "_1f300",
    htmlEntity: "&#x1F300",
  },
  zzz: {
    name: "zzz",
    category: "symbols",
    unicode: "_1f4a4",
    htmlEntity: "&#x1F4A4",
  },
  "atm-sign": {
    name: "atm-sign",
    category: "symbols",
    unicode: "_1f3e7",
    htmlEntity: "&#x1F3E7",
  },
  "water-closet": {
    name: "water-closet",
    category: "symbols",
    unicode: "_1f6be",
    htmlEntity: "&#x1F6BE",
  },
  "wheelchair-symbol": {
    name: "wheelchair-symbol",
    category: "symbols",
    unicode: "_267f",
    htmlEntity: "&#x267F",
  },
  "p-button": {
    name: "p-button",
    category: "symbols",
    unicode: "_1f17f",
    htmlEntity: "&#x1F17F",
  },
  "japanese-“vacancy”-button": {
    name: "japanese-“vacancy”-button",
    category: "symbols",
    unicode: "_1f233",
    htmlEntity: "&#x1F233",
  },
  "japanese-“service-charge”-button": {
    name: "japanese-“service-charge”-button",
    category: "symbols",
    unicode: "_1f202",
    htmlEntity: "&#x1F202",
  },
  "passport-control": {
    name: "passport-control",
    category: "symbols",
    unicode: "_1f6c2",
    htmlEntity: "&#x1F6C2",
  },
  customs: {
    name: "customs",
    category: "symbols",
    unicode: "_1f6c3",
    htmlEntity: "&#x1F6C3",
  },
  "baggage-claim": {
    name: "baggage-claim",
    category: "symbols",
    unicode: "_1f6c4",
    htmlEntity: "&#x1F6C4",
  },
  "left-luggage": {
    name: "left-luggage",
    category: "symbols",
    unicode: "_1f6c5",
    htmlEntity: "&#x1F6C5",
  },
  elevator: {
    name: "elevator",
    category: "symbols",
    unicode: "_1f6d7",
    htmlEntity: "&#x1F6D7",
  },
  "men’s-room": {
    name: "men’s-room",
    category: "symbols",
    unicode: "_1f6b9",
    htmlEntity: "&#x1F6B9",
  },
  "women’s-room": {
    name: "women’s-room",
    category: "symbols",
    unicode: "_1f6ba",
    htmlEntity: "&#x1F6BA",
  },
  "baby-symbol": {
    name: "baby-symbol",
    category: "symbols",
    unicode: "_1f6bc",
    htmlEntity: "&#x1F6BC",
  },
  restroom: {
    name: "restroom",
    category: "symbols",
    unicode: "_1f6bb",
    htmlEntity: "&#x1F6BB",
  },
  "litter-in-bin-sign": {
    name: "litter-in-bin-sign",
    category: "symbols",
    unicode: "_1f6ae",
    htmlEntity: "&#x1F6AE",
  },
  cinema: {
    name: "cinema",
    category: "symbols",
    unicode: "_1f3a6",
    htmlEntity: "&#x1F3A6",
  },
  "antenna-bars": {
    name: "antenna-bars",
    category: "symbols",
    unicode: "_1f4f6",
    htmlEntity: "&#x1F4F6",
  },
  "japanese-“here”-button": {
    name: "japanese-“here”-button",
    category: "symbols",
    unicode: "_1f201",
    htmlEntity: "&#x1F201",
  },
  "input-symbols": {
    name: "input-symbols",
    category: "symbols",
    unicode: "_1f523",
    htmlEntity: "&#x1F523",
  },
  information: {
    name: "information",
    category: "symbols",
    unicode: "_2139",
    htmlEntity: "&#x2139",
  },
  "input-latin-letters": {
    name: "input-latin-letters",
    category: "symbols",
    unicode: "_1f524",
    htmlEntity: "&#x1F524",
  },
  "input-latin-lowercase": {
    name: "input-latin-lowercase",
    category: "symbols",
    unicode: "_1f521",
    htmlEntity: "&#x1F521",
  },
  "input-latin-uppercase": {
    name: "input-latin-uppercase",
    category: "symbols",
    unicode: "_1f520",
    htmlEntity: "&#x1F520",
  },
  "ng-button": {
    name: "ng-button",
    category: "symbols",
    unicode: "_1f196",
    htmlEntity: "&#x1F196",
  },
  "ok-button": {
    name: "ok-button",
    category: "symbols",
    unicode: "_1f197",
    htmlEntity: "&#x1F197",
  },
  "up!-button": {
    name: "up!-button",
    category: "symbols",
    unicode: "_1f199",
    htmlEntity: "&#x1F199",
  },
  "cool-button": {
    name: "cool-button",
    category: "symbols",
    unicode: "_1f192",
    htmlEntity: "&#x1F192",
  },
  "new-button": {
    name: "new-button",
    category: "symbols",
    unicode: "_1f195",
    htmlEntity: "&#x1F195",
  },
  "free-button": {
    name: "free-button",
    category: "symbols",
    unicode: "_1f193",
    htmlEntity: "&#x1F193",
  },
  "keycap-0": {
    name: "keycap-0",
    category: "symbols",
    unicode: "_0030-20e3",
    htmlEntity: "&#x0030;&#x20E3",
  },
  "keycap-1": {
    name: "keycap-1",
    category: "symbols",
    unicode: "_0031-20e3",
    htmlEntity: "&#x0031;&#x20E3",
  },
  "keycap-2": {
    name: "keycap-2",
    category: "symbols",
    unicode: "_0032-20e3",
    htmlEntity: "&#x0032;&#x20E3",
  },
  "keycap-3": {
    name: "keycap-3",
    category: "symbols",
    unicode: "_0033-20e3",
    htmlEntity: "&#x0033;&#x20E3",
  },
  "keycap-4": {
    name: "keycap-4",
    category: "symbols",
    unicode: "_0034-20e3",
    htmlEntity: "&#x0034;&#x20E3",
  },
  "keycap-5": {
    name: "keycap-5",
    category: "symbols",
    unicode: "_0035-20e3",
    htmlEntity: "&#x0035;&#x20E3",
  },
  "keycap-6": {
    name: "keycap-6",
    category: "symbols",
    unicode: "_0036-20e3",
    htmlEntity: "&#x0036;&#x20E3",
  },
  "keycap-7": {
    name: "keycap-7",
    category: "symbols",
    unicode: "_0037-20e3",
    htmlEntity: "&#x0037;&#x20E3",
  },
  "keycap-8": {
    name: "keycap-8",
    category: "symbols",
    unicode: "_0038-20e3",
    htmlEntity: "&#x0038;&#x20E3",
  },
  "keycap-9": {
    name: "keycap-9",
    category: "symbols",
    unicode: "_0039-20e3",
    htmlEntity: "&#x0039;&#x20E3",
  },
  "keycap-10": {
    name: "keycap-10",
    category: "symbols",
    unicode: "_1f51f",
    htmlEntity: "&#x1F51F",
  },
  "input-numbers": {
    name: "input-numbers",
    category: "symbols",
    unicode: "_1f522",
    htmlEntity: "&#x1F522",
  },
  "keycap-#": {
    name: "keycap-#",
    category: "symbols",
    unicode: "_0023-20e3",
    htmlEntity: "&#x0023;&#x20E3",
  },
  "keycap-*": {
    name: "keycap-*",
    category: "symbols",
    unicode: "_002a-20e3",
    htmlEntity: "&#x002A;&#x20E3",
  },
  "eject-button": {
    name: "eject-button",
    category: "symbols",
    unicode: "_23cf",
    htmlEntity: "&#x23CF",
  },
  "play-button": {
    name: "play-button",
    category: "symbols",
    unicode: "_25b6",
    htmlEntity: "&#x25B6",
  },
  "pause-button": {
    name: "pause-button",
    category: "symbols",
    unicode: "_23f8",
    htmlEntity: "&#x23F8",
  },
  "play-or-pause-button": {
    name: "play-or-pause-button",
    category: "symbols",
    unicode: "_23ef",
    htmlEntity: "&#x23EF",
  },
  "stop-button": {
    name: "stop-button",
    category: "symbols",
    unicode: "_23f9",
    htmlEntity: "&#x23F9",
  },
  "record-button": {
    name: "record-button",
    category: "symbols",
    unicode: "_23fa",
    htmlEntity: "&#x23FA",
  },
  "next-track-button": {
    name: "next-track-button",
    category: "symbols",
    unicode: "_23ed",
    htmlEntity: "&#x23ED",
  },
  "last-track-button": {
    name: "last-track-button",
    category: "symbols",
    unicode: "_23ee",
    htmlEntity: "&#x23EE",
  },
  "fast-forward-button": {
    name: "fast-forward-button",
    category: "symbols",
    unicode: "_23e9",
    htmlEntity: "&#x23E9",
  },
  "fast-reverse-button": {
    name: "fast-reverse-button",
    category: "symbols",
    unicode: "_23ea",
    htmlEntity: "&#x23EA",
  },
  "fast-up-button": {
    name: "fast-up-button",
    category: "symbols",
    unicode: "_23eb",
    htmlEntity: "&#x23EB",
  },
  "fast-down-button": {
    name: "fast-down-button",
    category: "symbols",
    unicode: "_23ec",
    htmlEntity: "&#x23EC",
  },
  "reverse-button": {
    name: "reverse-button",
    category: "symbols",
    unicode: "_25c0",
    htmlEntity: "&#x25C0",
  },
  "upwards-button": {
    name: "upwards-button",
    category: "symbols",
    unicode: "_1f53c",
    htmlEntity: "&#x1F53C",
  },
  "downwards-button": {
    name: "downwards-button",
    category: "symbols",
    unicode: "_1f53d",
    htmlEntity: "&#x1F53D",
  },
  "right-arrow": {
    name: "right-arrow",
    category: "symbols",
    unicode: "_27a1",
    htmlEntity: "&#x27A1",
  },
  "left-arrow": {
    name: "left-arrow",
    category: "symbols",
    unicode: "_2b05",
    htmlEntity: "&#x2B05",
  },
  "up-arrow": {
    name: "up-arrow",
    category: "symbols",
    unicode: "_2b06",
    htmlEntity: "&#x2B06",
  },
  "down-arrow": {
    name: "down-arrow",
    category: "symbols",
    unicode: "_2b07",
    htmlEntity: "&#x2B07",
  },
  "up-right-arrow": {
    name: "up-right-arrow",
    category: "symbols",
    unicode: "_2197",
    htmlEntity: "&#x2197",
  },
  "down-right-arrow": {
    name: "down-right-arrow",
    category: "symbols",
    unicode: "_2198",
    htmlEntity: "&#x2198",
  },
  "down-left-arrow": {
    name: "down-left-arrow",
    category: "symbols",
    unicode: "_2199",
    htmlEntity: "&#x2199",
  },
  "up-left-arrow": {
    name: "up-left-arrow",
    category: "symbols",
    unicode: "_2196",
    htmlEntity: "&#x2196",
  },
  "up-down-arrow": {
    name: "up-down-arrow",
    category: "symbols",
    unicode: "_2195",
    htmlEntity: "&#x2195",
  },
  "left-right-arrow": {
    name: "left-right-arrow",
    category: "symbols",
    unicode: "_2194",
    htmlEntity: "&#x2194",
  },
  "left-arrow-curving-right": {
    name: "left-arrow-curving-right",
    category: "symbols",
    unicode: "_21aa",
    htmlEntity: "&#x21AA",
  },
  "right-arrow-curving-left": {
    name: "right-arrow-curving-left",
    category: "symbols",
    unicode: "_21a9",
    htmlEntity: "&#x21A9",
  },
  "right-arrow-curving-up": {
    name: "right-arrow-curving-up",
    category: "symbols",
    unicode: "_2934",
    htmlEntity: "&#x2934",
  },
  "right-arrow-curving-down": {
    name: "right-arrow-curving-down",
    category: "symbols",
    unicode: "_2935",
    htmlEntity: "&#x2935",
  },
  "shuffle-tracks-button": {
    name: "shuffle-tracks-button",
    category: "symbols",
    unicode: "_1f500",
    htmlEntity: "&#x1F500",
  },
  "repeat-button": {
    name: "repeat-button",
    category: "symbols",
    unicode: "_1f501",
    htmlEntity: "&#x1F501",
  },
  "repeat-single-button": {
    name: "repeat-single-button",
    category: "symbols",
    unicode: "_1f502",
    htmlEntity: "&#x1F502",
  },
  "counterclockwise-arrows-button": {
    name: "counterclockwise-arrows-button",
    category: "symbols",
    unicode: "_1f504",
    htmlEntity: "&#x1F504",
  },
  "clockwise-vertical-arrows": {
    name: "clockwise-vertical-arrows",
    category: "symbols",
    unicode: "_1f503",
    htmlEntity: "&#x1F503",
  },
  "musical-note": {
    name: "musical-note",
    category: "symbols",
    unicode: "_1f3b5",
    htmlEntity: "&#x1F3B5",
  },
  "musical-notes": {
    name: "musical-notes",
    category: "symbols",
    unicode: "_1f3b6",
    htmlEntity: "&#x1F3B6",
  },
  "plus-sign": {
    name: "plus-sign",
    category: "symbols",
    unicode: "_2795",
    htmlEntity: "&#x2795",
  },
  "minus-sign": {
    name: "minus-sign",
    category: "symbols",
    unicode: "_2796",
    htmlEntity: "&#x2796",
  },
  "division-sign": {
    name: "division-sign",
    category: "symbols",
    unicode: "_2797",
    htmlEntity: "&#x2797",
  },
  "multiplication-sign": {
    name: "multiplication-sign",
    category: "symbols",
    unicode: "_2716",
    htmlEntity: "&#x2716",
  },
  infinity: {
    name: "infinity",
    category: "symbols",
    unicode: "_267e",
    htmlEntity: "&#x267E",
  },
  "heavy-dollar-sign": {
    name: "heavy-dollar-sign",
    category: "symbols",
    unicode: "_1f4b2",
    htmlEntity: "&#x1F4B2",
  },
  "currency-exchange": {
    name: "currency-exchange",
    category: "symbols",
    unicode: "_1f4b1",
    htmlEntity: "&#x1F4B1",
  },
  "trade-mark": {
    name: "trade-mark",
    category: "symbols",
    unicode: "_2122",
    htmlEntity: "&#x2122",
  },
  copyright: {
    name: "copyright",
    category: "symbols",
    unicode: "_00a9",
    htmlEntity: "&#x00A9",
  },
  registered: {
    name: "registered",
    category: "symbols",
    unicode: "_00ae",
    htmlEntity: "&#x00AE",
  },
  "wavy-dash": {
    name: "wavy-dash",
    category: "symbols",
    unicode: "_3030",
    htmlEntity: "&#x3030",
  },
  "curly-loop": {
    name: "curly-loop",
    category: "symbols",
    unicode: "_27b0",
    htmlEntity: "&#x27B0",
  },
  "double-curly-loop": {
    name: "double-curly-loop",
    category: "symbols",
    unicode: "_27bf",
    htmlEntity: "&#x27BF",
  },
  "end-arrow": {
    name: "end-arrow",
    category: "symbols",
    unicode: "_1f51a",
    htmlEntity: "&#x1F51A",
  },
  "back-arrow": {
    name: "back-arrow",
    category: "symbols",
    unicode: "_1f519",
    htmlEntity: "&#x1F519",
  },
  "on!-arrow": {
    name: "on!-arrow",
    category: "symbols",
    unicode: "_1f51b",
    htmlEntity: "&#x1F51B",
  },
  "top-arrow": {
    name: "top-arrow",
    category: "symbols",
    unicode: "_1f51d",
    htmlEntity: "&#x1F51D",
  },
  "soon-arrow": {
    name: "soon-arrow",
    category: "symbols",
    unicode: "_1f51c",
    htmlEntity: "&#x1F51C",
  },
  "check-mark": {
    name: "check-mark",
    category: "symbols",
    unicode: "_2714",
    htmlEntity: "&#x2714",
  },
  "check-box-with-check": {
    name: "check-box-with-check",
    category: "symbols",
    unicode: "_2611",
    htmlEntity: "&#x2611",
  },
  "radio-button": {
    name: "radio-button",
    category: "symbols",
    unicode: "_1f518",
    htmlEntity: "&#x1F518",
  },
  "white-circle": {
    name: "white-circle",
    category: "symbols",
    unicode: "_26aa",
    htmlEntity: "&#x26AA",
  },
  "black-circle": {
    name: "black-circle",
    category: "symbols",
    unicode: "_26ab",
    htmlEntity: "&#x26AB",
  },
  "red-circle": {
    name: "red-circle",
    category: "symbols",
    unicode: "_1f534",
    htmlEntity: "&#x1F534",
  },
  "blue-circle": {
    name: "blue-circle",
    category: "symbols",
    unicode: "_1f535",
    htmlEntity: "&#x1F535",
  },
  "brown-circle": {
    name: "brown-circle",
    category: "symbols",
    unicode: "_1f7e4",
    htmlEntity: "&#x1F7E4",
  },
  "purple-circle": {
    name: "purple-circle",
    category: "symbols",
    unicode: "_1f7e3",
    htmlEntity: "&#x1F7E3",
  },
  "green-circle": {
    name: "green-circle",
    category: "symbols",
    unicode: "_1f7e2",
    htmlEntity: "&#x1F7E2",
  },
  "yellow-circle": {
    name: "yellow-circle",
    category: "symbols",
    unicode: "_1f7e1",
    htmlEntity: "&#x1F7E1",
  },
  "orange-circle": {
    name: "orange-circle",
    category: "symbols",
    unicode: "_1f7e0",
    htmlEntity: "&#x1F7E0",
  },
  "red-triangle-pointed-up": {
    name: "red-triangle-pointed-up",
    category: "symbols",
    unicode: "_1f53a",
    htmlEntity: "&#x1F53A",
  },
  "red-triangle-pointed-down": {
    name: "red-triangle-pointed-down",
    category: "symbols",
    unicode: "_1f53b",
    htmlEntity: "&#x1F53B",
  },
  "small-orange-diamond": {
    name: "small-orange-diamond",
    category: "symbols",
    unicode: "_1f538",
    htmlEntity: "&#x1F538",
  },
  "small-blue-diamond": {
    name: "small-blue-diamond",
    category: "symbols",
    unicode: "_1f539",
    htmlEntity: "&#x1F539",
  },
  "large-orange-diamond": {
    name: "large-orange-diamond",
    category: "symbols",
    unicode: "_1f536",
    htmlEntity: "&#x1F536",
  },
  "large-blue-diamond": {
    name: "large-blue-diamond",
    category: "symbols",
    unicode: "_1f537",
    htmlEntity: "&#x1F537",
  },
  "white-square-button": {
    name: "white-square-button",
    category: "symbols",
    unicode: "_1f533",
    htmlEntity: "&#x1F533",
  },
  "black-square-button": {
    name: "black-square-button",
    category: "symbols",
    unicode: "_1f532",
    htmlEntity: "&#x1F532",
  },
  "black-small-square": {
    name: "black-small-square",
    category: "symbols",
    unicode: "_25aa",
    htmlEntity: "&#x25AA",
  },
  "white-small-square": {
    name: "white-small-square",
    category: "symbols",
    unicode: "_25ab",
    htmlEntity: "&#x25AB",
  },
  "black-medium-small-square": {
    name: "black-medium-small-square",
    category: "symbols",
    unicode: "_25fe",
    htmlEntity: "&#x25FE",
  },
  "white-medium-small-square": {
    name: "white-medium-small-square",
    category: "symbols",
    unicode: "_25fd",
    htmlEntity: "&#x25FD",
  },
  "black-medium-square": {
    name: "black-medium-square",
    category: "symbols",
    unicode: "_25fc",
    htmlEntity: "&#x25FC",
  },
  "white-medium-square": {
    name: "white-medium-square",
    category: "symbols",
    unicode: "_25fb",
    htmlEntity: "&#x25FB",
  },
  "black-large-square": {
    name: "black-large-square",
    category: "symbols",
    unicode: "_2b1b",
    htmlEntity: "&#x2B1B",
  },
  "white-large-square": {
    name: "white-large-square",
    category: "symbols",
    unicode: "_2b1c",
    htmlEntity: "&#x2B1C",
  },
  "orange-square": {
    name: "orange-square",
    category: "symbols",
    unicode: "_1f7e7",
    htmlEntity: "&#x1F7E7",
  },
  "blue-square": {
    name: "blue-square",
    category: "symbols",
    unicode: "_1f7e6",
    htmlEntity: "&#x1F7E6",
  },
  "red-square": {
    name: "red-square",
    category: "symbols",
    unicode: "_1f7e5",
    htmlEntity: "&#x1F7E5",
  },
  "brown-square": {
    name: "brown-square",
    category: "symbols",
    unicode: "_1f7eb",
    htmlEntity: "&#x1F7EB",
  },
  "purple-square": {
    name: "purple-square",
    category: "symbols",
    unicode: "_1f7ea",
    htmlEntity: "&#x1F7EA",
  },
  "green-square": {
    name: "green-square",
    category: "symbols",
    unicode: "_1f7e9",
    htmlEntity: "&#x1F7E9",
  },
  "yellow-square": {
    name: "yellow-square",
    category: "symbols",
    unicode: "_1f7e8",
    htmlEntity: "&#x1F7E8",
  },
  "speaker-low-volume": {
    name: "speaker-low-volume",
    category: "symbols",
    unicode: "_1f508",
    htmlEntity: "&#x1F508",
  },
  "muted-speaker": {
    name: "muted-speaker",
    category: "symbols",
    unicode: "_1f507",
    htmlEntity: "&#x1F507",
  },
  "speaker-medium-volume": {
    name: "speaker-medium-volume",
    category: "symbols",
    unicode: "_1f509",
    htmlEntity: "&#x1F509",
  },
  "speaker-high-volume": {
    name: "speaker-high-volume",
    category: "symbols",
    unicode: "_1f50a",
    htmlEntity: "&#x1F50A",
  },
  bell: {
    name: "bell",
    category: "symbols",
    unicode: "_1f514",
    htmlEntity: "&#x1F514",
  },
  "bell-with-slash": {
    name: "bell-with-slash",
    category: "symbols",
    unicode: "_1f515",
    htmlEntity: "&#x1F515",
  },
  megaphone: {
    name: "megaphone",
    category: "symbols",
    unicode: "_1f4e3",
    htmlEntity: "&#x1F4E3",
  },
  loudspeaker: {
    name: "loudspeaker",
    category: "symbols",
    unicode: "_1f4e2",
    htmlEntity: "&#x1F4E2",
  },
  "left-speech-bubble": {
    name: "left-speech-bubble",
    category: "symbols",
    unicode: "_1f5e8",
    htmlEntity: "&#x1F5E8",
  },
  "eye-in-speech-bubble": {
    name: "eye-in-speech-bubble",
    category: "symbols",
    unicode: "_1f441-1f5e8",
    htmlEntity: "&#x1F441;&#x1F5E8",
  },
  "speech-balloon": {
    name: "speech-balloon",
    category: "symbols",
    unicode: "_1f4ac",
    htmlEntity: "&#x1F4AC",
  },
  "thought-balloon": {
    name: "thought-balloon",
    category: "symbols",
    unicode: "_1f4ad",
    htmlEntity: "&#x1F4AD",
  },
  "right-anger-bubble": {
    name: "right-anger-bubble",
    category: "symbols",
    unicode: "_1f5ef",
    htmlEntity: "&#x1F5EF",
  },
  "spade-suit": {
    name: "spade-suit",
    category: "symbols",
    unicode: "_2660",
    htmlEntity: "&#x2660",
  },
  "club-suit": {
    name: "club-suit",
    category: "symbols",
    unicode: "_2663",
    htmlEntity: "&#x2663",
  },
  "heart-suit": {
    name: "heart-suit",
    category: "symbols",
    unicode: "_2665",
    htmlEntity: "&#x2665",
  },
  "diamond-suit": {
    name: "diamond-suit",
    category: "symbols",
    unicode: "_2666",
    htmlEntity: "&#x2666",
  },
  joker: {
    name: "joker",
    category: "symbols",
    unicode: "_1f0cf",
    htmlEntity: "&#x1F0CF",
  },
  "flower-playing-cards": {
    name: "flower-playing-cards",
    category: "symbols",
    unicode: "_1f3b4",
    htmlEntity: "&#x1F3B4",
  },
  "mahjong-red-dragon": {
    name: "mahjong-red-dragon",
    category: "symbols",
    unicode: "_1f004",
    htmlEntity: "&#x1F004",
  },
  "one-o’clock": {
    name: "one-o’clock",
    category: "symbols",
    unicode: "_1f550",
    htmlEntity: "&#x1F550",
  },
  "two-o’clock": {
    name: "two-o’clock",
    category: "symbols",
    unicode: "_1f551",
    htmlEntity: "&#x1F551",
  },
  "three-o’clock": {
    name: "three-o’clock",
    category: "symbols",
    unicode: "_1f552",
    htmlEntity: "&#x1F552",
  },
  "four-o’clock": {
    name: "four-o’clock",
    category: "symbols",
    unicode: "_1f553",
    htmlEntity: "&#x1F553",
  },
  "five-o’clock": {
    name: "five-o’clock",
    category: "symbols",
    unicode: "_1f554",
    htmlEntity: "&#x1F554",
  },
  "six-o’clock": {
    name: "six-o’clock",
    category: "symbols",
    unicode: "_1f555",
    htmlEntity: "&#x1F555",
  },
  "seven-o’clock": {
    name: "seven-o’clock",
    category: "symbols",
    unicode: "_1f556",
    htmlEntity: "&#x1F556",
  },
  "eight-o’clock": {
    name: "eight-o’clock",
    category: "symbols",
    unicode: "_1f557",
    htmlEntity: "&#x1F557",
  },
  "nine-o’clock": {
    name: "nine-o’clock",
    category: "symbols",
    unicode: "_1f558",
    htmlEntity: "&#x1F558",
  },
  "ten-o’clock": {
    name: "ten-o’clock",
    category: "symbols",
    unicode: "_1f559",
    htmlEntity: "&#x1F559",
  },
  "eleven-o’clock": {
    name: "eleven-o’clock",
    category: "symbols",
    unicode: "_1f55a",
    htmlEntity: "&#x1F55A",
  },
  "twelve-o’clock": {
    name: "twelve-o’clock",
    category: "symbols",
    unicode: "_1f55b",
    htmlEntity: "&#x1F55B",
  },
  "one-thirty": {
    name: "one-thirty",
    category: "symbols",
    unicode: "_1f55c",
    htmlEntity: "&#x1F55C",
  },
  "two-thirty": {
    name: "two-thirty",
    category: "symbols",
    unicode: "_1f55d",
    htmlEntity: "&#x1F55D",
  },
  "three-thirty": {
    name: "three-thirty",
    category: "symbols",
    unicode: "_1f55e",
    htmlEntity: "&#x1F55E",
  },
  "four-thirty": {
    name: "four-thirty",
    category: "symbols",
    unicode: "_1f55f",
    htmlEntity: "&#x1F55F",
  },
  "five-thirty": {
    name: "five-thirty",
    category: "symbols",
    unicode: "_1f560",
    htmlEntity: "&#x1F560",
  },
  "six-thirty": {
    name: "six-thirty",
    category: "symbols",
    unicode: "_1f561",
    htmlEntity: "&#x1F561",
  },
  "seven-thirty": {
    name: "seven-thirty",
    category: "symbols",
    unicode: "_1f562",
    htmlEntity: "&#x1F562",
  },
  "eight-thirty": {
    name: "eight-thirty",
    category: "symbols",
    unicode: "_1f563",
    htmlEntity: "&#x1F563",
  },
  "nine-thirty": {
    name: "nine-thirty",
    category: "symbols",
    unicode: "_1f564",
    htmlEntity: "&#x1F564",
  },
  "ten-thirty": {
    name: "ten-thirty",
    category: "symbols",
    unicode: "_1f565",
    htmlEntity: "&#x1F565",
  },
  "eleven-thirty": {
    name: "eleven-thirty",
    category: "symbols",
    unicode: "_1f566",
    htmlEntity: "&#x1F566",
  },
  "twelve-thirty": {
    name: "twelve-thirty",
    category: "symbols",
    unicode: "_1f567",
    htmlEntity: "&#x1F567",
  },
  "digit-zero": {
    name: "digit-zero",
    category: "symbols",
    unicode: "_0030",
    htmlEntity: "&#x0030",
  },
  "digit-one": {
    name: "digit-one",
    category: "symbols",
    unicode: "_0031",
    htmlEntity: "&#x0031",
  },
  "digit-two": {
    name: "digit-two",
    category: "symbols",
    unicode: "_0032",
    htmlEntity: "&#x0032",
  },
  "digit-three": {
    name: "digit-three",
    category: "symbols",
    unicode: "_0033",
    htmlEntity: "&#x0033",
  },
  "digit-four": {
    name: "digit-four",
    category: "symbols",
    unicode: "_0034",
    htmlEntity: "&#x0034",
  },
  "digit-five": {
    name: "digit-five",
    category: "symbols",
    unicode: "_0035",
    htmlEntity: "&#x0035",
  },
  "digit-six": {
    name: "digit-six",
    category: "symbols",
    unicode: "_0036",
    htmlEntity: "&#x0036",
  },
  "digit-seven": {
    name: "digit-seven",
    category: "symbols",
    unicode: "_0037",
    htmlEntity: "&#x0037",
  },
  "digit-eight": {
    name: "digit-eight",
    category: "symbols",
    unicode: "_0038",
    htmlEntity: "&#x0038",
  },
  "digit-nine": {
    name: "digit-nine",
    category: "symbols",
    unicode: "_0039",
    htmlEntity: "&#x0039",
  },
  "pound-symbol": {
    name: "pound-symbol",
    category: "symbols",
    unicode: "_0023",
    htmlEntity: "&#x0023",
  },
  asterisk: {
    name: "asterisk",
    category: "symbols",
    unicode: "_002a",
    htmlEntity: "&#x002A",
  },
  "female-sign": {
    name: "female-sign",
    category: "symbols",
    unicode: "_2640",
    htmlEntity: "&#x2640",
  },
  "male-sign": {
    name: "male-sign",
    category: "symbols",
    unicode: "_2642",
    htmlEntity: "&#x2642",
  },
  "transgender-symbol": {
    name: "transgender-symbol",
    category: "symbols",
    unicode: "_26a7",
    htmlEntity: "&#x26A7",
  },
  "medical-symbol": {
    name: "medical-symbol",
    category: "symbols",
    unicode: "_2695",
    htmlEntity: "&#x2695",
  },
};
