import { EmojiInformation } from "../types/emojiInformation";

export const TRAVEL_AND_PLACES: EmojiInformation = {
  "🚗": {
    name: "automobile",
    category: "travel",
    unicode: "_1f697",
    htmlEntity: "&#x1F697",
  },
  "🚕": {
    name: "taxi",
    category: "travel",
    unicode: "_1f695",
    htmlEntity: "&#x1F695",
  },
  "🚙": {
    name: "sport-utility-vehicle",
    category: "travel",
    unicode: "_1f699",
    htmlEntity: "&#x1F699",
  },
  "🛻": {
    name: "pickup-truck",
    category: "travel",
    unicode: "_1f6fb",
    htmlEntity: "&#x1F6FB",
  },
  "🚌": {
    name: "bus",
    category: "travel",
    unicode: "_1f68c",
    htmlEntity: "&#x1F68C",
  },
  "🚎": {
    name: "trolleybus",
    category: "travel",
    unicode: "_1f68e",
    htmlEntity: "&#x1F68E",
  },
  "🏎": {
    name: "racing-car",
    category: "travel",
    unicode: "_1f3ce",
    htmlEntity: "&#x1F3CE",
  },
  "🚓": {
    name: "police-car",
    category: "travel",
    unicode: "_1f693",
    htmlEntity: "&#x1F693",
  },
  "🚑": {
    name: "ambulance",
    category: "travel",
    unicode: "_1f691",
    htmlEntity: "&#x1F691",
  },
  "🚒": {
    name: "fire-engine",
    category: "travel",
    unicode: "_1f692",
    htmlEntity: "&#x1F692",
  },
  "🚐": {
    name: "minibus",
    category: "travel",
    unicode: "_1f690",
    htmlEntity: "&#x1F690",
  },
  "🚚": {
    name: "delivery-truck",
    category: "travel",
    unicode: "_1f69a",
    htmlEntity: "&#x1F69A",
  },
  "🚛": {
    name: "articulated-lorry",
    category: "travel",
    unicode: "_1f69b",
    htmlEntity: "&#x1F69B",
  },
  "🚜": {
    name: "tractor",
    category: "travel",
    unicode: "_1f69c",
    htmlEntity: "&#x1F69C",
  },
  "🦯": {
    name: "probing-cane",
    category: "travel",
    unicode: "_1f9af",
    htmlEntity: "&#x1F9AF",
  },
  "🦽": {
    name: "manual-wheelchair",
    category: "travel",
    unicode: "_1f9bd",
    htmlEntity: "&#x1F9BD",
  },
  "🦼": {
    name: "motorized-wheelchair",
    category: "travel",
    unicode: "_1f9bc",
    htmlEntity: "&#x1F9BC",
  },
  "🛴": {
    name: "kick-scooter",
    category: "travel",
    unicode: "_1f6f4",
    htmlEntity: "&#x1F6F4",
  },
  "🚲": {
    name: "bicycle",
    category: "travel",
    unicode: "_1f6b2",
    htmlEntity: "&#x1F6B2",
  },
  "🛵": {
    name: "motor-scooter",
    category: "travel",
    unicode: "_1f6f5",
    htmlEntity: "&#x1F6F5",
  },
  "🏍": {
    name: "motorcycle",
    category: "travel",
    unicode: "_1f3cd",
    htmlEntity: "&#x1F3CD",
  },
  "🛺": {
    name: "auto-rickshaw",
    category: "travel",
    unicode: "_1f6fa",
    htmlEntity: "&#x1F6FA",
  },
  "🚨": {
    name: "police-car-light",
    category: "travel",
    unicode: "_1f6a8",
    htmlEntity: "&#x1F6A8",
  },
  "🚔": {
    name: "oncoming-police-car",
    category: "travel",
    unicode: "_1f694",
    htmlEntity: "&#x1F694",
  },
  "🚍": {
    name: "oncoming-bus",
    category: "travel",
    unicode: "_1f68d",
    htmlEntity: "&#x1F68D",
  },
  "🚘": {
    name: "oncoming-automobile",
    category: "travel",
    unicode: "_1f698",
    htmlEntity: "&#x1F698",
  },
  "🚖": {
    name: "oncoming-taxi",
    category: "travel",
    unicode: "_1f696",
    htmlEntity: "&#x1F696",
  },
  "🚡": {
    name: "aerial-tramway",
    category: "travel",
    unicode: "_1f6a1",
    htmlEntity: "&#x1F6A1",
  },
  "🚠": {
    name: "mountain-cableway",
    category: "travel",
    unicode: "_1f6a0",
    htmlEntity: "&#x1F6A0",
  },
  "🚟": {
    name: "suspension-railway",
    category: "travel",
    unicode: "_1f69f",
    htmlEntity: "&#x1F69F",
  },
  "🚃": {
    name: "railway-car",
    category: "travel",
    unicode: "_1f683",
    htmlEntity: "&#x1F683",
  },
  "🚋": {
    name: "tram-car",
    category: "travel",
    unicode: "_1f68b",
    htmlEntity: "&#x1F68B",
  },
  "🚞": {
    name: "mountain-railway",
    category: "travel",
    unicode: "_1f69e",
    htmlEntity: "&#x1F69E",
  },
  "🚝": {
    name: "monorail",
    category: "travel",
    unicode: "_1f69d",
    htmlEntity: "&#x1F69D",
  },
  "🚄": {
    name: "high-speed-train",
    category: "travel",
    unicode: "_1f684",
    htmlEntity: "&#x1F684",
  },
  "🚅": {
    name: "bullet-train",
    category: "travel",
    unicode: "_1f685",
    htmlEntity: "&#x1F685",
  },
  "🚈": {
    name: "light-rail",
    category: "travel",
    unicode: "_1f688",
    htmlEntity: "&#x1F688",
  },
  "🚂": {
    name: "locomotive",
    category: "travel",
    unicode: "_1f682",
    htmlEntity: "&#x1F682",
  },
  "🚆": {
    name: "train",
    category: "travel",
    unicode: "_1f686",
    htmlEntity: "&#x1F686",
  },
  "🚇": {
    name: "metro",
    category: "travel",
    unicode: "_1f687",
    htmlEntity: "&#x1F687",
  },
  "🚊": {
    name: "tram",
    category: "travel",
    unicode: "_1f68a",
    htmlEntity: "&#x1F68A",
  },
  "🚉": {
    name: "station",
    category: "travel",
    unicode: "_1f689",
    htmlEntity: "&#x1F689",
  },
  "✈": {
    name: "airplane",
    category: "travel",
    unicode: "_2708",
    htmlEntity: "&#x2708",
  },
  "🛫": {
    name: "airplane-departure",
    category: "travel",
    unicode: "_1f6eb",
    htmlEntity: "&#x1F6EB",
  },
  "🛬": {
    name: "airplane-arrival",
    category: "travel",
    unicode: "_1f6ec",
    htmlEntity: "&#x1F6EC",
  },
  "🛩": {
    name: "small-airplane",
    category: "travel",
    unicode: "_1f6e9",
    htmlEntity: "&#x1F6E9",
  },
  "💺": {
    name: "seat",
    category: "travel",
    unicode: "_1f4ba",
    htmlEntity: "&#x1F4BA",
  },
  "🛰": {
    name: "satellite",
    category: "travel",
    unicode: "_1f6f0",
    htmlEntity: "&#x1F6F0",
  },
  "🚀": {
    name: "rocket",
    category: "travel",
    unicode: "_1f680",
    htmlEntity: "&#x1F680",
  },
  "🛸": {
    name: "flying-saucer",
    category: "travel",
    unicode: "_1f6f8",
    htmlEntity: "&#x1F6F8",
  },
  "🚁": {
    name: "helicopter",
    category: "travel",
    unicode: "_1f681",
    htmlEntity: "&#x1F681",
  },
  "🛶": {
    name: "canoe",
    category: "travel",
    unicode: "_1f6f6",
    htmlEntity: "&#x1F6F6",
  },
  "⛵": {
    name: "sailboat",
    category: "travel",
    unicode: "_26f5",
    htmlEntity: "&#x26F5",
  },
  "🚤": {
    name: "speedboat",
    category: "travel",
    unicode: "_1f6a4",
    htmlEntity: "&#x1F6A4",
  },
  "🛥": {
    name: "motor-boat",
    category: "travel",
    unicode: "_1f6e5",
    htmlEntity: "&#x1F6E5",
  },
  "🛳": {
    name: "passenger-ship",
    category: "travel",
    unicode: "_1f6f3",
    htmlEntity: "&#x1F6F3",
  },
  "⛴": {
    name: "ferry",
    category: "travel",
    unicode: "_26f4",
    htmlEntity: "&#x26F4",
  },
  "🚢": {
    name: "ship",
    category: "travel",
    unicode: "_1f6a2",
    htmlEntity: "&#x1F6A2",
  },
  "⚓": {
    name: "anchor",
    category: "travel",
    unicode: "_2693",
    htmlEntity: "&#x2693",
  },
  "⛽": {
    name: "fuel-pump",
    category: "travel",
    unicode: "_26fd",
    htmlEntity: "&#x26FD",
  },
  "🚧": {
    name: "construction",
    category: "travel",
    unicode: "_1f6a7",
    htmlEntity: "&#x1F6A7",
  },
  "🚦": {
    name: "vertical-traffic-light",
    category: "travel",
    unicode: "_1f6a6",
    htmlEntity: "&#x1F6A6",
  },
  "🚥": {
    name: "horizontal-traffic-light",
    category: "travel",
    unicode: "_1f6a5",
    htmlEntity: "&#x1F6A5",
  },
  "🚏": {
    name: "bus-stop",
    category: "travel",
    unicode: "_1f68f",
    htmlEntity: "&#x1F68F",
  },
  "🗺": {
    name: "world-map",
    category: "travel",
    unicode: "_1f5fa",
    htmlEntity: "&#x1F5FA",
  },
  "🗿": {
    name: "moai",
    category: "travel",
    unicode: "_1f5ff",
    htmlEntity: "&#x1F5FF",
  },
  "🗽": {
    name: "statue-of-liberty",
    category: "travel",
    unicode: "_1f5fd",
    htmlEntity: "&#x1F5FD",
  },
  "🗼": {
    name: "tokyo-tower",
    category: "travel",
    unicode: "_1f5fc",
    htmlEntity: "&#x1F5FC",
  },
  "🏰": {
    name: "castle",
    category: "travel",
    unicode: "_1f3f0",
    htmlEntity: "&#x1F3F0",
  },
  "🏯": {
    name: "japanese-castle",
    category: "travel",
    unicode: "_1f3ef",
    htmlEntity: "&#x1F3EF",
  },
  "🏟": {
    name: "stadium",
    category: "travel",
    unicode: "_1f3df",
    htmlEntity: "&#x1F3DF",
  },
  "🎡": {
    name: "ferris-wheel",
    category: "travel",
    unicode: "_1f3a1",
    htmlEntity: "&#x1F3A1",
  },
  "🎢": {
    name: "roller-coaster",
    category: "travel",
    unicode: "_1f3a2",
    htmlEntity: "&#x1F3A2",
  },
  "🎠": {
    name: "carousel-horse",
    category: "travel",
    unicode: "_1f3a0",
    htmlEntity: "&#x1F3A0",
  },
  "⛲": {
    name: "fountain",
    category: "travel",
    unicode: "_26f2",
    htmlEntity: "&#x26F2",
  },
  "⛱": {
    name: "umbrella-on-ground",
    category: "travel",
    unicode: "_26f1",
    htmlEntity: "&#x26F1",
  },
  "🏖": {
    name: "beach-with-umbrella",
    category: "travel",
    unicode: "_1f3d6",
    htmlEntity: "&#x1F3D6",
  },
  "🏝": {
    name: "desert-island",
    category: "travel",
    unicode: "_1f3dd",
    htmlEntity: "&#x1F3DD",
  },
  "🏜": {
    name: "desert",
    category: "travel",
    unicode: "_1f3dc",
    htmlEntity: "&#x1F3DC",
  },
  "🌋": {
    name: "volcano",
    category: "travel",
    unicode: "_1f30b",
    htmlEntity: "&#x1F30B",
  },
  "⛰": {
    name: "mountain",
    category: "travel",
    unicode: "_26f0",
    htmlEntity: "&#x26F0",
  },
  "🏔": {
    name: "snow-capped-mountain",
    category: "travel",
    unicode: "_1f3d4",
    htmlEntity: "&#x1F3D4",
  },
  "🗻": {
    name: "mount-fuji",
    category: "travel",
    unicode: "_1f5fb",
    htmlEntity: "&#x1F5FB",
  },
  "🏕": {
    name: "camping",
    category: "travel",
    unicode: "_1f3d5",
    htmlEntity: "&#x1F3D5",
  },
  "⛺": {
    name: "tent",
    category: "travel",
    unicode: "_26fa",
    htmlEntity: "&#x26FA",
  },
  "🏠": {
    name: "house",
    category: "travel",
    unicode: "_1f3e0",
    htmlEntity: "&#x1F3E0",
  },
  "🏡": {
    name: "house-with-garden",
    category: "travel",
    unicode: "_1f3e1",
    htmlEntity: "&#x1F3E1",
  },
  "🏘": {
    name: "houses",
    category: "travel",
    unicode: "_1f3d8",
    htmlEntity: "&#x1F3D8",
  },
  "🏚": {
    name: "derelict-house",
    category: "travel",
    unicode: "_1f3da",
    htmlEntity: "&#x1F3DA",
  },
  "🛖": {
    name: "hut",
    category: "travel",
    unicode: "_1f6d6",
    htmlEntity: "&#x1F6D6",
  },
  "🏗": {
    name: "building-construction",
    category: "travel",
    unicode: "_1f3d7",
    htmlEntity: "&#x1F3D7",
  },
  "🏭": {
    name: "factory",
    category: "travel",
    unicode: "_1f3ed",
    htmlEntity: "&#x1F3ED",
  },
  "🏢": {
    name: "office-building",
    category: "travel",
    unicode: "_1f3e2",
    htmlEntity: "&#x1F3E2",
  },
  "🏬": {
    name: "department-store",
    category: "travel",
    unicode: "_1f3ec",
    htmlEntity: "&#x1F3EC",
  },
  "🏣": {
    name: "japanese-post-office",
    category: "travel",
    unicode: "_1f3e3",
    htmlEntity: "&#x1F3E3",
  },
  "🏤": {
    name: "post-office",
    category: "travel",
    unicode: "_1f3e4",
    htmlEntity: "&#x1F3E4",
  },
  "🏥": {
    name: "hospital",
    category: "travel",
    unicode: "_1f3e5",
    htmlEntity: "&#x1F3E5",
  },
  "🏦": {
    name: "bank",
    category: "travel",
    unicode: "_1f3e6",
    htmlEntity: "&#x1F3E6",
  },
  "🏨": {
    name: "hotel",
    category: "travel",
    unicode: "_1f3e8",
    htmlEntity: "&#x1F3E8",
  },
  "🏪": {
    name: "convenience-store",
    category: "travel",
    unicode: "_1f3ea",
    htmlEntity: "&#x1F3EA",
  },
  "🏫": {
    name: "school",
    category: "travel",
    unicode: "_1f3eb",
    htmlEntity: "&#x1F3EB",
  },
  "🏩": {
    name: "love-hotel",
    category: "travel",
    unicode: "_1f3e9",
    htmlEntity: "&#x1F3E9",
  },
  "💒": {
    name: "wedding",
    category: "travel",
    unicode: "_1f492",
    htmlEntity: "&#x1F492",
  },
  "🏛": {
    name: "classical-building",
    category: "travel",
    unicode: "_1f3db",
    htmlEntity: "&#x1F3DB",
  },
  "⛪": {
    name: "church",
    category: "travel",
    unicode: "_26ea",
    htmlEntity: "&#x26EA",
  },
  "🕌": {
    name: "mosque",
    category: "travel",
    unicode: "_1f54c",
    htmlEntity: "&#x1F54C",
  },
  "🕍": {
    name: "synagogue",
    category: "travel",
    unicode: "_1f54d",
    htmlEntity: "&#x1F54D",
  },
  "🛕": {
    name: "hindu-temple",
    category: "travel",
    unicode: "_1f6d5",
    htmlEntity: "&#x1F6D5",
  },
  "🕋": {
    name: "kaaba",
    category: "travel",
    unicode: "_1f54b",
    htmlEntity: "&#x1F54B",
  },
  "⛩": {
    name: "shinto-shrine",
    category: "travel",
    unicode: "_26e9",
    htmlEntity: "&#x26E9",
  },
  "🛤": {
    name: "railway-track",
    category: "travel",
    unicode: "_1f6e4",
    htmlEntity: "&#x1F6E4",
  },
  "🛣": {
    name: "motorway",
    category: "travel",
    unicode: "_1f6e3",
    htmlEntity: "&#x1F6E3",
  },
  "🗾": {
    name: "map-of-japan",
    category: "travel",
    unicode: "_1f5fe",
    htmlEntity: "&#x1F5FE",
  },
  "🎑": {
    name: "moon-viewing-ceremony",
    category: "travel",
    unicode: "_1f391",
    htmlEntity: "&#x1F391",
  },
  "🏞": {
    name: "national-park",
    category: "travel",
    unicode: "_1f3de",
    htmlEntity: "&#x1F3DE",
  },
  "🌅": {
    name: "sunrise",
    category: "travel",
    unicode: "_1f305",
    htmlEntity: "&#x1F305",
  },
  "🌄": {
    name: "sunrise-over-mountains",
    category: "travel",
    unicode: "_1f304",
    htmlEntity: "&#x1F304",
  },
  "🌠": {
    name: "shooting-star",
    category: "travel",
    unicode: "_1f320",
    htmlEntity: "&#x1F320",
  },
  "🎇": {
    name: "sparkler",
    category: "travel",
    unicode: "_1f387",
    htmlEntity: "&#x1F387",
  },
  "🎆": {
    name: "fireworks",
    category: "travel",
    unicode: "_1f386",
    htmlEntity: "&#x1F386",
  },
  "🌇": {
    name: "sunset",
    category: "travel",
    unicode: "_1f307",
    htmlEntity: "&#x1F307",
  },
  "🌆": {
    name: "cityscape-at-dusk",
    category: "travel",
    unicode: "_1f306",
    htmlEntity: "&#x1F306",
  },
  "🏙": {
    name: "cityscape",
    category: "travel",
    unicode: "_1f3d9",
    htmlEntity: "&#x1F3D9",
  },
  "🌃": {
    name: "night-with-stars",
    category: "travel",
    unicode: "_1f303",
    htmlEntity: "&#x1F303",
  },
  "🌌": {
    name: "milky-way",
    category: "travel",
    unicode: "_1f30c",
    htmlEntity: "&#x1F30C",
  },
  "🌉": {
    name: "bridge-at-night",
    category: "travel",
    unicode: "_1f309",
    htmlEntity: "&#x1F309",
  },
  "🌁": {
    name: "foggy",
    category: "travel",
    unicode: "_1f301",
    htmlEntity: "&#x1F301",
  },
};
